# 2026–2027 RESIDENTIAL ACADEMIC CALENDAR {#sec-academic-calendar}

### FALL TERM 2026

   |   
:-|---:
August 26 |	Classes Begin
September 7 |	Labor Day Holiday (No Classes) 
October 15–16 |	Fall Term Recess (No Classes) 
October 19 |	Begin Second-Half Term Courses
November 23–27 |	Thanksgiving Recess Holiday (No Classes) 
December 11 |	Last Day of Fall Term
December 14–17 |	Final Exams


### SPRING TERM 2027

   |   
:-|---:
January 13 |	Classes Begin
January 18 |	Martin Luther King Jr. Day Holiday (No Classes) 
March 4 |	Begin Second-Half Term Courses
March 15–19 |	Spring Term Recess (No Classes)
April 22 |	Student Research Symposium (No Day Classes, Evening Classes Meet)
April 30 |	Last Day of Spring Term
May 3–6 |	Final Exams
May 8 |	Honors Convocation \/ Baccalaureate
May 9 |	Commencement  


### MAY EXPERIENTIAL TERM 2027

   |   
:-|---:
May 12 |	Classes Begin
May 31 |	Memorial Day Holiday (No Classes) 
June 4 |	Last Day of May Experiential Term
June 5 |	Residence Halls Close


### SUMMER TERM 2027*
    
   |    
:-|---:
June 7 |	Classes Begin
June 18 |	Juneteenth Holiday (No Classes) 
July 5 |	Independence Day Holiday (No Classes) 
July 12 |	Last Day of Block A Courses
July 13 |	First Day of Block B Courses
August 13 |	Summer Term Ends: Last Day of Block B and Full-Term Courses


For a full listing of dates, please visit www.coe.edu: https://www.coe.edu/why-coe/events/calendar.  This website provides a list of all upcoming events
