# THE EDUCATIONAL PROGRAM {#sec-educational-program}

## **GRADUATION REQUIREMENTS**

All students granted an undergraduate degree from Coe must complete the specific requirements for one of four bachelor degrees (Bachelor of Arts [B.A.], Reduced-credit Bachelor of Arts [RC-B.A.] (Online Only), Bachelor of Science in Nursing [B.S.N.] or Bachelor of Science in Engineering [B.S.E.]). Students must complete the 5 General Education Requirements (Divisional Requirements, First-Year Experience, Writing Emphasis courses, Diversity Across the Curriculum courses and a Practicum), complete an area of study appropriate for their chosen degree with at least a 2.0 grade point average (GPA), earn at least 32 course credits (cc) (or 24 cc for the RC-B.A.) with grades leading to a cumulative GPA of 2.0 or higher, and comply with additional graduation policies listed in this section. No more than a total of two course credits from courses which are less than 0.5 credit can be used to meet the 32-credit (traditional B.A., B.S.N. or B.S.E) or 24-credit (RC-B.A.) graduation requirement.

## **GENERAL EDUCATION REQUIREMENTS**

A liberal arts education at Coe College prepares students to engage with the challenges they face as active participants in the twenty-first century. Coe graduates are informed by the knowledge acquired in the liberal arts tradition and equipped with the skills and knowledge that ground meaningful lives and fulfilling careers. Coe graduates are connected and accountable to local, national, and global communities and are prepared to engage with unfamiliar situations, emerging technologies, and diverse perspectives. 

Completion of all General Education Requirements is required for all students earning a first B.A., RC-B.A., B.S.N., or B.S.E. degree at Coe College. An appropriate transferred course, determined by the Office of the Registrar, with a grade of “C” (2.0) or better may be accepted to meet an individual requirement. The Office of the Registrar will be responsible for assessing how transfer courses will be applied to the General Education requirements.

Advanced Placement and International Baccalaureate courses may not be used to meet any part of these requirements. No more than two course credits with the same prefix may be used to fulfill the Divisional Requirements. A given course may be able to simultaneously contribute to more than one general education category, as these categories do not mutually exclude each other: Divisional Requirements, First-Year Experience, Writing Across the Curriculum, Diversity Across the Curriculum, and Practicum.

### **Divisional Requirements**

Students must complete each of the following requirements. No course can count in more than one divisional requirement.

1.	Fine Arts Requirement – A total of at least TWO course credits with a prefix of ARH, ART, CRW, MU, MUA, or THE. Students may also satisfy this requirement by completing NYT-250 Fine Arts in New York City, a component of Coe’s New York Term, described on page 56.
2.	Humanities Requirement – A total of at least TWO course credits with a prefix of AAM, CLA, COM, ENG, HIS, JPN, PHL, REL, or SPA.
3.	Natural Sciences and Mathematics Requirement – A total of at least ONE course credit with a prefix of BIO, CHM, CS, DS, ENR, MTH, PHY, or STA.
4.	Lab Science Requirement – A total of at least ONE course credit from courses with a lab component. Students must enroll in and pass both the lab and corresponding lecture to complete this requirement. Lab sections are denoted with an L at the end of their course codes.
5.	Social Sciences Requirement – A total of at least TWO course credits with a prefix of ANT, ECO, GS, POL, PSY, or SOC.

### **First-Year Experience**

Students who have not yet completed a full-time college term after high school graduation are required to complete a First-Year Experience in their first term at Coe. 

The student’s First-Year Experience at Coe is a deliberate strategy to engage first-year students across multiple dimensions of college life in the first year.  Components of the First-Year Experience include writing exercises, various campus events, and the First-Year Seminar (FYS), described in detail in this section of the catalog. Students who drop or fail their First-Year Seminar are required to complete a replacement course designated by the Registrar the following term.  The completion of this Spring Term course makes it possible for the student to fulfill the FYS graduation requirement.  For students who fail the Fall Term First-Year Seminar, successful completion of the Spring Term course also allows the grade in the FYS to be changed from “F” to “NP” on the transcript.

Students who begin their college enrollment in the Spring Term must also complete a course designated as a replacement.

#### **FS-110 First-Year Seminar (WE)**

Required of all first-year students who have not yet completed a full-time college term after high school graduation. The First-Year Seminar introduces students to college-level study with emphasis on critical thinking, writing, speaking, and research skills. Faculty offer first-year-only topics courses exploring issues from multiple perspectives within or across disciplines. Students in all sections prepare portfolios of their written work and attend a variety of cultural events on and off campus. Seminar instructors also serve as the primary academic advisors for first-year students in their respective sections. First-Year Seminars are writing emphasis and cannot fulfill any distributional, cultural perspective, or major requirements.

### **Writing Emphasis (WE) Courses**

Only designated WE courses in which a student earns a grade of “C” (2.0) or better count toward fulfillment of this requirement.

Only designated courses taken at Coe College count toward fulfillment of this requirement.

Undergraduate degree-seeking* students 

- who start at Coe College or who transfer fewer than 8 course credits earned after graduation from high school must complete at least 5 writing emphasis courses. Of these 5, one will usually be the FYS. Of the remaining 4, it is recommended (but not required) that at least 1 be taken outside the student’s intended major(s).
- who transfer at least 8 but fewer than 16 course credits to Coe, earned after graduation from high school, must complete at least 3 writing emphasis courses.
- who transfer 16 or more course credits to Coe, earned after graduation from high school, must complete at least 2 writing emphasis credits.

For all students, regardless of transfer credit, it is recommended (but not required) that at least one writing emphasis course be taken in the upper division within the student’s intended major(s). “Upper division” courses are defined in this case as those numbered 300 and above; upper division writing emphasis courses could include both scheduled classroom courses and arranged writing-based capstone projects (such as a thesis). See Departmental Writing Plans for more information on writing in the major(s).

*Students seeking a second undergraduate degree from Coe should see Second Baccalaureate Degree p. 26

*Writing Across the Curriculum: Statement of Guiding Principles*

As stated in the Coe College Mission Statement, our reason to exist as an institution is to ready students intellectually, professionally, and socially to lead productive and satisfying lives in the global society of the 21st century. In accordance with this mission, our curriculum requires that students undertake “a series of intensive writing experiences, spread across four years of study.” This requirement is known as Writing Across the Curriculum, the guiding principles of which are detailed below.

As a philosophy, Writing Across the Curriculum asserts that writing is most effectively learned in context: to varied audiences, with varied purposes. In adopting this philosophy, Coe College has committed to making writing-intensive experiences available to students in all disciplines. Known as “Writing Emphasis” credits, these courses are divergent in subject matter but aligned in their commitment to giving students content-rich and context-specific writing experiences that foster a critical flexibility in transferring knowledge about effective writing to multiple, even unknown, contexts.

Therefore, students who complete the requisite number of writing emphasis courses will graduate from Coe knowing that writing is both a means and an end: a method for exploring ideas and deepening one’s knowledge as well as a tool for sharing that knowledge and expressing one’s point of view. Similarly, graduating students will know that the practice of writing is a recursive process rooted in revision, which refers both to the reconsideration of one’s ideas and to the refinement of prose, and this process unfolds over a lifetime. Understanding that students will encounter innumerable writing situations in their lives, many of which may be unfamiliar to them, they will graduate from Coe having developed the confidence and self-efficacy necessary to adapt or draw from their existing knowledge in order to navigate new contexts.

Although many courses at Coe may include writing activities, courses endorsed by Writing Across the Curriculum are those in which:

- Students are given opportunities to practice revision, whether via multiple drafts of a single project or multiple iterations of the same type of assignment;
- Students receive instructor feedback on written work to facilitate revision; and
- Writing assignments are frequent enough that they are integral to the learning throughout the course, enabling students to develop in one or more of the following learning outcomes, as appropriate to discipline and course objectives:
  - How to write for specific purposes and audiences
    - *Including attention to the ways purposes and audiences shape form, mode, voice, method, organization, engagement with and citation of research, and/or creativity and imagination*
  - How to engage in critical thinking
    - *Particularly how to conduct analysis, how to synthesize information, how to interpret and/or use evidence and data, and how to present one’s ideas coherently and stylistically*
  - How to practice, assess, and develop effective habits for writing
    - *Specifically, how to read deeply, how to begin and later practice selection in research, how to be a skilled reader of one’s own and others’ in-process writing, how to accept and interpret feedback, and how to revise writing, all of which are parts of the process of learning how to have and develop ideas*
  - How to engage in writing as a method for learning and discovery
    - *For deepening knowledge, thinking through questions and problems, and reflecting on connections and growth*
  - How to name and describe one’s own knowledge for others
    - *For example, in the form of personal statements for application to graduate study, cover letters and resumes for entering and advancing in the workforce, or other forms of self-summary that facilitate transition from the baccalaureate environment through the broader public.*

Many writing emphasis sections are offered each year. First-Year Seminars (all of which are Writing emphasis), Divisional requirements, Diversity across the Curriculum, or major courses that are also designated as writing emphasis courses may be used to satisfy both requirements.

In this catalog, writing emphasis courses are designated by a (WE) after the course title, e.g. “COM-141 Introduction to Journalism (WE).” In other contexts, the course code may end with a “W” or “WE” (e.g. COM-141-W or COM-141-WE). All sections of such a course, regardless of instructor, will carry writing emphasis credit.

#### Writing Emphasis Course Listing

- AAM-137 African American Literature
- AAM-367 Studies in African American Literature
- ACC-313 Fraud Examination
- ACC-413 Auditing
- ARH-307 Modern and Contemporary Art
- ART-464 Seminar in Art and Visual Studies I
- ASC-216 History of Modern Korea
- AVS-401 Aviation Seminar
- AVS-403 Aviation Safety
- BIO-145L Introduction to Biology Laboratory
- BIO-155L Organismal and Ecological Biology Laboratory
- BIO-205L General Botany Laboratory
- BIO-235L Genetics Laboratory
- BIO-295L Spatial Ecology Laboratory
- BIO-325 Microbiology
- BIO-415L Developmental Biology Laboratory
- BIO-425L Ecology Lab
- BUS-190 Statistical Analysis
- BUS-330 Principles of Marketing
- BUS-375 Business Ethics
- BUS-387 Advanced Topics in Human Resource Management
- BUS-460 Advertising 
- BUS-461 Marketing Decision-Making & Strategy
- BUS-464 Seminar in Management
- BUS-470 Strategic Management
- CHM-211L Analytical Chemistry Lab
- CHM-341 Physical Chemistry I
- CHM-422 Synthesis Laboratory
- CHM-451L Inorganic Chemistry Lab
- COM-137 Interpersonal Communication 
- COM-141 Introduction to Journalism
- COM-151 Introduction to New Media Studies
- COM-157 Introduction to Media Analysis
- COM-231 Communication in Teams
- COM-236 Intercultural Communication
- COM-241 Multimedia Journalism
- COM-257 Sex, Race, and Gender in the Media
- COM-267 Environmental Rhetoric 
- COM-281 Introduction to Research Methods
- COM-322 Professional Communication and Writing
- COM-323 Relational Communication: Theory and Application
- COM-327 Organizational Comm
- COM-332 Health Communication
- COM-341 Digital Storytelling
- COM-377 Language, Power, and Social Change
- COM-381 Research Methods in Communication Studies
- COM-394 Directed Learning in Communication
- COM-435 Advanced Topics in Human Communication
- COM-437 Advanced Topics in Human Communication
- COM-444 Independent Study in Communication Studies
- COM-455 Special Topics in Media Analysis
- COM-457 Special Topics in Media Analysis
- COM-465 Advanced Topics in Cultural and Critical Communication
- COM-467 Advanced Topics in Cultural and Critical Communication
- CRW-105 Exploring Creative Writing
- CRW-106 Exploring Creative Writing: Non-Western Perspectives
- CRW-107 Exploring Creative Writing: United States Pluralism
- CRW-125 Introduction to Creative Writing
- CRW-135 Writer’s Colony 
- CRW-225 Creative Nonfiction Workshop 1
- CRW-255 Playwriting Workshop 1
- CRW-280 Poetry Workshop
- CRW-290 Fiction Workshop
- CRW-325 Creative Nonfiction Workshop 2
- CRW-345 Writing Wilderness
- CRW-350 Screenwriting
- CRW-355 Playwriting Workshop 2
- CRW-380 Poetry Workshop
- CRW-390 Fiction Workshop
- CRW-394 Directed Learning in Creative Writing
- CRW-455 Playwriting Workshop 3
- CRW-480 Poetry Workshop
- CRW-484 Advanced Topics in Creative Writing
- CRW-490 Fiction Workshop
- CRW-492 Manuscript Workshop
- CS-480 Software Engineering Capstone
- CS-280 Algorithms in Society
- ECC-112 Introduction to Writing Center Theory & Practice
- ECC-312 Writing Center Theory & Practice
- ECC-345 Writing Process
- ECO-375 Econometrics
- ECO-395 History of Economic Thought
- ECO-424 Political Economy
- ECO-445 Econometrics II
- EDU-105 Foundations of Education
- EDU-187 Human Relations
- EDU-215 Practicum in Education
- EDU-220 Professional Writing for Teachers
- EDU-237 English Language Learners
- EDU-260 Content Area Language and Literacy
- EDU-270 Literature K-12
- EDU-305 Methods of Elementary Science
- EDU-310 Methods of Secondary Business Education
- EDU-311 Methods of Secondary Language Arts
- EDU-312 Methods of Secondary Social Studies
- EDU-313 Methods of Secondary Mathematics
- EDU-320 Methods of Secondary Science
- EDU-321 Methods of World Language K-12
- EDU-335 Methods of Elementary Mathematics
- EDU-345 Methods of Elementary Language Arts
- EDU-355 Methods of Elementary Reading
- EDU-365 Methods of Elementary Social Studies
- EDU-395 Diagnostic Reading and Tutorial
- EDU-481 Student Teaching in Art at the Secondary School 
- EDU-482 Student Teaching in Physical Education at the Secondary School 
- EDU-483 Student Teaching in Art at the Elementary School 
- EDU-485 Student Teaching in Physical Education at the Elementary School 
- EDU-489 Student Teaching in the Senior High School  
- EDU-490 Student Teaching in Middle School or Junior High School  
- EDU-491 Student Teaching in the Upper Elementary Grades: Grades 3-6 
- EDU-492 Student Teaching in the Primary Grades: Grades K-3 
- ENG-111 Introduction to Literary Studies: The Art of Reading and Writing
- ENG-117 Asian American Literature
- ENG-127 Social Justice and Literature
- ENG-137 African American Literature
- ENG-146 Introduction to Postcolonial Literature
- ENG-157 Latinx/Chicanx Literature
- ENG-206 Gender and Literature: NWP
- ENG-207 Gender and Literature: USP
- ENG-208 Gender and Literature: DWP
- ENG-281 Literatures in English 1800
- ENG-291 Literatures in English after 1800
- ENG-301 The Art of Literary Research
- ENG-312 Studies in Environmental Humanities
- ENG-327 Literature of the American Renaissance
- ENG-328 Dante’s Divine Comedy
- ENG-337 American Realism and Naturalism
- ENG-347 Studies in Modern or Contemporary American Literature
- ENG-357 Studies in Latinx/Chicanx Literature
- ENG-367 Studies in African American Literature
- ENG-375 Studies in European Literature
- ENG-378 Studies in Transatlantic Literature
- ENG-380 The Age of Chaucer
- ENG-382 Shakespeare: Comedies and Romances
- ENG-383 Shakespeare: Tragedies and Histories
- ENG-384 British Renaissance Literature
- ENG-385 Restoration and Eighteenth-Century British Literature
- ENG-388 Romantic Literature
- ENG-390 Victorian Literature
- ENG-392 The Nineteenth-Century British Novel
- ENG-393 Studies in Modern or Contemporary British Literature
- ENG-394 Directed Learning in English
- ENG-454 Honors Research
- ENG-464 Seminar in Literature
- ENG-467 Seminar in Literature: USP
- GS-107 Introduction to Gender and Sexuality
- GS-327 Theory and Methods in Gender and Sexuality Studies
- GS-387 Topics in Gender and Sexuality Studies
- HIS-205 The Historian’s Craft
- HIS-208 The First World War
- HIS-216 History of Modern Korea
- HIS-217 The American War in Vietnam
- HIS-218 The Second World War
- HIS-227 The American Civil War
- HIS-238 Modern France
- HIS-246 History of Modern China
- HIS-248 The French Revolution
- HIS-256 History of Modern Japan
- HIS-257 Native American History
- HIS-268 Latin America
- HIS-272 History of Medieval Europe
- HIS-275 Ancient Greek History
- HIS-276 The “Discovery” of America: Clash of Cultures and Alterities
- HIS-278 History of the Holocaust
- HIS-285 History of Ancient Rome
- HIS-286 Modern Middle East
- HIS-288 Renaissance and Reformation
- HIS-292 History of Modern England
- HIS-297 Woman in America
- HIS-300 Public History
- HIS-306 Revolution, Social Struggle, and Testimonio in Latin America 20th Century
- HIS-308 Legacies of the Cold War in Argentina, Peru, Columbia, and Chile
- HIS-316 Topics in History: NWP
- HIS-317 Topics in History: USP
- HIS-318 Topics in History: DWP
- HIS-325 Recent American History I
- HIS-328 Sport and Spectacle in Ancient Greece and Rome
- HIS-335 Recent American History II
- HIS-347 African American History
- HIS-355 19th Century Europe
- HIS-365 20th Century Europe
- HIS-372 Early Modern Europe
- HIS-387 American Colonial History
- HIS-395 United States Diplomatic History
- HIS-444 Independent Study
- HIS-465 Seminar in Ancient History
- HIS-466 Seminar in Modern East Asian History
- HIS-472 Seminar in American History I
- HIS-473 Seminar in American History II
- HIS-474 Seminar in Modern European
- KIN-347 Adapted Physical Education
- KIN-440 Organization and Admin of Physical Education and Athletics
- MTH-215 Foundations of Advanced Mathematics
- MTH-305 Advanced Geometry
- MTH-325 Differential Equations
- MTH-445 Complex Analysis
- MTH-455 Mathematical Modeling
- MTH-484 History of Mathematics
- MU-107 American Music
- MU-384 Conducting I
- MU-385 Conducting II
- NUR-305 Information Literature and Management
- NUR-375 Legal and Ethical Issues in Nursing
- NUR-425 Nursing Research
- NUR-455 Leadership and Contemporary Issues in Nursing
- PHL-105 Introduction to Philosophy
- PHL-128 Morality and Moral Controversies
- PHL-200 Bio-medical Ethics
- PHL-205 Environmental Ethics
- PHL-210 Topics in Philosophy
- PHL-220 Ancient Greek Philosophy
- PHL-265 Political Philosophy
- PHL-285 Law, Morality, and Punishment
- PHL-300 Early Modern Philosophy
- PHL-315 Advanced Topics in Philosophy
- PHL-320 Seminar in Ethics
- PHL-355 Seminar in Metaphysics and Epistemology
- PHL-394 Directed Learning in Philosophy
- PHL-444 Independent Study in Philosophy
- PHL-490 Philosophy in Colloquium
- PHL-494 Internship in Philosophy
- PHY-105 Physics: An Historical Approach
- PHY-236 Advanced Laboratory 1
- PHY-246 Advanced Laboratory 2
- PHY-311 Renewable Energy
- PHY-444 Independent Study
- PHY-454 Summer Research
- POL-210 Environmental Politics
- POL-258 World Politics
- POL-266 Latin American Politics
- POL-276 African Politics
- POL-277 Women and Politics in the United States
- POL-286 Asian Politics
- POL-298 European Politics
- POL-305 Terrorism
- POL-310 International Organization
- POL-325 The American Congress
- POL-345 The American Presidency
- POL-350 US Social Policy Process
- POL-365 American Foreign Policy
- POL-405 Contemporary Political Theory
- POL-435 Ancient and Medieval Political Theory
- POL-445 Modern Political Theory
- PR-205 Public Relations
- PSY-200 Research Methods
- PSY-295 Applied Career Development in Psychology
- PSY-325L Health Psychology Laboratory
- PSY-335L Sensation and Perception Laboratory
- PSY-355L Personality Laboratory
- PSY-464 Seminar in Psychology
- REL-101 Introduction to Religion
- REL-103 Belief and Unbelief
- REL-105 Introduction to Hebrew Bible
- REL-108 Western Religions
- REL-115 Introduction to New Testament
- REL-128 Judaism
- REL-136 Religions of China
- REL-138 Modern Judaism 
- REL-148 Islam
- REL-206 Buddhist Thought
- REL-215 The Rise of Christianity
- REL-217 Religion in America
- REL-226 Religions of China: Daoism 
- REL-236 Zen Buddhism
- REL-310 Early Christian Gospels
- REL-328 Dante’s Divine Comedy
- REL-330 Topics in Hebrew Bible
- REL-336 Tibetan Buddhist Culture
- REL-338 Modern Religious thought
- REL-365 The Letters of Paul
- REL-385 Advanced Topics in Religion
- REL-394 Directed Learning in Religion
- REL-396 Advanced Topics in Religion: NWP
- REL-444 Independent Study in Religion
- REL-494 Internship in Religion
- SOC-235 Methods of Sociological Research
- SOC-450 Sociological Theory
- SOC-464 Sociology Capstone
- SPA-315 Spanish Composition and Conversation
- SPA-325 Spanish Language and Literature
- SPA-330 Spanish for Heritage Speakers
- SPA-345 Introduction to Hispanic Literature
- SPA-394 Directed Learning
- SPA-412 Ecologies: Latin American Environmental Literature and Cultural Works
- SPA-418 Gender and Sexuality in the Hispanic World
- SPA-421 Nation, History and Literature
- SPA-428 Indigeneity, Blackness, and Ethnic Literatures in the Hispanic World
- SPA-431 Hispanic Graphic Novel: Theory and Practice
- SPA-432 Representations of Violence in Hispanic Cultural Productions
- SPA-442 Pop Culture, Media, and Cultural Studies
- SPA-443 Cinema and the Politics of Representation
- SPA-444 Independent Study
- SPA-446 Latin American and Spanish Short Stories
- SPA-451 Hispanic Cross-Over Literature: Theory and Practice
- SPA-455 Hispanic Drama and Performance: Theory and Practice
- SPA-457 Latinx Literature
- SPA-458 Travel Writing and Transatlantic Literature
- SPA-475 Topics in Hispanic Literature
- SPA-476 Topics in Hispanic Society and Culture
- SPA-485 Topics in Hispanic Literature
- SPA-486 Topics in Hispanic Society and Culture
- THE-228 Theatre History I
- THE-238 Theatre History II
- THE-255 Playwriting Workshop 1
- THE-288 History of Dress
- THE-290 Directing I
- THE-355 Playwriting Workshop 2
- THE-390 Directing II
- THE-455 Playwriting Workshop 3
- THE-464 Senior Seminar
- THE-494 Internship in Theatre Arts
- WLC-108 Cultural Studies and Literature in Translation
