# THE EDUCATIONAL PROGRAM {#sec-educational-program}

## GRADUATION REQUIREMENTS

All students granted an undergraduate degree from Coe must complete the specific requirements for one of four bachelor degrees (Bachelor of Arts [B.A.], Reduced-credit Bachelor of Arts [RC-B.A.] (Online Only), Bachelor of Science in Nursing [B.S.N.] or Bachelor of Science in Engineering [B.S.E.]). Students must complete the 5 General Education Requirements (Divisional Requirements, First-Year Experience, Writing Emphasis courses, Diversity Across the Curriculum courses and a Practicum), complete an area of study appropriate for their chosen degree with at least a 2.0 grade point average (GPA), earn at least 32 course credits (cc) (or 24 cc for the RC-B.A.) with grades leading to a cumulative GPA of 2.0 or higher, and comply with additional graduation policies listed in this section. No more than a total of two course credits from courses which are less than 0.5 credit can be used to meet the 32-credit (traditional B.A., B.S.N. or B.S.E) or 24-credit (RC-B.A.) graduation requirement.

## GENERAL EDUCATION REQUIREMENTS

A liberal arts education at Coe College prepares students to engage with the challenges they face as active participants in the twenty-first century. Coe graduates are informed by the knowledge acquired in the liberal arts tradition and equipped with the skills and knowledge that ground meaningful lives and fulfilling careers. Coe graduates are connected and accountable to local, national, and global communities and are prepared to engage with unfamiliar situations, emerging technologies, and diverse perspectives. 

Completion of all General Education Requirements is required for all students earning a first B.A., RC-B.A., B.S.N., or B.S.E. degree at Coe College. An appropriate transferred course, determined by the Office of the Registrar, with a grade of “C” (2.0) or better may be accepted to meet an individual requirement. The Office of the Registrar will be responsible for assessing how transfer courses will be applied to the General Education requirements.

Advanced Placement and International Baccalaureate courses may not be used to meet any part of these requirements. No more than two course credits with the same prefix may be used to fulfill the Divisional Requirements. A given course may be able to simultaneously contribute to more than one general education category, as these categories do not mutually exclude each other: Divisional Requirements, First-Year Experience, Writing Across the Curriculum, Diversity Across the Curriculum, and Practicum.

### Divisional Requirements

Students must complete each of the following requirements. No course can count in more than one divisional requirement.

1.	Fine Arts Requirement – A total of at least TWO course credits with a prefix of ARH, ART, CRW, MU, MUA, or THE. Students may also satisfy this requirement by completing NYT-250 Fine Arts in New York City, a component of Coe’s New York Term, described on page 56.
2.	Humanities Requirement – A total of at least TWO course credits with a prefix of AAM, CLA, COM, ENG, HIS, JPN, PHL, REL, or SPA.
3.	Natural Sciences and Mathematics Requirement – A total of at least ONE course credit with a prefix of BIO, CHM, CS, DS, ENR, MTH, PHY, or STA.
4.	Lab Science Requirement – A total of at least ONE course credit from courses with a lab component. Students must enroll in and pass both the lab and corresponding lecture to complete this requirement. Lab sections are denoted with an L at the end of their course codes.
5.	Social Sciences Requirement – A total of at least TWO course credits with a prefix of ANT, ECO, GS, POL, PSY, or SOC.

### First-Year Experience

Students who have not yet completed a full-time college term after high school graduation are required to complete a First-Year Experience in their first term at Coe. 

The student’s First-Year Experience at Coe is a deliberate strategy to engage first-year students across multiple dimensions of college life in the first year.  Components of the First-Year Experience include writing exercises, various campus events, and the First-Year Seminar (FYS), described in detail in this section of the catalog. Students who drop or fail their First-Year Seminar are required to complete a replacement course designated by the Registrar the following term.  The completion of this Spring Term course makes it possible for the student to fulfill the FYS graduation requirement.  For students who fail the Fall Term First-Year Seminar, successful completion of the Spring Term course also allows the grade in the FYS to be changed from “F” to “NP” on the transcript.

Students who begin their college enrollment in the Spring Term must also complete a course designated as a replacement.

#### FS-110 First-Year Seminar (WE)

Required of all first-year students who have not yet completed a full-time college term after high school graduation. The First-Year Seminar introduces students to college-level study with emphasis on critical thinking, writing, speaking, and research skills. Faculty offer first-year-only topics courses exploring issues from multiple perspectives within or across disciplines. Students in all sections prepare portfolios of their written work and attend a variety of cultural events on and off campus. Seminar instructors also serve as the primary academic advisors for first-year students in their respective sections. First-Year Seminars are writing emphasis and cannot fulfill any distributional, cultural perspective, or major requirements.

### Writing Emphasis (WE) Courses

Only designated WE courses in which a student earns a grade of “C” (2.0) or better count toward fulfillment of this requirement.

Only designated courses taken at Coe College count toward fulfillment of this requirement.

Undergraduate degree-seeking* students 

- who start at Coe College or who transfer fewer than 8 course credits earned after graduation from high school must complete at least 5 writing emphasis courses. Of these 5, one will usually be the FYS. Of the remaining 4, it is recommended (but not required) that at least 1 be taken outside the student’s intended major(s).
- who transfer at least 8 but fewer than 16 course credits to Coe, earned after graduation from high school, must complete at least 3 writing emphasis courses.
- who transfer 16 or more course credits to Coe, earned after graduation from high school, must complete at least 2 writing emphasis credits.

For all students, regardless of transfer credit, it is recommended (but not required) that at least one writing emphasis course be taken in the upper division within the student’s intended major(s). “Upper division” courses are defined in this case as those numbered 300 and above; upper division writing emphasis courses could include both scheduled classroom courses and arranged writing-based capstone projects (such as a thesis). See Departmental Writing Plans for more information on writing in the major(s).

*Students seeking a second undergraduate degree from Coe should see Second Baccalaureate Degree p. 26

*Writing Across the Curriculum: Statement of Guiding Principles*

As stated in the Coe College Mission Statement, our reason to exist as an institution is to ready students intellectually, professionally, and socially to lead productive and satisfying lives in the global society of the 21st century. In accordance with this mission, our curriculum requires that students undertake “a series of intensive writing experiences, spread across four years of study.” This requirement is known as Writing Across the Curriculum, the guiding principles of which are detailed below.

As a philosophy, Writing Across the Curriculum asserts that writing is most effectively learned in context: to varied audiences, with varied purposes. In adopting this philosophy, Coe College has committed to making writing-intensive experiences available to students in all disciplines. Known as “Writing Emphasis” credits, these courses are divergent in subject matter but aligned in their commitment to giving students content-rich and context-specific writing experiences that foster a critical flexibility in transferring knowledge about effective writing to multiple, even unknown, contexts.

Therefore, students who complete the requisite number of writing emphasis courses will graduate from Coe knowing that writing is both a means and an end: a method for exploring ideas and deepening one’s knowledge as well as a tool for sharing that knowledge and expressing one’s point of view. Similarly, graduating students will know that the practice of writing is a recursive process rooted in revision, which refers both to the reconsideration of one’s ideas and to the refinement of prose, and this process unfolds over a lifetime. Understanding that students will encounter innumerable writing situations in their lives, many of which may be unfamiliar to them, they will graduate from Coe having developed the confidence and self-efficacy necessary to adapt or draw from their existing knowledge in order to navigate new contexts.

Although many courses at Coe may include writing activities, courses endorsed by Writing Across the Curriculum are those in which:

- Students are given opportunities to practice revision, whether via multiple drafts of a single project or multiple iterations of the same type of assignment;
- Students receive instructor feedback on written work to facilitate revision; and
- Writing assignments are frequent enough that they are integral to the learning throughout the course, enabling students to develop in one or more of the following learning outcomes, as appropriate to discipline and course objectives:
  - How to write for specific purposes and audiences
    - *Including attention to the ways purposes and audiences shape form, mode, voice, method, organization, engagement with and citation of research, and/or creativity and imagination*
  - How to engage in critical thinking
    - *Particularly how to conduct analysis, how to synthesize information, how to interpret and/or use evidence and data, and how to present one’s ideas coherently and stylistically*
  - How to practice, assess, and develop effective habits for writing
    - *Specifically, how to read deeply, how to begin and later practice selection in research, how to be a skilled reader of one’s own and others’ in-process writing, how to accept and interpret feedback, and how to revise writing, all of which are parts of the process of learning how to have and develop ideas*
  - How to engage in writing as a method for learning and discovery
    - *For deepening knowledge, thinking through questions and problems, and reflecting on connections and growth*
  - How to name and describe one’s own knowledge for others
    - *For example, in the form of personal statements for application to graduate study, cover letters and resumes for entering and advancing in the workforce, or other forms of self-summary that facilitate transition from the baccalaureate environment through the broader public.*

Many writing emphasis sections are offered each year. First-Year Seminars (all of which are Writing emphasis), Divisional requirements, Diversity across the Curriculum, or major courses that are also designated as writing emphasis courses may be used to satisfy both requirements.

In this catalog, writing emphasis courses are designated by a (WE) after the course title, e.g. “COM-141 Introduction to Journalism (WE).” In other contexts, the course code may end with a “W” or “WE” (e.g. COM-141-W or COM-141-WE). All sections of such a course, regardless of instructor, will carry writing emphasis credit.

#### Writing Emphasis Course Listing

|   |   |
|---|---|
| {{< var c.aam137.long >}} | {{< var c.aam367.long >}} |
| {{< var c.aam367.long >}} | {{< var c.acc313.long >}} |
| {{< var c.acc313.long >}} | {{< var c.acc413.long >}} |
| {{< var c.acc413.long >}} | {{< var c.arh307.long >}} |
| {{< var c.arh307.long >}} | {{< var c.art464.long >}} |
| {{< var c.art464.long >}} | {{< var c.asc216.long >}} |
| {{< var c.asc216.long >}} | {{< var c.avs401.long >}} |
| {{< var c.avs401.long >}} | {{< var c.avs403.long >}} |
| {{< var c.avs403.long >}} | {{< var c.bio145l.long >}} |
| {{< var c.bio145l.long >}} | {{< var c.bio155l.long >}} |
| {{< var c.bio155l.long >}} | {{< var c.bio205l.long >}} |
| {{< var c.bio205l.long >}} | {{< var c.bio235l.long >}} |
| {{< var c.bio235l.long >}} | {{< var c.bio295l.long >}} |
| {{< var c.bio295l.long >}} | {{< var c.bio325.long >}} |
| {{< var c.bio325.long >}} | {{< var c.bio415l.long >}} |
| {{< var c.bio415l.long >}} | {{< var c.bio425l.long >}} |
| {{< var c.bio425l.long >}} | {{< var c.bus190.long >}} |
| {{< var c.bus190.long >}} | {{< var c.bus330.long >}} |
| {{< var c.bus330.long >}} | {{< var c.bus375.long >}} |
| {{< var c.bus375.long >}} | {{< var c.bus387.long >}} |
| {{< var c.bus387.long >}} | {{< var c.bus460.long >}} |
| {{< var c.bus460.long >}} | {{< var c.bus461.long >}} |
| {{< var c.bus461.long >}} | {{< var c.bus464.long >}} |
| {{< var c.bus464.long >}} | {{< var c.bus470.long >}} |
| {{< var c.bus470.long >}} | {{< var c.chm211l.long >}} |
| {{< var c.chm211l.long >}} | {{< var c.chm341.long >}} |
| {{< var c.chm341.long >}} | {{< var c.chm422.long >}} |
| {{< var c.chm422.long >}} | {{< var c.chm451l.long >}} |
| {{< var c.chm451l.long >}} | {{< var c.com137.long >}} |
| {{< var c.com137.long >}} | {{< var c.com141.long >}} |
| {{< var c.com141.long >}} | {{< var c.com151.long >}} |
| {{< var c.com151.long >}} | {{< var c.com157.long >}} |
| {{< var c.com157.long >}} | {{< var c.com231.long >}} |
| {{< var c.com231.long >}} | {{< var c.com236.long >}} |
| {{< var c.com236.long >}} | {{< var c.com241.long >}} |
| {{< var c.com241.long >}} | {{< var c.com257.long >}} |
| {{< var c.com257.long >}} | {{< var c.com267.long >}} |
| {{< var c.com267.long >}} | {{< var c.com281.long >}} |
| {{< var c.com281.long >}} | {{< var c.com322.long >}} |
| {{< var c.com322.long >}} | {{< var c.com323.long >}} |
| {{< var c.com323.long >}} | {{< var c.com327.long >}} |
| {{< var c.com327.long >}} | {{< var c.com332.long >}} |
| {{< var c.com332.long >}} | {{< var c.com341.long >}} |
| {{< var c.com341.long >}} | {{< var c.com377.long >}} |
| {{< var c.com377.long >}} | {{< var c.com381.long >}} |
| {{< var c.com381.long >}} | {{< var c.com394.long >}} |
| {{< var c.com394.long >}} | {{< var c.com435.long >}} |
| {{< var c.com435.long >}} | {{< var c.com437.long >}} |
| {{< var c.com437.long >}} | {{< var c.com444.long >}} |
| {{< var c.com444.long >}} | {{< var c.com455.long >}} |
| {{< var c.com455.long >}} | {{< var c.com457.long >}} |
| {{< var c.com457.long >}} | {{< var c.com465.long >}} |
| {{< var c.com465.long >}} | {{< var c.com467.long >}} |
| {{< var c.com467.long >}} | {{< var c.crw105.long >}} |
| {{< var c.crw105.long >}} | {{< var c.crw106.long >}} |
| {{< var c.crw106.long >}} | {{< var c.crw107.long >}} |
| {{< var c.crw107.long >}} | {{< var c.crw125.long >}} |
| {{< var c.crw125.long >}} | {{< var c.crw135.long >}} |
| {{< var c.crw135.long >}} | {{< var c.crw225.long >}} |
| {{< var c.crw225.long >}} | {{< var c.crw255.long >}} |
| {{< var c.crw255.long >}} | {{< var c.crw280.long >}} |
| {{< var c.crw280.long >}} | {{< var c.crw290.long >}} |
| {{< var c.crw290.long >}} | {{< var c.crw325.long >}} |
| {{< var c.crw325.long >}} | {{< var c.crw345.long >}} |
| {{< var c.crw345.long >}} | {{< var c.crw350.long >}} |
| {{< var c.crw350.long >}} | {{< var c.crw355.long >}} |
| {{< var c.crw355.long >}} | {{< var c.crw380.long >}} |
| {{< var c.crw380.long >}} | {{< var c.crw390.long >}} |
| {{< var c.crw390.long >}} | {{< var c.crw394.long >}} |
| {{< var c.crw394.long >}} | {{< var c.crw455.long >}} |
| {{< var c.crw455.long >}} | {{< var c.crw480.long >}} |
| {{< var c.crw480.long >}} | {{< var c.crw484.long >}} |
| {{< var c.crw484.long >}} | {{< var c.crw490.long >}} |
| {{< var c.crw490.long >}} | {{< var c.crw492.long >}} |
| {{< var c.crw492.long >}} | {{< var c.cs480.long >}} |
| {{< var c.cs480.long >}} | {{< var c.cs280.long >}} |
| {{< var c.cs280.long >}} | {{< var c.ecc112.long >}} |
| {{< var c.ecc112.long >}} | {{< var c.ecc312.long >}} |
| {{< var c.ecc312.long >}} | {{< var c.ecc345.long >}} |
| {{< var c.ecc345.long >}} | {{< var c.eco375.long >}} |
| {{< var c.eco375.long >}} | {{< var c.eco395.long >}} |
| {{< var c.eco395.long >}} | {{< var c.eco424.long >}} |
| {{< var c.eco424.long >}} | {{< var c.eco445.long >}} |
| {{< var c.eco445.long >}} | {{< var c.edu105.long >}} |
| {{< var c.edu105.long >}} | {{< var c.edu187.long >}} |
| {{< var c.edu187.long >}} | {{< var c.edu215.long >}} |
| {{< var c.edu215.long >}} | {{< var c.edu220.long >}} |
| {{< var c.edu220.long >}} | {{< var c.edu237.long >}} |
| {{< var c.edu237.long >}} | {{< var c.edu260.long >}} |
| {{< var c.edu260.long >}} | {{< var c.edu270.long >}} |
| {{< var c.edu270.long >}} | {{< var c.edu305.long >}} |
| {{< var c.edu305.long >}} | {{< var c.edu310.long >}} |
| {{< var c.edu310.long >}} | {{< var c.edu311.long >}} |
| {{< var c.edu311.long >}} | {{< var c.edu312.long >}} |
| {{< var c.edu312.long >}} | {{< var c.edu313.long >}} |
| {{< var c.edu313.long >}} | {{< var c.edu320.long >}} |
| {{< var c.edu320.long >}} | {{< var c.edu321.long >}} |
| {{< var c.edu321.long >}} | {{< var c.edu335.long >}} |
| {{< var c.edu335.long >}} | {{< var c.edu345.long >}} |
| {{< var c.edu345.long >}} | {{< var c.edu355.long >}} |
| {{< var c.edu355.long >}} | {{< var c.edu365.long >}} |
| {{< var c.edu365.long >}} | {{< var c.edu395.long >}} |
| {{< var c.edu395.long >}} | {{< var c.edu481.long >}} |
| {{< var c.edu481.long >}} | {{< var c.edu482.long >}} |
| {{< var c.edu482.long >}} | {{< var c.edu483.long >}} |
| {{< var c.edu483.long >}} | {{< var c.edu485.long >}} |
| {{< var c.edu485.long >}} | {{< var c.edu489.long >}} |
| {{< var c.edu489.long >}} | {{< var c.edu490.long >}} |
| {{< var c.edu490.long >}} | {{< var c.edu491.long >}} |
| {{< var c.edu491.long >}} | {{< var c.edu492.long >}} |
| {{< var c.edu492.long >}} | {{< var c.eng111.long >}} |
| {{< var c.eng111.long >}} | {{< var c.eng117.long >}} |
| {{< var c.eng117.long >}} | {{< var c.eng127.long >}} |
| {{< var c.eng127.long >}} | {{< var c.eng137.long >}} |
| {{< var c.eng137.long >}} | {{< var c.eng146.long >}} |
| {{< var c.eng146.long >}} | {{< var c.eng157.long >}} |
| {{< var c.eng157.long >}} | {{< var c.eng206.long >}} |
| {{< var c.eng206.long >}} | {{< var c.eng207.long >}} |
| {{< var c.eng207.long >}} | {{< var c.eng208.long >}} |
| {{< var c.eng208.long >}} | {{< var c.eng281.long >}} |
| {{< var c.eng281.long >}} | {{< var c.eng291.long >}} |
| {{< var c.eng291.long >}} | {{< var c.eng301.long >}} |
| {{< var c.eng301.long >}} | {{< var c.eng312.long >}} |
| {{< var c.eng312.long >}} | {{< var c.eng327.long >}} |
| {{< var c.eng327.long >}} | {{< var c.eng328.long >}} |
| {{< var c.eng328.long >}} | {{< var c.eng337.long >}} |
| {{< var c.eng337.long >}} | {{< var c.eng347.long >}} |
| {{< var c.eng347.long >}} | {{< var c.eng357.long >}} |
| {{< var c.eng357.long >}} | {{< var c.eng367.long >}} |
| {{< var c.eng367.long >}} | {{< var c.eng375.long >}} |
| {{< var c.eng375.long >}} | {{< var c.eng378.long >}} |
| {{< var c.eng378.long >}} | {{< var c.eng380.long >}} |
| {{< var c.eng380.long >}} | {{< var c.eng382.long >}} |
| {{< var c.eng382.long >}} | {{< var c.eng383.long >}} |
| {{< var c.eng383.long >}} | {{< var c.eng384.long >}} |
| {{< var c.eng384.long >}} | {{< var c.eng385.long >}} |
| {{< var c.eng385.long >}} | {{< var c.eng388.long >}} |
| {{< var c.eng388.long >}} | {{< var c.eng390.long >}} |
| {{< var c.eng390.long >}} | {{< var c.eng392.long >}} |
| {{< var c.eng392.long >}} | {{< var c.eng393.long >}} |
| {{< var c.eng393.long >}} | {{< var c.eng394.long >}} |
| {{< var c.eng394.long >}} | {{< var c.eng454.long >}} |
| {{< var c.eng454.long >}} | {{< var c.eng464.long >}} |
| {{< var c.eng464.long >}} | {{< var c.eng467.long >}} |
| {{< var c.eng467.long >}} | {{< var c.gs107.long >}} |
| {{< var c.gs107.long >}} | {{< var c.gs327.long >}} |
| {{< var c.gs327.long >}} | {{< var c.gs387.long >}} |
| {{< var c.gs387.long >}} | {{< var c.his205.long >}} |
| {{< var c.his205.long >}} | {{< var c.his208.long >}} |
| {{< var c.his208.long >}} | {{< var c.his216.long >}} |
| {{< var c.his216.long >}} | {{< var c.his217.long >}} |
| {{< var c.his217.long >}} | {{< var c.his218.long >}} |
| {{< var c.his218.long >}} | {{< var c.his227.long >}} |
| {{< var c.his227.long >}} | {{< var c.his238.long >}} |
| {{< var c.his238.long >}} | {{< var c.his246.long >}} |
| {{< var c.his246.long >}} | {{< var c.his248.long >}} |
| {{< var c.his248.long >}} | {{< var c.his256.long >}} |
| {{< var c.his256.long >}} | {{< var c.his257.long >}} |
| {{< var c.his257.long >}} | {{< var c.his268.long >}} |
| {{< var c.his268.long >}} | {{< var c.his272.long >}} |
| {{< var c.his272.long >}} | {{< var c.his275.long >}} |
| {{< var c.his275.long >}} | {{< var c.his276.long >}} |
| {{< var c.his276.long >}} | {{< var c.his278.long >}} |
| {{< var c.his278.long >}} | {{< var c.his285.long >}} |
| {{< var c.his285.long >}} | {{< var c.his286.long >}} |
| {{< var c.his286.long >}} | {{< var c.his288.long >}} |
| {{< var c.his288.long >}} | {{< var c.his292.long >}} |
| {{< var c.his292.long >}} | {{< var c.his297.long >}} |
| {{< var c.his297.long >}} | {{< var c.his300.long >}} |
| {{< var c.his300.long >}} | {{< var c.his306.long >}} |
| {{< var c.his306.long >}} | {{< var c.his308.long >}} |
| {{< var c.his308.long >}} | {{< var c.his316.long >}} |
| {{< var c.his316.long >}} | {{< var c.his317.long >}} |
| {{< var c.his317.long >}} | {{< var c.his318.long >}} |
| {{< var c.his318.long >}} | {{< var c.his325.long >}} |
| {{< var c.his325.long >}} | {{< var c.his328.long >}} |
| {{< var c.his328.long >}} | {{< var c.his335.long >}} |
| {{< var c.his335.long >}} | {{< var c.his347.long >}} |
| {{< var c.his347.long >}} | {{< var c.his355.long >}} |
| {{< var c.his355.long >}} | {{< var c.his365.long >}} |
| {{< var c.his365.long >}} | {{< var c.his372.long >}} |
| {{< var c.his372.long >}} | {{< var c.his387.long >}} |
| {{< var c.his387.long >}} | {{< var c.his395.long >}} |
| {{< var c.his395.long >}} | {{< var c.his444.long >}} |
| {{< var c.his444.long >}} | {{< var c.his465.long >}} |
| {{< var c.his465.long >}} | {{< var c.his466.long >}} |
| {{< var c.his466.long >}} | {{< var c.his472.long >}} |
| {{< var c.his472.long >}} | {{< var c.his473.long >}} |
| {{< var c.his473.long >}} | {{< var c.his474.long >}} |
| {{< var c.his474.long >}} | {{< var c.kin347.long >}} |
| {{< var c.kin347.long >}} | {{< var c.kin440.long >}} |
| {{< var c.kin440.long >}} | {{< var c.mth215.long >}} |
| {{< var c.mth215.long >}} | {{< var c.mth305.long >}} |
| {{< var c.mth305.long >}} | {{< var c.mth325.long >}} |
| {{< var c.mth325.long >}} | {{< var c.mth445.long >}} |
| {{< var c.mth445.long >}} | {{< var c.mth455.long >}} |
| {{< var c.mth455.long >}} | {{< var c.mth484.long >}} |
| {{< var c.mth484.long >}} | {{< var c.mu107.long >}} |
| {{< var c.mu107.long >}} | {{< var c.mu384.long >}} |
| {{< var c.mu384.long >}} | {{< var c.mu385.long >}} |
| {{< var c.mu385.long >}} | {{< var c.nur305.long >}} |
| {{< var c.nur305.long >}} | {{< var c.nur375.long >}} |
| {{< var c.nur375.long >}} | {{< var c.nur425.long >}} |
| {{< var c.nur425.long >}} | {{< var c.nur455.long >}} |
| {{< var c.nur455.long >}} | {{< var c.phl105.long >}} |
| {{< var c.phl105.long >}} | {{< var c.phl128.long >}} |
| {{< var c.phl128.long >}} | {{< var c.phl200.long >}} |
| {{< var c.phl200.long >}} | {{< var c.phl205.long >}} |
| {{< var c.phl205.long >}} | {{< var c.phl210.long >}} |
| {{< var c.phl210.long >}} | {{< var c.phl220.long >}} |
| {{< var c.phl220.long >}} | {{< var c.phl265.long >}} |
| {{< var c.phl265.long >}} | {{< var c.phl285.long >}} |
| {{< var c.phl285.long >}} | {{< var c.phl300.long >}} |
| {{< var c.phl300.long >}} | {{< var c.phl315.long >}} |
| {{< var c.phl315.long >}} | {{< var c.phl320.long >}} |
| {{< var c.phl320.long >}} | {{< var c.phl355.long >}} |
| {{< var c.phl355.long >}} | {{< var c.phl394.long >}} |
| {{< var c.phl394.long >}} | {{< var c.phl444.long >}} |
| {{< var c.phl444.long >}} | {{< var c.phl490.long >}} |
| {{< var c.phl490.long >}} | {{< var c.phl494.long >}} |
| {{< var c.phl494.long >}} | {{< var c.phy105.long >}} |
| {{< var c.phy105.long >}} | {{< var c.phy236.long >}} |
| {{< var c.phy236.long >}} | {{< var c.phy246.long >}} |
| {{< var c.phy246.long >}} | {{< var c.phy311.long >}} |
| {{< var c.phy311.long >}} | {{< var c.phy444.long >}} |
| {{< var c.phy444.long >}} | {{< var c.phy454.long >}} |
| {{< var c.phy454.long >}} | {{< var c.pol210.long >}} |
| {{< var c.pol210.long >}} | {{< var c.pol258.long >}} |
| {{< var c.pol258.long >}} | {{< var c.pol266.long >}} |
| {{< var c.pol266.long >}} | {{< var c.pol276.long >}} |
| {{< var c.pol276.long >}} | {{< var c.pol277.long >}} |
| {{< var c.pol277.long >}} | {{< var c.pol286.long >}} |
| {{< var c.pol286.long >}} | {{< var c.pol298.long >}} |
| {{< var c.pol298.long >}} | {{< var c.pol305.long >}} |
| {{< var c.pol305.long >}} | {{< var c.pol310.long >}} |
| {{< var c.pol310.long >}} | {{< var c.pol325.long >}} |
| {{< var c.pol325.long >}} | {{< var c.pol345.long >}} |
| {{< var c.pol345.long >}} | {{< var c.pol350.long >}} |
| {{< var c.pol350.long >}} | {{< var c.pol365.long >}} |
| {{< var c.pol365.long >}} | {{< var c.pol405.long >}} |
| {{< var c.pol405.long >}} | {{< var c.pol435.long >}} |
| {{< var c.pol435.long >}} | {{< var c.pol445.long >}} |
| {{< var c.pol445.long >}} | {{< var c.pr205.long >}} |
| {{< var c.pr205.long >}} | {{< var c.psy200.long >}} |
| {{< var c.psy200.long >}} | {{< var c.psy295.long >}} |
| {{< var c.psy295.long >}} | {{< var c.psy325l.long >}} |
| {{< var c.psy325l.long >}} | {{< var c.psy335l.long >}} |
| {{< var c.psy335l.long >}} | {{< var c.psy355l.long >}} |
| {{< var c.psy355l.long >}} | {{< var c.psy464.long >}} |
| {{< var c.psy464.long >}} | {{< var c.rel101.long >}} |
| {{< var c.rel101.long >}} | {{< var c.rel103.long >}} |
| {{< var c.rel103.long >}} | {{< var c.rel105.long >}} |
| {{< var c.rel105.long >}} | {{< var c.rel108.long >}} |
| {{< var c.rel108.long >}} | {{< var c.rel115.long >}} |
| {{< var c.rel115.long >}} | {{< var c.rel128.long >}} |
| {{< var c.rel128.long >}} | {{< var c.rel136.long >}} |
| {{< var c.rel136.long >}} | {{< var c.rel138.long >}} |
| {{< var c.rel138.long >}} | {{< var c.rel148.long >}} |
| {{< var c.rel148.long >}} | {{< var c.rel206.long >}} |
| {{< var c.rel206.long >}} | {{< var c.rel215.long >}} |
| {{< var c.rel215.long >}} | {{< var c.rel217.long >}} |
| {{< var c.rel217.long >}} | {{< var c.rel226.long >}} |
| {{< var c.rel226.long >}} | {{< var c.rel236.long >}} |
| {{< var c.rel236.long >}} | {{< var c.rel310.long >}} |
| {{< var c.rel310.long >}} | {{< var c.rel328.long >}} |
| {{< var c.rel328.long >}} | {{< var c.rel330.long >}} |
| {{< var c.rel330.long >}} | {{< var c.rel336.long >}} |
| {{< var c.rel336.long >}} | {{< var c.rel338.long >}} |
| {{< var c.rel338.long >}} | {{< var c.rel365.long >}} |
| {{< var c.rel365.long >}} | {{< var c.rel385.long >}} |
| {{< var c.rel385.long >}} | {{< var c.rel394.long >}} |
| {{< var c.rel394.long >}} | {{< var c.rel396.long >}} |
| {{< var c.rel396.long >}} | {{< var c.rel444.long >}} |
| {{< var c.rel444.long >}} | {{< var c.rel494.long >}} |
| {{< var c.rel494.long >}} | {{< var c.soc235.long >}} |
| {{< var c.soc235.long >}} | {{< var c.soc450.long >}} |
| {{< var c.soc450.long >}} | {{< var c.soc464.long >}} |
| {{< var c.soc464.long >}} | {{< var c.spa315.long >}} |
| {{< var c.spa315.long >}} | {{< var c.spa325.long >}} |
| {{< var c.spa325.long >}} | {{< var c.spa330.long >}} |
| {{< var c.spa330.long >}} | {{< var c.spa345.long >}} |
| {{< var c.spa345.long >}} | {{< var c.spa394.long >}} |
| {{< var c.spa394.long >}} | {{< var c.spa412.long >}} |
| {{< var c.spa412.long >}} | {{< var c.spa418.long >}} |
| {{< var c.spa418.long >}} | {{< var c.spa421.long >}} |
| {{< var c.spa421.long >}} | {{< var c.spa428.long >}} |
| {{< var c.spa428.long >}} | {{< var c.spa431.long >}} |
| {{< var c.spa431.long >}} | {{< var c.spa432.long >}} |
| {{< var c.spa432.long >}} | {{< var c.spa442.long >}} |
| {{< var c.spa442.long >}} | {{< var c.spa443.long >}} |
| {{< var c.spa443.long >}} | {{< var c.spa444.long >}} |
| {{< var c.spa444.long >}} | {{< var c.spa446.long >}} |
| {{< var c.spa446.long >}} | {{< var c.spa451.long >}} |
| {{< var c.spa451.long >}} | {{< var c.spa455.long >}} |
| {{< var c.spa455.long >}} | {{< var c.spa457.long >}} |
| {{< var c.spa457.long >}} | {{< var c.spa458.long >}} |
| {{< var c.spa458.long >}} | {{< var c.spa475.long >}} |
| {{< var c.spa475.long >}} | {{< var c.spa476.long >}} |
| {{< var c.spa476.long >}} | {{< var c.spa485.long >}} |
| {{< var c.spa485.long >}} | {{< var c.spa486.long >}} |
| {{< var c.spa486.long >}} | {{< var c.the228.long >}} |
| {{< var c.the228.long >}} | {{< var c.the238.long >}} |
| {{< var c.the238.long >}} | {{< var c.the255.long >}} |
| {{< var c.the255.long >}} | {{< var c.the288.long >}} |
| {{< var c.the288.long >}} | {{< var c.the290.long >}} |
| {{< var c.the290.long >}} | {{< var c.the355.long >}} |
| {{< var c.the355.long >}} | {{< var c.the390.long >}} |
| {{< var c.the390.long >}} | {{< var c.the455.long >}} |
| {{< var c.the455.long >}} | {{< var c.the464.long >}} |
| {{< var c.the464.long >}} | {{< var c.the494.long >}} |
| {{< var c.the494.long >}} | {{< var c.wlc108.long >}} |
| {{< var c.wlc108.long >}} |  |

### Diversity Across the Curriculum

Students are required to complete at least TWO courses from the Diversity Across the Curriculum course list, where a term-long study away may count as the two required courses as approved by the Registrar.
An essential part of a liberal arts education is to prepare students to live and work in a diverse and interconnected world. Diversity Across the Curriculum courses, offered at all levels across the curriculum, are designed to equip students to engage in effective and respectful civil dialogue in global and local contexts.

#### Diversity Across the Curriculum: Course Listing

|      |      |
| :--- | :--- |
| AAM-107 Intro to African American Studies | AAM-197 Tupac Shakur and the Hip Hop Revolution |
| AAM-217 Sport and Black Culture | AAM-227 Blackness and Identity in America |
| AAM-367 Studies in African American Literature (WE) | ANT-116 Cultural Anthropology |
| ANT-125 Art and Archaeology of the Classical World | ANT-208 Archaeological Field School |
| ARH-106 World Art | ARH-107 Gender and Art |
| ARH-128 Introduction to Art History | ARH-218 The World of Renaissance Art |
| ARH-248 Baroque, Rococo, and Neoclassicism | ARH-268 History of Architecture |
| ARH-296 Topics in Art History: Global Perspectives | ARH-297 Topics in Art History: U.S. Pluralism |
| ASC-106 May Experiential Term in Asia | ASC-176 China and Japan |
| ASC-186 Modern South Asia | ASC-196 Modern Southeast Asia |
| BUS-375 Business Ethics (WE) | BUS-446 International Business Management |
| COM-137 Interpersonal Communication (WE) | COM-157 Intro to Media Analysis (WE) |
| COM-161 Visual Rhetoric | COM-227 Topics in Communication Studies |
| COM-236 Intercultural Communication (WE) | COM-247 Topics in Communication Studies |
| COM-257 Sex, Race, and Gender in the Media (WE) | COM-267 Environmental Rhetoric (WE) |
| COM-277 Topics in Communication Studies | COM-327 Organizational Comm (WE) |
| COM-347 Persuasion | COM-377 Language, Power, and Social Change (WE) |
| COM-437 Advanced Topics in Human Communication (WE) | COM-457 Advanced Topics in Mass Media (WE) |
| COM-467 Advanced Topics in Cultural and Critical Communication (WE) | CRW-106 Exploring Creative Writing: Non-Western Perspectives (WE) |
| ECO-237 Labor Economics | ECO-247 Health Economics |
| ECO-336 Divergent Economic Growth | ECO-436 Economic Development |
| ECO-446 International Economics | EDU-105 Foundations of Education (WE) |
| EDU-117 Exceptional Learners | EDU-187 Human Relations (WE) |
| EDU-217 Principles of Effective Instruction | EDU-237 English Language Learners (WE) |
| ENG-107 Exploring Literature: United States. Pluralism | ENG-108 Exploring Literature: Diverse Western Perspectives |
| ENG-117 Asian American Literature (WE) | ENG-127 Social Justice & Literature (WE) |
| ENG-137 African American Literature (WE) | ENG-146 Postcolonial Literature (WE) |
| ENG-157 Latinx/Chicanx Literature (WE) | ENG-206 Gender and Literature: Non-Western Perspectives (WE) |
| ENG-207 Gender and Literature: United States Pluralism (WE) | ENG-208 Gender and Literature (WE) |
| ENG-327 Literature of the American Renaissance (WE) | ENG-328 Dante’s Divine Comedy (WE) (cross-listed with REL-328) |
| ENG-337 American Realism and Naturalism (WE) | ENG-347 Studies in Modern or Contemporary American Literature (WE) |
| ENG-357 Studies in Latinx/Chicanx Literature (WE) | ENG-367 Studies in African American Literature (WE) |
| ENG-378 Studies in Transatlantic Literature (WE) | ENG-388 Romantic Literature (WE) |
| ENG-467 Seminar in Literature: United States Pluralism (WE) | GS-107 Introduction to Gender and Sexuality Studies (WE) |
| GS-247 Gender and Sexuality Studies Symposium | GS-327 Theory and Methods in Gender and Sexuality Studies (WE) |
| HIS-136 East Asian Civilization | HIS-208 World War I (WE) |
| HIS-216 The History of Modern Korea (WE) | HIS-217 The American War in Vietnam (WE) |
| HIS-218 World War II (WE) | HIS-227 The American Civil War (WE) |
| HIS-238 Modern France (WE) | HIS-246 The History of Modern China (WE) |
| HIS-248 French Revolution (WE) | HIS-256 The History of Modern Japan (WE) |
| HIS-257 Native American History (WE) | HIS-268 Latin America (WE) |
| HIS-276 The “Discovery” of America: Clash of Cultures and Alterities (WE) | HIS-278 History of the Holocaust (WE) |
| HIS-286 Modern Middle East (WE) | HIS-288 Renaissance and Reformation (WE) |
| HIS-297 Women in America (WE) | HIS-306 Revolution, Social Struggle, and Testimonio in Latin America 20th Century (WE) |
| HIS-308 Legacies of the Cold War in Argentina, Peru, Colombia, and Chile (WE) | HIS-316 Topics in History: Non-Western Perspectives (WE) |
| HIS-317 Topics in History: United States Pluralism (WE) | HIS-318 Topics in History: Diverse Western Perspectives (WE) |
| HIS-328 Sport and Spectacle in Ancient Greece and Rome (WE) | HIS-347 African American History (WE) |
| HIS-387 American Colonial History (WE) | HIS-466 Seminar in Asian History (WE) |
| IS-116 Intro to International Studies | IS-126 Human Rights Work with Burmese Migrants in Thailand |
| IS-199 May Experiential Term in the Francophone World | IS-316 Topics in International Studies: Non-Western Perspectives |
| JPN-115 Elementary Japanese I | JPN-125 Elementary Japanese II |
| KIN-347 Adapted Physical Education (WE) | MU-107 American Music (WE) |
| MU-108 Queerness in Music: A History | MU-117 Jazz: The Early Years |
| MU-157 Introduction to Jazz History | MU-166 Music of the World |
| NUR-315 Pathophysiology and Assessment | NUR-430 Community and Population Oriented Nursing |
| PHL-105 Introduction to Philosophy (WE) | PHL-128 Morality and Moral Controversies (WE) |
| PHL-200 Biomedical Ethics (WE) | PHL-265 Political Philosophy (WE) |
| PHL-285 Law, Morality, and Punishment (WE) | POL-107 Environmental Justice |
| POL-108 Introduction to Politics | POL-115 American National Government and Politics |
| POL-258 World Politics (WE) | POL-266 Latin American Politics (WE) |
| POL-276 African Politics (WE) | POL-277 Women and Politics in the United States (WE) |
| POL-286 Asian Politics (WE) | POL-296 Topics in Political Science - Non-Western Perspectives |
| POL-298 European Politics (WE) | POL-350 US Social Policy Process (WE) |
| PSY-205 Developmental Psychology | PSY-215 Multicultural Psychology |
| PSY-235 Abnormal Psychology | PSY-245 Organizational Psychology |
| PSY-255 Social Psychology | REL-101 Introduction to Religion (WE) |
| REL-106 Eastern Religions | REL-108 Western Religions (WE) |
| REL-116 Buddhism | REL-128 Judaism (WE) |
| REL-136 Religions of China (WE) | REL-138 Modern Judaism (WE) |
| REL-148 Islam (WE) | REL-178 Christianity |
| REL-196 Hinduism | REL-207 Apocalypse and Apocalyptic Literature |
| REL-217 Religion in America (WE) | REL-226 Religions of China: Daoism (WE) |
| REL-236 Zen Buddhism (WE) | REL-246 Caste and Untouchability in South Asia |
| REL-296 Topics in Religion: Non-Western Perspectives | REL-328 Dante’s Divine Comedy (WE) (cross-listed with ENG-328) |
| REL-336 Tibetan Buddhist Culture (WE) | SCJ-207 Restorative Justice |
| SOC-107 Introduction to Sociology | SOC-207 Sociology of the Family |
| SOC-217 Sociology of Religion | SOC-227 Sociology of Sexuality |
| SOC-236 Topics in Sociology: Non-Western Perspectives | SOC-237 Topics in Sociology: United States Pluralism |
| SOC-238 Topics in Sociology: Diverse Western Perspectives | SOC-247 Sociology of Race |
| SOC-257 Sociology of Health & Medicine | SOC-286 Global and Transnational Sociology |
| SPA-115 Elementary Spanish I | SPA-125 Elementary Spanish II |
| SPA-129 Intensive Elementary Spanish I–II | SPA-135 Spanish Review and Preparation |
| SPA-148 Spanish Literature in Translation | SPA-215 Intermediate Spanish I |
| SPA-225 Intermediate Spanish II | SPA-258 Spanish Language Learning Abroad |
| SPA-315 Spanish Composition and Conversation (WE) | SPA-325 Spanish Language and Literature (WE) |
| SPA-330 Spanish for Heritage Speakers (WE) | SPA-336 Hispanic Life and Culture: Latin America |
| SPA-338 Hispanic Life and Culture: Europe | SPA-339 Spanish for Health Care |
| SPA-345 Introduction to Hispanic Literature (WE) | SPA-349 Business Spanish |
| SPA-412 Ecologies: Latin American Environmental Literature and Cultural Works (WE) | SPA-418 Gender and Sexuality in the Hispanic World (WE) |
| SPA-421 Nation, History, and Literature (WE) | SPA-428 Indigeneity, Blackness, and Ethnic Literatures in the Hispanic World (WE) |
| SPA-431 Hispanic Graphic Novel: Theory and Practice (WE) | SPA-432 Representations of Violence in Hispanic Cultural Productions (WE) |
| SPA-442 Popular Culture, Media, and Cultural Studies (WE) | SPA-443 Cinema and the Politics of Representation (WE) |
| SPA-444 Independent Study (WE) | SPA-446 Latin American and Spanish Short Stories |
| SPA-451 Hispanic Cross-Over Literature: Theory and Practice (WE) | SPA-455 Hispanic Drama and Performance: Theory and Practice (WE) |
| SPA-457 US Latinx Literature (WE) | SPA-458 Travel Writing & Transatlantic Literature |
| SPA-475/-485 Topics in Hispanic Literature (WE) | SPA-476/-486 Topics in Hispanic Society and Culture (WE) |
| THE-161 Afro-Latin Dance | THE-228 History of Theatre and Drama I (WE) |
| THE-238 History of Theatre and Drama II (WE) | THE-288 History of Dress (WE) |
| WLC-108 Cultural Studies and Literature in Translation (WE) | WSH-286 Topics in Washington DC: Non-Western Perspectives |

### PRACTICUM

All Students, except those earning a second degree, must complete at least ONE practicum experience. A practicum experience that integrates academic learning with significant educational experiences beyond the classroom is typically completed in the student’s junior or senior year. A practicum experience can consist of an internship, off-campus study, community-based project, honors project, or some other kind of independent activity. Depending on the type selected, some practica are graded A–F, while others are P/NP. Some practica are credit bearing, while others are not. 

The following list includes acceptable practicum experiences:

1.	Full-Term Off-Campus Study 
2.	May Experiential Term Courses
3.	Wilderness Field Station or Archaeological Field School Summer Courses 
4.	Departmental Honors Project, if transcripted with an appropriate course code
5.	Independent Study
6.	Student Teaching 
7.	Internships (All course codes ending in 494 and 499)
8.	Research (All course codes ending in 454 and 459)
9.	Community-Based Project
  - Supervised work on service projects proposed by external constituencies such as non-profit institutions, community agencies, and government organizations. Students learn about the issues, problems, and techniques associated with developing, organizing, and participating in projects that address and solve real-world problems, as well as provide services and benefits to community and project sponsors.  Authorization for the community-based project is determined by the supervising faculty member. May be taken more than once. A minimum of 140 hours of work is required. P/NP basis only. A maximum of two course credits earned through any combination of Internships and Community-Based Projects may be included in the 32 course credits required for graduation.
10.	Additional practicum courses:
  - ART-474 Seminar in Art and Visual Studies II & Thesis Exhibition
  - BIO-115 Marine Biology
  - BIO-462 Advanced Biology Laboratory I
  - CFP-401 Action Research I plus CFP-402 Action Research II
  - CRW-112 Advanced Literary Magazine Editing (two terms)
  - CRW-492 Manuscript Workshop (WE)
  - ECO-454 Research in Economics
  - EDU-215 Practicum in Education (WE
  - MUA-490 Senior Recital
  - NUR-455 Leadership and Contemporary Issues in Nursing/Clinical Application (WE)
  - PHL-490 Philosophy Colloquium (WE) (0.0 credit)
  - PHY-255 Introduction to Physics Research I
  - PHY-355 Introduction to Physics Research II
  - THE-442 Advanced Projects in Design and Technical Production
  - THE-452 Advanced Projects in Acting
  - THE-462 Advanced Projects in Directing 

## AREAS OF STUDY

The four undergraduate degrees have areas of study associated with them.  The Bachelor of Science in Nursing’s area of study is nursing; the Bachelor of Science in Engineering’s area of study is engineering physics.  The Bachelor of Arts’ areas of study (residential or online), commonly referred to as majors, are listed below. The Bachelor of Arts degree has two options for completion—the traditional program and the reduced-credit program (online only), with each requiring an area of study, commonly referred to as a major. A student earning an RC-B.A. must complete an area of study approved for this particular degree. A student earning a traditional B.A. must complete at least one area of study approved for the traditional degree, but may also complete an area of study approved for a RC-B.A., earning the traditional B.A.  Students may matriculate from a residential to online program or vice versa but cannot be simultaneously in both degree programs.

All students are required to complete at least one area of study associated with their degree. Students should declare a major by the end of their sophomore year.  All students must earn at least a 2.00 GPA in courses required to complete their areas of study, as well as meet specific requirements set forth for the area of study.

### Areas of Study (Majors) for B.A. (Residential Only) 32 Credit Program

|                         |                                |                          |
|:---                     |:---                            |:---                      |
|Accounting, Managerial   |           Data Science         |                     Music|
|Accounting, Public       |            Economics           |                Philosophy|
|African American Studies |       Elementary Education     |                   Physics|
|Art                      |             English            |         Political Science|
|Asian Studies            |             History            |                Psychology|
|Biology                  |    Interdisciplinary Science   | Social & Criminal Justice|
|Business Administration  | Interdisciplinary Studies [^INT] |               Sociology|
|Chemistry                |     International Economics    |                   Spanish|
|Communication Studies    |      International Studies     |           Spanish Studies|
|Computer Science         |           Kinesiology          |              Theatre Arts|
|Creative Writing         |           Mathematics          |                          |

[^INT]: A coherent interdisciplinary sequence of courses devised by the student, in consultation with faculty, suited to the student’s individual goals and approved by the Academic Policies Committee.
