# STUDENT LIFE

Student Life provides personalized support to students, enabling each to gain the best possible undergraduate education adding substantially to the educational program. Residence accommodations, along with living and learning values, an attractive campus social life, a sound health program, good recreational facilities, and a program of co-curricular activities are among the opportunities offered Student Life.

## Campus Civility Statement 

This statement was written by students in order to address standards of civility and respect within the Coe College community. This statement is a living document and is intended to evolve over time. 

We, the members of the Coe College community, expect our campus climate to be safe, mutually supportive, academically encouraging, egalitarian, and tolerant of all its members: 

we expect the academic experience to extend beyond the classroom into our living environment. 

we expect a campus free of incidents that create a hostile living environment. 

we expect a healthy and responsible attitude to accompany all social gatherings. 

we expect that intoxication will not be an excuse for incidents that occur while under the influence. 

we expect that diversity of opinion should be cultivated and encouraged as well as respected within our community. 

we expect that everyone will have the right to be respected for his or her individuality.

we expect all campus community members to respect the rights of other persons regardless of their actual or perceived age, color, creed, disability, gender identity, national origin, race, religion, sex, or sexual orientation. 

A community is made up of individuals who model these standards and hold each other accountable. In order for the community to encompass the goals outlined above, each individual must be responsible and accountable for her or his own actions and words. 

## Student Contribution to College Policy

Coe is proud of its traditions and its ability to change. While cognizant of the past, the College is also sensitive to the changing nature and needs of students. Coe students play an integral part in the initiation of change by utilizing available channels and by the creative development and use of new ones. The Student Senate is a frequent forum for the resolution of student concerns.  

## Student Senate 

Student Senate is the representative government of Coe students and coordinates many co-curricular activities. Through the student activity fee, the Senate funds the weekly newspaper, the Cosmos, and other student publications. The Student Activities Committee (SAC) of the Student Senate sponsors bands, comedians, multicultural programming, and other kinds of entertainment and activities.  

## Student Handbook 

The *College Policies and Student Handbook* outlines the College’s expectations for responsible behavior reflecting maturity, mutual respect, and cooperation among all members of the Coe community. Student Life develops policies for conduct procedures, residence hall living, student organizations, and other areas of student affairs for approval by the Board of Trustees. The *College Policies and Student Handbook* is available online at https://www.coe.edu/student-life/community-standards-expectations/student-handbook

## Committee Participation 

Students serve on various committees, which aid in making educational policy at the college. Most committees (Academic Policies, Assessment, Athletics, Belonging, Campus Technology, Enrollment, Financial Aid and Academic Progress, Executive, Finance and Facilities, First-Year Program, Internationalization, Marquis Series, Petitions, Wellness, and Writing) include students appointed by the Student Senate as voting members. 
