# COLLEGE REGULATIONS AND POLICIES

## Effective Catalog

Students ordinarily are graduated under the provisions of the catalog of their matriculation date. A student’s matriculation date is the day of first enrollment following admission. If the student is readmitted, the matriculation date becomes the day of first enrollment following readmission. However, students will be expected to satisfy, to the extent practical, the graduation requirements of the catalog in effect at the anticipated date of graduation. Any necessary modification of general degree requirements will be worked out by the Provost and Dean of the Faculty, the Registrar, the appropriate department chair, and the Academic Policies Committee. Modification of major or minor requirements will be worked out by the department chair involved, the Registrar, and the student’s advisor. A student has the right of petition to the Committee on Petitions.

## Course Numbering

-	Courses numbered 100–199 are introductory to the subject.
-	Courses numbered 200–299 assume a capacity for the independent acquisition of material and generally build on the methods and subject matter of 100-level courses.
-	Courses numbered 300–399 are typically oriented toward a major or minor. They require a strong foundation of knowledge specific to the discipline.
-	Courses numbered 400–499 are courses in the major or minor that are designed to challenge students to integrate discipline-specific knowledge in advanced ways. These courses typically contain advanced disciplinary coursework, capstone projects, and/or independent research. 

## Grading

**GRADES**

|    |                                   |                                    |
|----|-----------------------------------|------------------------------------|
| A  | Excellent                         | 4.0 grade points per course credit |
| A- |                                   | 3.7 grade points per course credit |
| B+ |                                   | 3.3 grade points per course credit |
| B  | Above average                     | 3.0 grade points per course credit |
| B- |                                   | 2.7 grade points per course credit |
| C+ |                                   | 2.3 grade points per course credit |
| C  | Satisfactory, minimum expectation credit | 2.0 grade points per course credit |
| C- |                                   | 1.7 grade points per course credit |
| D+ |                                   | 1.3 grade points per course credit |
| D  | Passing, below expectation        | 1.0 grade points per course credit |
| D- |                                   | 0.7 grade points per course credit |
| F  | Failure                           | 0.0 grade points per course credit |
| WF | Failure                           | 0.0 grade points per course credit |
| P  | Pass                              | Credit awarded, no grade points given |
| NP | Not Pass                          | No credit and no grade points |

### Status Marks
 
- **W**	Approved withdrawal from a course. 
- **X**	Course extends beyond term.  An “X” status grade is given in courses designated in the Catalog as having coursework that extends beyond the end of the term.  Under no circumstances can an “X” grade remain unresolved for more than one calendar year.
- **O**	No mark had been reported by the instructor by the time academic reports were processed. 
- **I**	Incomplete. An “I” status grade is reported only for students who are unable to complete the work in the course due to extenuating circumstances.  The normal length of time for resolution of an incomplete is within four weeks of the next Fall or Spring term in which the student enrolls.  If the instructor believes the resolution of the incomplete will take longer, the instructor will note the later deadline when reporting the incomplete status grade.  An unresolved incomplete will automatically become a failing grade after the deadline, unless the instructor notes otherwise when reporting the incomplete.  Under no circumstances can an “I” grade remain unresolved for more than one calendar year.
- **R**	The prefix “R” to a grade (i.e., RA, RB, RC, RD, RF) indicates a grade of repeated course. A student may repeat a course previously taken, and registration must indicate this repeat. Failure to register for a repeat course properly results in no recognition of the second attempt. Only the grade earned when the course is retaken is used in computing the GPA. Credit may be earned only once for a given course. Courses may be repeated only once, although, students may petition for a second repeat if extenuating circumstances exist. 
- **EQ**	Equivalent credit recognized; no credit given. Does not increase courses attempted. For a student who has completed four course credits of student teaching and who has high school or life experience equivalent to a regular catalog course, the said course, upon recommendation of the Education chair and the chair of the department in which equivalent credit is being recognized, may be listed on the student’s transcript with the appropriate credit and a status mark of “EQ.” 

### Audited Courses 

Students may audit courses with the consent of the instructor. In doing so, they attend class but are not required to take tests or submit papers. Audited courses receive no credit and do not appear on transcripts. 

### First Course Grading For Non-Traditional Students 

Individuals who have been away from the collegiate routine for several years may register on an audit basis in their first course while paying half tuition for this one course, participate fully in the class (including tests, papers, etc.), and decide at the conclusion of the course if they wish to pay the other half of the tuition and receive credit for the course. This policy applies only to the first course—not to succeeding courses. 

### Courses Graded as Pass/Not-Pass

Courses are graded A–F unless otherwise indicated in the course description that only P/NP is an option (e.g., student teaching, internships).  Courses graded P/NP count as credits towards graduation but do not affect the student’s GPA. In addition, students may opt to take up to four A–F graded courses on a P/NP basis.  When students opt for P/NP grading, the Office of the Registrar converts any grade a faculty member provides of D- or better to a P, and any grade of F to an NP. In order to count for Writing Emphasis credit, a submitted grade of C or higher must be earned.

The following regulations apply: 

1. Students are permitted to change the method of grading for a course from a letter grade to P/NP.  This change is allowed from the start of the term of enrollment through the last day to withdraw from courses during that term. See Academic Calendar Section 3.0.1 for official dates.
2. Students may elect to take up to four graded courses during their undergraduate career on a P/NP basis. However: 
    a. Students cannot use a course for which they elected P/NP grading to satisfy the requirements for a major or minor. 
    b. Students cannot elect P/NP grading while on academic probation, though provisionally-admitted First Year students are allowed the option of P/NP grading. 
3. The Registrar will not inform the instructor of the student’s request for P/NP grading and the instructor must provide the Registrar with an appropriate letter grade. 
4. A student’s request for P/NP grading may be nullified at any time before the end of the third business day after grades are due in the student’s final term.  A written notice must be sent to the Office of the Registrar to communicate the student’s intent to replace the P or NP grade with the instructor’s letter grade. 
5. A student’s request to change their method of grading to P/NP in lieu of a letter grade counts as one of the four P/NP elected courses during the student’s undergraduate career, regardless of whether it is later nullified. 
6. Ordinarily a student is limited to one course credit per term on an elected P/NP basis.  A student wishing to exceed this limitation must present a convincing rationale or significant mitigating circumstances to the Committee on Petitions. 

### Midterm Grades 

Midterm grades are not official evaluations and are not part of the official transcript. The goal of midterm grades is to help students take responsibility for their academic progress. Faculty submit midterm grades of A-F for students in all full-term courses. Midterm grades are not intended to be a guarantee, promise, or contract regarding the final grade a student will earn in the class. Instead, they provide information for students about their academic performance.

## Class Designation

Class Designation is determined by the number of course credits earned following the Fall and Spring Terms. 

First-year student: Fewer than 8.0 course credits earned  

Sophomore: 8.0–15.9 course credits earned 

Junior: 16.0–23.9 course credits earned 

Senior: 24.0 or more course credits earned 

## Registration

Before being allowed to register, students must have been admitted for study by the Office of Admission, must have settled their account with the Business Office, and must meet with their Academic Advisor. Registrations are canceled for failure to pay fees on time. 

Students are encouraged to develop a four-year comprehensive educational plan with the help of their advisor or with other members of the faculty. 

Students who will not graduate during the current academic year register online during the Spring Term for the Fall Term of the following academic year during times specified by the Office of the Registrar. Registration for the Spring and May Experiential Terms takes place during the preceding Fall Term. Once the online registration period is over, all changes to registration must take place in the Office of the Registrar using accurate, legible, and completed registration forms. Entering first-year students and transfer students receive instructions with their orientation materials, and readmitted students receive instructions from the Office of the Registrar concerning their registrations. Registrations are not accepted for a term without successful petition after the end of the first week of classes of that term. 

### Changes in Registration 

1.	Unless a course is registered by a student online during the registration period, they must intentionally file a registration form with the Office of the Registrar in order to be registered for a course.  Registration forms for course additions must be approved by the student’s advisor and instructor of the course. 
2.	Courses may be added or dropped during the first five days of the Fall, Spring, or Summer Term, including 7-week courses. Students may add a May Experiential Term course during the first three days of said term. If a student needs to add a course after these deadlines due to extenuating circumstances, the student must petition the Committee on Petitions by completing the appropriate forms.
For courses spanning a fraction of a Term, the last date to add or drop without a “W” will be calculated as a proportionate time frame comparatively as full-term courses. Students can withdraw from a course without a WF during the first two-thirds of the term.
3.	A student may withdraw from one or more courses with the following results: 
-	If a student withdraws from a course when 2/3 or less of the Term is completed, a “W” (withdrawal) grade will be entered on the student’s permanent record. This grade will not affect the student’s GPA. This is the date listed in the academic calendar as the Last Day to Withdraw from a course.   
-	For courses spanning a fraction of a Term, the last date to withdraw with a “W” will be calculated using the 2/3 fraction.  See Academic Calendar (p. 10) for official dates for full-term and half-term courses.
-	If a student officially withdraws from a course after 2/3 of the Term is completed, a “WF” will be entered on the student’s permanent record. This will affect the student’s GPA. 
-	A withdrawn course, regardless of the date withdrawn, counts as attempted credits on the transcript. Therefore, it also counts when calculating academic standing and satisfactory academic progress (see p. 229) for financial aid.

### Course Load 

A student is full-time for the Fall or Spring Term when enrolled for three or more course credits. A student enrolled for fewer than three course credits is a part-time student. For financial aid purposes, half-time is defined as enrollment in no fewer than two course credits in each of the Fall and Spring Terms; three-fourths is defined as enrollment in no fewer than 2.5 course credits in each of the Fall and Spring Terms. Students who have earned a cumulative GPA of 3.4 or above, or have earned both 23 credits and a cumulative GPA of 2.5 or above, may take above 4.99 credits without the need for a petition, but approval must be secured from the Office of the Registrar. Other students must submit a petition to the Committee on Petitions and obtain approval in order to register for five or more course credits. No student shall be permitted to register for over 5.99 credits in each of the Fall and Spring terms. The Committee on Petitions will only consider petitions for above 4.99 credits from those students who have completed at least one term as a full-time student.  Students may not register for more than one course credit during May Experiential Term.

## Administrative Withdrawal Policy

Students must be registered for courses and abide by add/drop and late registration changes according to all existing procedures in the Coe College Academic Catalog.

Under extreme circumstances, a student may be administratively withdrawn from their courses. While the college reserves the right in each instance to determine when administrative withdrawal appears appropriate, normally this process can be initiated after the following conditions have occurred:
-	The student has not completed any work for their current term courses in three weeks (21 days) and has not communicated with any of their faculty in said period of time.
-	The student is not responding to reasonable requests from their faculty, the Dean of Student Success and Persistence, the Dean of Students, the Provost and/or other college personnel related to student support.
-	In the case of the above circumstances, the Dean of Student Success and Persistence will reach out to the student a final time offering them 48 hours to respond and start attending class.
-	If the student responds within 48 hours, the Dean of Student Success and Persistence meets with the student to determine whether the student desires to withdraw from enrollment with the college, and if not, any conditions for the student's continued enrollment with the college.
-	If the student does not respond, their case will be reviewed by CAPE, and a recommendation for withdrawal may be forwarded to the Provost Office. The Provost will review the material and make a final determination and then instruct the Registrar accordingly.
-	The student will be notified by letter. If the student has authorized disclosure of educational records to their parent(s)/guardian(s) under FERPA, the college will notify the student's parent(s)/guardian(s).

## Academic Integrity Policy

At Coe College, we expect academic integrity of all members of our community. Academic integrity assumes honesty about the nature of one’s work in all situations. Such honesty is at the heart of the educational enterprise and is a precondition for intellectual growth. Academic dishonesty is the willful attempt to misrepresent one’s work, cheat, plagiarize, or impede other students’ academic progress. Academic dishonesty interferes with the mission of the College and will be treated with the utmost seriousness as a violation of community standards. 

### Forms of Academic Dishonesty 

- *Cheating* is the attempt to deceive an evaluator by claiming credit for work one has not done or by knowingly assisting such an attempt. It includes (but is not limited to) the use of unauthorized sources of information on in-class or take-home exams, or other assignments; copying from other students on exams, assignments, or lab reports; fabrication of data, research, quotations, or other information; and taking credit for collaborations to which one has not contributed. 
- *Plagiarism* is the use of someone else’s words or ideas without acknowledgement and, when intentional, is a form of academic dishonesty. The unacknowledged use of words or ideas from *any* published or unpublished sources, including Internet resources or other student papers, constitutes plagiarism. Plagiarism may occur intentionally or unintentionally through the omission of appropriate citations. *Any* ideas or information the student adopts from a source, whether or not directly quoted, must be acknowledged by specific reference in notes or the text. 
- *Any* words or phrases that are taken from a source must be quoted and cited. *Any* paraphrase—the restatement of an idea in your own words—must be cited. 
The methods of citation and documentation vary from discipline to discipline. Students are responsible for determining the appropriate method for any given assignment or, in the absence of a clearly stated protocol, using any accepted academic method. Guidelines can be found on the library website and in the Writing Center. 
- *Other forms of academic dishonesty* include (but are not limited to) deliberately impeding other students’ work and misuse of common academic property, in the libraries, labs, and elsewhere. 

### Statement on Generative Technology

Use of generative writing technology (such as ChatGPT or similar) without express permission from your instructor is a form of academic dishonesty. If specific parameters of use are not outlined by an instructor, students should assume use of said technology is prohibited, and that unauthorized use of it will be subject to disciplinary action. Coe College faculty may set parameters for when and how the use of such technology is permissible, as well as how students should document their use of it.

### Sanctions 

Instructors have responsibility for determining whether academic dishonesty has occurred. Instructors shall proceed with sanctions accordingly. Any act of academic dishonesty that results in one of the sanctions below shall be detailed in a formal report filed with the Provost and Dean of the Faculty. 

Cases of unintentional plagiarism may be dealt with through educational procedures such as further assignments requiring the student to practice documentation and citation methods, or other means determined by the instructor. 

Acts of academic dishonesty will be subject to one or more of the following sanctions:
1.	failure of the assignment, i.e. exam, paper, lab report, etc. 
2.	other sanction as determined by the instructor, within the framework and grading rubric of the class
3.	failure of the class 
4.	suspension or expulsion 

An instructor may impose the first three of these penalties. Suspension or expulsion may only be carried out by the Provost and Dean of the Faculty. 

Repeated acts of academic dishonesty will result in suspension or expulsion. When academic dishonesty has been determined to have occurred a second time, the Provost and Dean of the Faculty shall decide on the student’s status at the College. 

### Procedure

When an instance of academic dishonesty is suspected, the instructor will meet with the student to discuss the incident and will decide which, if any, of the above sanctions is appropriate. 

If warranted, the instructor will send a report to the Provost, with a copy given to the student, which details the nature of the violation and the steps taken to address it. The Provost will send a letter to the student within ten business days of receipt of the faculty member’s report. The letter will reiterate the incident, describe the sanctions, and inform the student of their right to appeal. The report and letter from the Provost will remain on file in the Academic Affairs Office until five years after the student’s graduation or severance from Coe. The Vice President for Student Life will be notified that a report has been filed. Information in the file will be confidential, to be shared only at the discretion of the Provost and Dean of the Faculty for a legitimate educational or legal purpose. 

### Appeals Process

The student may appeal the charge and/or the sanction within ten business days of receiving the Provost’s letter of notice by emailing the Provost and Dean of the Faculty requesting an appeals hearing. Students wishing to appeal are strongly encouraged to consult with the Associate Dean for Student Academics, who has been designated by the College to help explain the appeals process and work with the student if they choose to appeal. 

The Provost’s Office will convene an Academic Integrity Appeals Board within ten business days of receipt of the request for appeal to hear the appeal. The Academic Integrity Appeals Board will be chaired by either the chair or co-chair of the Academic Policies Committee. Additional members of the board will include: one additional faculty member on the Academic Policies Committee, a senior Student Life officer, one faculty member from the Committee on Academics, Persistence and Enrollment, and the Associate Dean for Faculty Development.  In any hearing the Provost may replace the Associate Dean for Faculty Development, or other member of the board to avoid conflicts of interest. The student may choose to have a faculty or staff member present as an observer. The student and the instructor will each appear as witnesses and each may request that other pertinent witnesses appear. 

A majority vote of the Appeals Board is necessary to uphold or overturn a sanction. If a sanction is overturned, the Appeals Board may impose a lesser sanction. The Appeals Board will submit a written finding which will be sent to the student and the faculty member(s) involved in the case and which will become part of the student’s file. If the appeal’s outcome is to overturn the dishonesty charge, the report in the Academic Affairs Integrity file will be removed.

## Academic Standing

All students are expected to meet the College’s standards for academic performance (see chart in this section). These are in place to keep students on track towards meeting the graduation requirements of the college (32 credits with a cumulative GPA of 2.0). Students who do not meet Coe’s academic standards may be put on probation or suspended from the College.

To make sure that students are aware when their academic standing is in jeopardy, a series of communications are issued throughout an academic term including D/F notices, academic warnings, and notices of academic probation. Unless otherwise stated, these communications will be sent to the student by email sent to the student’s Coe email address. Additionally, advisors may be contacted about their advisees’ performance.

### D/F Notices

Academic notices are issued at midterm to students who earn a D, F, or NP in one or more courses. Students receiving these notices are expected to meet with their academic advisor to identify appropriate support.

### Academic Warnings

Academic warnings will be issued to students who earn a term grade point average below 2.0 while retaining a cumulative grade point average of 2.0 or higher. Students receiving academic warnings are strongly encouraged to re-evaluate their current approach to their studies and/or their academic plans. They are expected to meet with their academic advisor.

### Academic Probation

The Academic Standing Committee reviews academic records of all students at the conclusion of both the Fall and Spring Terms. A student is placed on academic probation if the cumulative GPA falls below the minimum GPA levels listed below:

| Total Course Credits Attempted | Minimum GPA Levels |
|:------------------------------:|:------------------:|
| 0.0 – 4.99                     | l.50               |
| 5.0 – 7.9                      | l.75               |
| 8.0 – 11.9                     | 1.80               |
| 12.0 – 15.9                    | 1.90               |
| 16.0+                          | 2.00               |

Students who are placed on probation for academic standing reasons will receive a letter via their Coe email address notifying them of their probation status. To return to good standing and be removed from academic probation, a student shall earn a cumulative GPA greater than the threshold for academic probation as specified above. Students who are placed on academic probation have a maximum of two (2) consecutive terms, excluding May and Summer, to return to good standing before they are subject to academic suspension. In the first probation term, a student on probation is required to enroll in SKD-145 Strategies for Academic Success.

A student on probation is also subject to academic suspension if their cumulative GPA decreases at the end of any term on probation.

Students who are on academic probation:
-	Are expected to comply with any requirements outlined by the Academic Standing Committee.
-	May not elect P/NP grading in lieu of a letter grade.
-	May not be excused from attending class to participate in extra-curricular activities.

The status of academic probation is noted on a student’s transcript.

Students on probation who are not meeting the conditions of their probation and not performing at a passing level in their courses may be withdrawn from the College during the term on the recommendation of the Academic Standing Committee. If the student had previously appealed a suspension, the suspension is reinstated. Otherwise, the student will be exited from the College and is eligible to return on probation the following term. Students may appeal this decision to the Provost.

### Academic Suspension

Students who do not meet the conditions of their academic probation or who fall below retention thresholds (see below) will be considered for academic suspension by the Academic Standing Committee, and, if suspended, will be unable to take courses at Coe College for a period of at least one academic year. (One academic year is defined as a Fall and Spring Term, and does not count May or Summer Terms.) A registration hold preventing registration will be placed on the student’s account. A student already registered for the following term will be dropped from those courses.

| Total Course Credits Attempted | Minimum GPA Levels |
|:------------------------------:|:------------------:|
| 0.0 – 4.99                     | 0.50               |
| 5.0 – 7.9                      | l.00               |
| 8.0 – 11.9                     | 1.50               |
| 12.0 – 15.9                    | 1.70               |
| 16.0 – 19.9                    | 1.80               |
| 20.0 – 23.9                    | 1.90               |
| 24 +                           | 2.00               |

Students who are placed on suspension for academic reasons will receive a letter via their Coe email address notifying them of their suspension status. Suspended students have the right to appeal for immediate readmission if they can provide evidence of circumstances that would warrant reconsideration by the deadline indicated in their suspension letter.

To appeal for immediate readmission:
-	A suspended student appealing for readmission must submit a written form that offers an explanation of any circumstances that affected the student’s academic performance, as well as a detailed plan with specific actions that the student will take to improve their academic standing, including how the student will overcome the obstacles that affected their academic performance. The form will be made available to eligible students online, and must be completed by the deadline communicated in the suspension letter in order to be considered. Student appeals will not be considered if required materials are not received by the deadline.
-	Following submission of the appeal form, the student must also schedule a hearing with the Academic Standing Committee At this meeting the student will have the opportunity to respond to questions the Committee may have on the circumstances outlined in the student’s appeal materials.
-	A suspended student appealing for readmission is encouraged to request a letter of support for immediate readmission from a faculty advisor or other faculty or staff member at Coe, if the letter can shed light on the student’s ability and motivation to do well in future academic endeavors. Similarly, the student is encouraged to consult with one or more faculty or staff members to prepare a strong case for readmission.

Students who have been suspended for academic reasons from the College once, can return to the College either through a successful appeal for immediate readmission or through readmission after leaving for at least one academic year. A student who is suspended for academic reasons more than once cannot appeal for immediate readmission and must leave the College for at least one academic year.

### Interim Suspension

Interim Suspension is a situation where it is determined that a student’s continued presence at the college constitutes an immediate threat of harm to the student, other individuals, or to the stability and continuance of normal College functions.  The Provost and Dean of Students or their designee may suspend a student pending disciplinary proceedings. Such suspension may become effective immediately and without prior notice. 

Interim suspension shall be considered an excused absence until the conclusion of formal hearings.  The student will be offered the opportunity to make up any academic work missed during the time in which the interim suspension was imposed. It is the student’s responsibility to make specific arrangements with faculty members to complete academic work. The Dean of Students will initiate communication with the appropriate faculty.

### Readmission Following Suspension

Coe College’s academic suspension policy allows students, who are not readmitted immediately through appeal, to apply for readmission after at least one academic year has passed.

To be considered for readmission, the student must file a request to return with the Associate Dean for Student Academics. In the appeal documentation, the student must present evidence that demonstrates how the circumstances that led to the student’s academic suspension have been addressed, and how the student plans to be successful in his or her academic future. Readmission is determined by the Associate Dean for Student Academics, in consultation with other campus officials as necessary. These officials reserve the right to conduct its own investigation, review the case, and make a final decision concerning the student’s reinstatement to the College. When appropriate, certain academic stipulations may be applied. If a suspended student provides evidence of successful course completion elsewhere and/or written evidence of motivation and maturity necessary to be academically successful at Coe, the student may be readmitted on probation at Coe.

## Exiting the College 

The exit process at Coe College, whether through withdrawing or taking a leave of absence, is initiated by the student. Students must contact the Dean of Student Success & Persistence to conduct an exit interview. At the interview, the student is given an official exit checklist that provides information that students should collect from other offices on campus, including the Student Financial Services Office, to verify a balance due or a credit to be refunded; Student Loan information, to be aware of financial aid adjustments; the Library, to ascertain that all materials have been returned; and the Director of Residence Life, to arrange for room checkout.  All exiting students will also be asked to complete an exit survey, which can be completed electronically after the exit interview.

If a student withdraws from all courses during a period of enrollment for which they received financial aid, the Student Financial Services Office will determine how much, if any, of the student’s financial aid proceeds must be returned to the College, based on a federally mandated refund formula (see *Return of Title IV Funds/ Institutional Refund Policy*, p. 223).

Special consideration is given to students who withdrew due to a call to active duty. Coe’s “Military Call Up/Refund” and “Readmission of Service Member” policies are published on the Admission/Financial Aid webpage. Copies of these policies can be requested from the Student Financial Services Office.

## Leave of Absence

A student may find it necessary to interrupt a program of study at the College. Under this condition, the student may apply for a leave of absence. A leave of absence may be granted for a period not to exceed 12 months. Students may extend a leave of absence to up to a total of 36 months by contacting the Office of the Registrar via email at o-registrar@coe.edu. Students are officially withdrawn from the College upon beginning a Leave of Absence, but they may return to the College without reapplying. Students who neither renew their leave of absence nor return to Coe will have to reapply should they wish to return to the College. Coursework completed while on leave from the College is subject to the same conditions as work in transfer. 

### Requesting a Leave of Absence 

Students planning to take a leave of absence from the College should first consult their academic advisor and then **must declare** their intent. Students should contact the Dean of Student Success & Persistence to initiate the process. Please refer to the previous section on exiting the College for the steps that follow.

### On Leave of Absence 

The Coe community is committed to supporting students while they are away from the College. Thus, the Associate Dean for Student Academics may assign a designee who will be the point of contact to each student on a leave of absence. This designee will stay in contact with the student during their time away from the College, as appropriate, and will assist with the return process once the student is ready to resume coursework. 

### Returning to Coe after a Leave of Absence 

Students planning on returning to the College from a leave of absence do not need to apply for readmission, but must submit a statement of intent to re-enroll to the Office of the Registrar and the Associate Dean for Student Academics, or designee, who will assist with the return process. Students are strongly encouraged to schedule a consultation with the Associate Dean for Student Academics, or designee, by December 1 for returning the Spring Term, or August 1 to return the Fall Term. If a student wants to register during the regular registration time (November for Spring Term or late March / early April for Fall Term), they will need to submit their statement of intent and contact the Associate Dean for Student Academics, or designee, at least two weeks before Registration. The exact date of Registration can be found on the Academic Calendar on the Coe website under the Academics tab. 

## Withdrawal from the College and Readmission 

Admission for work toward a degree terminates and the student is considered withdrawn from the College if: 
1.	A full-time student does not enroll at Coe for the next term (excluding May Experiential Term and Summer Term) and has not completed a Leave of Absence form. This does not apply to students in College-approved off-campus study programs. 
2.	A part-time student does not enroll for a course at Coe in a 12-month period and has not completed a Leave of Absence form. 

Students wishing to resume work toward a degree, once admission status has terminated, must apply for readmission.

## Transcript Evaluation Policies

Official transcripts for courses taken at Coe College can only be issued by the Office of the Registrar and only after the office has received a written request and payment from the student.

### General Policy on Transfer Credit

To honor its mission and to preserve its academic integrity as a liberal arts institution, the College accepts a course in transfer for the equivalent earned credit (4 semester hours = 6 quarter hours = 1 course credit), if that course meets the spirit of the College’s mission and is from a regionally accredited institution. The College can only enter transfer work upon receipt of an official transcript with final grade(s) for the coursework in question. Departments will accept transferred 100- and 200-level course equivalencies toward fulfilling major or minor requirements, unless otherwise noted in a respective department’s section of the Catalog. In cases where it is unclear whether the course would be acceptable for transfer credit, the Registrar and the appropriate department chair will consult. Other exceptions are referred to the Committee on Petitions. First-year seminars may transfer in for elective credit but will not fulfill other requirements. Neither remedial nor skill-development courses may transfer in. Practicum and Writing Emphasis options may not be transferred in and must instead be taken at Coe except in cases of transfer students with approved degrees. Mathematics courses may only transfer in if they are Calculus I or higher. Coursework of a technical/professional/vocational nature generally will not transfer into Coe.

### Evaluation of Credits in Transfer

The Office of the Registrar is responsible for the evaluation of transfer credit. Credits accepted in transfer do not affect the cumulative GPA. Grades for the credits accepted are not recorded on Coe’s transcript. Thus, transfer credits increase only the total courses attempted and the total course credits earned. Credit is not accepted for course work earning a grade below “C” (2.0 on a 4.0 scale), nor for courses on a Satisfactory/Unsatisfactory or Pass/Not Pass basis, unless the institution where the course was taken provides verification that the student earned at least the equivalent of a “C” in the course.

Accepted transfer credit appears on a student’s Coe transcript with a grade of “P” (Pass), which does not influence GPA. If an equivalent course is repeated at Coe College, the transfer credit no longer counts toward graduation. In the reverse situation, if the equivalent to a Coe course is taken as a repeat at another institution and transferred in, the original Coe course, and any earned credit associated with it, is forgiven and the transfer work takes its place.

### Junior or Community College Credit

A maximum of 16 credits (junior standing) will be accepted as transfer credit from the sum of 2-year regionally accredited institutions plus AP/IB scores. Transfer students who complete a regionally accredited A.A. degree program or a regionally accredited college-parallel A.S. degree program will be accorded junior status (16 course credits) at Coe. Transfer students who complete an A.A., A.S., or A.A.S. degree from a regionally accredited institution with which Coe has a specific articulation agreement will be awarded credit consistent with that agreement. A transferred A.A, A.S., or approved A.A.S. degree fulfills the General Education Distribution, Diversity Across the Curriculum, and Writing Emphasis requirements but not the Practicum requirement. See p. 25 for information on reverse credit transfer for transfer students who have not yet finished their associate’s degrees at time of beginning coursework at Coe.

### Four-Year College Credit

For students pursuing a B.A, B.S.N. or B.S.E, a maximum of 24 credits (senior standing) will be accepted as transfer credit from the sum of 4-year regionally accredited institutions, plus 2-year regionally accredited institutions, plus AP/IB scores. For students pursuing a RC-B.A, a maximum of 16 credits will be accepted as transfer credit from the sum of 4-year regionally accredited institutions, plus 2-year regionally accredited institutions, plus AP/IB scores. For information on second-baccalaureate degree students, see p. 26.

### European Credit Transfer System (ECTS)

ECTS credits are a relative rather than an absolute measure of student workload.  They specify how much of a year’s workload a course unit represents at the institution or department allocating the credits. ECTS is thus based on a full student workload and not limited to contact hours only.

In ECTS, 60 credits represent the workload of a normal undergraduate academic year of study and normally 30 credits for a semester and 20 credits for a term. Thus, ECTS credits will normally be transferred to Coe College at a rate of 7.5 ECTS credits: 1 Coe credit.

### Occasional Transfer Credit for Degree-Seeking Students

Degree-seeking students sometimes wish to transfer credit from another institution toward their degree at Coe. Such credit must be approved in advance of completion of the course by the Registrar. Departments must approve in advance any courses counting toward a major, a minor, or teacher certification requirements.

### Evaluation of Credits for Graduation

The Office of the Registrar certifies the completion of area of study and General Education requirements. Credits toward a major, minor, endorsement, license, authorization, etc. are approved by the appropriate department chair, administrative coordinator, or by Academic Policies Committee for interdisciplinary majors. Departments will accept transferred 100- and 200-level course equivalencies toward fulfilling major or minor requirements, unless otherwise noted in a respective department’s section of the Catalog.

### Credit by Examination

A maximum of eight course credits (sophomore standing) in satisfaction of degree requirements may be applied from credit earned through the sum of the Advanced Placement (AP) Program and International Baccalaureate (IB). Students may not receive college credit for both AP and IB in areas of similar content.

### Updating Course Work

In the natural course of reviewing academic records, a student may be required to repeat certain courses (or appropriate substitutes) taken more than four years prior to the review to bring studies in those areas up to date. Review cases may be brought to the Academic Policies Committee by any member of the faculty, and this committee makes the final decision. 

### Advanced Placement (AP)

Coe College’s Advanced Placement code is 6101.

Coe College grants college credit for approved Advanced Placement examination scores of 4 or 5.  AP credit cannot be used to fulfill any General Education requirement. Each AP exam may earn 1.0 course credit up to a maximum of eight total course credits towards graduation from AP and IB.  Credit is granted upon receipt of the results of the examination, which must be received directly from the Educational Testing Service.  Further information regarding Advanced Placement examination reporting to the College may be obtained in the Office of the Registrar and on Coe’s website. If an equivalent course is taken after matriculation to Coe College, the AP credit is removed from the transcript.

### International Baccalaureate (IB)

Coe College credit may be awarded for International Baccalaureate work.  Students may earn 1.0 course credit for each higher-level examination score of 5, 6, or 7 to a maximum of eight total course credits from AP and IB.  No credit is granted for standard-level examinations.  IB credit cannot be used to fulfill any General Education requirement.  Credit is granted upon receipt of the results of the examination, which must be received directly from the International Baccalaureate Organization.  Further information regarding International Baccalaureate examination reporting to the College may be obtained in the Office of the Registrar and on Coe’s website.  If an equivalent course is taken after matriculation to Coe College, the IB credit is removed from the transcript.

## Class Attendance

Regular class attendance is expected, although the instructor of each course sets the standard expected to be met by the students. The College expects attendance on all scheduled days, including the first and last day of a term, as well as the class days immediately preceding and following College holidays. Students officially representing the College are excused as necessary prior to the absence. Students on academic probation are not excused from attending class to participate in extra-curricular activities. 

## Final Exams

The final exam schedule is published by the Registrar. It is expected that final exams will be given during the time scheduled for each course. There may be extraordinary cases when an individual student has a compelling reason for taking an exam at a time other than that scheduled. In such cases the instructor may properly decide to let that individual take the exam at another time. Having more than two exams scheduled on one day would justify allowing a student to take a third exam on another day. The instructor of the course with the highest course number will move the exam, for that student only, to a mutually convenient time.

## Participation in Commencement 

Students can participate in Commencement when they have met all the requirements for graduation for one of Coe’s degrees, they have completed their Intent to Graduate form, and it has been fully processed and approved by the Registrar’s Office. (Intent to Graduate forms will be processed in the order they are received. Submissions past the deadline have no guarantee of being processed for Commencement participation.)  In addition, all students, unless excused in writing by the Provost, must complete a survey assessing their educational experience at Coe.  All pending graduates must participate in Commencement exercises unless excused in writing by the Registrar.

### Pending Graduates

Students who need to earn no more than 2.0 course credits to complete all graduation requirements may be permitted to participate in one Commencement exercise provided the remaining course credits are scheduled to be completed within one academic year of their Commencement ceremony.  In these instances, a plan for completion must be submitted in writing to the Registrar’s Office and approved by the Registrar prior to Commencement. Coe graduates may participate in Commencement no later than one academic year following the conferral of their degree. Pending graduates will be listed in the Commencement booklet, but will not receive their diploma until all graduation requirements are met.  Final Latin honors (see p. 28) are bestowed only after all graduation requirements are met, and will be listed on a student’s final diploma and transcript.

## STUDENT NOTIFICATION OF RIGHTS UNDER FERPA

The Family Educational Rights and Privacy Act (FERPA) affords students certain rights with respect to their education records. They are: 

-	the right to inspect and review the student’s education records within 45 days of the day the College receives a request for access. Students should submit to the Office of the Registrar written requests that identify the record(s) they wish to inspect. The Registrar will make arrangements for access and notifies the student of the time and place where the records may be inspected. If the records are not maintained by the Office of the Registrar, the Registrar shall advise the student of the correct official to whom the request should be addressed. 
-	the right to request the amendment of the student’s education records that the student believes are inaccurate or misleading. Students may ask the College to amend records that they believe are inaccurate or misleading. They should write the College official responsible for the records, clearly identify the part of the record they want changed, and specify why it is inaccurate or misleading. FERPA was not intended to provide a process to be used to question substantive judgments which are correctly recorded. The rights of challenge are not intended to allow students to contest, for example, a grade in a course because they felt a higher grade should have been assigned. If the College decides not to amend the record as requested by the student, the College will notify the student of the decision and advise the student of his or her right to a hearing regarding the request for amendment. Additional information regarding the hearing procedures will be provided to the student when notified of the right to a hearing. 
-	the right to consent to disclosures of personally identifiable information contained in the student’s education records, except to the extent that FERPA authorized disclosure without consent. One exception which permits disclosure without consent is disclosure to school officials with legitimate educational interests. A school official is a person employed by the College in an administrative, supervisory, academic or research, or support staff position (including law enforcement unit personnel and health staff); a person or company with whom the College has contracted (such as an attorney, auditor, collection agent, or official of the National Student Clearinghouse); or a student serving on an official committee, such as an admission, petitions, retention, honors recognition, disciplinary, or grievance committee, or assisting another school official in performing his or her tasks. A school official has a legitimate educational interest if the official needs to review an education record in order to fulfill his or her professional responsibility.
-	the right to file a complaint with the U.S. Department of Education concerning alleged failures by the College to comply with the requirements of FERPA. 

A student is a person who attends or has attended Coe College, as determined by matriculation and enrollment by the first date of an academic term. Coe College obtains written permission from the student before releasing any information from a student’s educational record in most cases.  However, as the law allows, on a case-by-case basis, appropriate parts of a student record may be disclosed, without consent of the student, to the following parties: 

-	college employees who have a legitimate need to know. 
-	persons who need to know in cases of health and safety emergencies. 
-	accrediting organizations to carry out accrediting functions. 
-	appropriate parties in connection with financial aid to a student. 
-	federal, state, and local governmental officials for purposes authorized by law. 
-	individuals who have lawfully obtained court orders or subpoenas. 
-	organizations conducting educational studies for the College. 
-	courts during litigation between the College and the student or parent.
-	victim of crime of violence after final results of a disciplinary hearing. 
-	public after disciplinary proceedings determine student committed crime of violence. 

In many situations, complaints relative to FERPA can be resolved with the College on an informal basis by contacting the Registrar, in the lower level of Voorhees Hall. 

**To file a FERPA complaint** with the U.S. Department of Education, contact the office that administers FERPA at: Family Policy Compliance Office, U.S. Dept. of Education, 400 Maryland Avenue SW, Washington, DC 20202-4605.
