# COURSES OF INSTRUCTION

## INDIVIDUALIZED STUDY

### INDEPENDENT STUDY

The one-credit independent study is a student-driven initiative that requires the completion of a minimum of 140 hours of academic work, including meeting with a faculty advisor and performing independent work between meetings. Developed and outlined by the student, an independent study supplements the existing departmental program through more intensive study of a present topic or through examination of topics not comprehensively covered in an existing course. An existing course taken by arrangement does not constitute an independent study. Independent studies are only offered at the 300- and 400- levels and are meant to foster a student’s pursuit of career and/or personal goals outside of the classroom. A proposed independent study must receive approval from the respective department chair and be registered through the Office of the Registrar in order to receive credit and count toward the practicum requirement. A student may receive a total of no more than 2.0 credits from independent studies. A student may only repeat an independent study with the same course code if approved by the relevant department chair. 

### DIRECTED LEARNING

The one-credit directed learning is an instructor-driven initiative that requires the completion of a minimum of 140 hours of academic work, including meeting with a faculty advisor and performing independent work between meetings. Developed and outlined by the instructor, directed learning helps students specialize in a major or minor. A proposed directed learning must receive approval from the respective department chair and be registered through the Office of the Registrar to receive credit and does not count toward the practicum requirement. A student may receive a total of no more than 2.0 credits from directed learning. A student may only repeat a directed learning with the same course code if approved by the relevant department chair. 

## ACADEMIC PROGRAMS

### Asia Term
Carstens (Co-Program Director), Nordmann (Co-Program Director)

**ASC-195 Asian Tonal Languages**  
An introduction to Thai, Vietnamese, and other tonal Asian languages.  Emphasis is on basic communication as well as the distinguishing features of languages that use tones as part of their linguistic system. 

**ASC-196 Modern South East Asia**  
An introduction to several Asian cultures such as Thai, Cambodian, and Vietnamese.  This course varies depending on the field of the supervising Coe faculty member. 

**ASC-444 Independent Study**  
A student-designed study of some feature of Asian culture, arranged in consultation with the supervising Coe faculty member. May be taken more than once for a maximum of 2.0 credits. Prerequisite: consent of instructor. 

### World Language
Rodríguez Moreno (Program Director)

**FSA-100 Foreign Study Abroad**  
Study abroad during May Experiential Term supervised by a Coe College faculty member, with site visits to places of historical and cultural interest. When appropriate, may count as a course in the major. May be taken more than once if offered in different locations. Prerequisite: consent of instructor. (Offered May Experiential Term only) 

**FSA-146 Turkey: History and Culture**  
Study abroad course on the history and culture of Turkey.  An exploration of a unique secular-Muslim society.  Particular historical focus is on Istanbul and ancient cities on Aegean coast.  Prerequisite: consent of instructor. (Offered May Experiential Term only)

**WLC-108 Cultural Studies and Literature in Translation (WE)**
A topics course, taught in English, that explores shared historical, literary, and cultural themes and experiences in the French and Spanish-speaking worlds. Topics may include the history and literature of slavery and colonization, environmental humanities, contemporary films and graphic novels, and social justice in globalized contexts. It may be counted for credit toward a Spanish or French and Francophone Studies majors and minors.

### Internships

The internship is a work or volunteer experience in the context of an independent academic investigation of site-related issues and personal aptitudes, values, and goals. Internships include a minimum of 140 hours of on-site or remote experience and the required documentation and/or academic journal or paper as determined by the faculty member.  The details of the academic component are determined by prior arrangement with the faculty internship advisor.

Internships are completed during the academic year for 1.0 credit, or during Summer Term for either 1.0 credit or 0.0 credit determined by the course registration.  In unusual circumstances where an internship presents an opportunity to extend the educational component of the experience significantly, an internship may earn 2.0 credits. Application for non-departmental, two-credit internships requires consultation with the Internship Faculty Advisor and approval of the Committee on Petitions; departmental two-credit internships, when permitted, are overseen by the department. 

A combined maximum of 2.0 course credits may be counted toward the 32 credits required for graduation through Internships or Community-Based Project. Many internships are completed in the Cedar Rapids area; however, it is permissible to complete an internship outside of the area during the summer, or done remotely if authorized by the Internship Faculty Advisor. 

Students interested in internships should consult with their Career Specialist in C3: Creativity, Careers, Community, as well as with the appropriate academic department who will be overseeing the internship experience.

Each internship must include the consent of an Internship Faculty Advisor and completion of the internship request form housed on the College’s online platform for internships.

**XXX-494 Internship in Departmental Area**
Explores a career area related to the sponsoring department. Application is submitted through C3: Creativity, Careers, Community, and supervision is provided by a faculty member in the department. A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisites: Consent of faculty supervisor and Career Services registration.

**XXX-499 Summer Internship in Departmental Area**
Explores a career area related to the sponsoring department. Application is submitted through C3: Creativity, Careers, Community, and supervision is provided by a faculty member in the department. A minimum of 140 hours on-site experience is required. Offered in the Summer Term on P/NP basis only. Prerequisites: Consent of faculty supervisor and Career Services registration. (0.0 course credit)

### RESEARCH

Research is completed during the academic year for 1.0 credit, or during the Summer Term for either 1.0 credit or 0.0 credit determined by the course registration. Research courses may be taken more than once with departmental approval. Departments will determine whether research credits count towards their majors, minors, and concentrations. 

**XXX-454 Research in Departmental Area**
Engages students in a research program designed and directed by a faculty member in the department. A minimum of 140 hours experience is required. P/NP basis only. Prerequisite: Consent of faculty supervisor.

**XXX-459 Summer Research in Departmental Area**
Engages students in a research program designed and directed by a faculty member in the department. A minimum of 140 hours experience is required. Offered in the Summer Term on P/NP basis only. Prerequisite: Consent of faculty supervisor (0.0 course credit)

### New York Term
Carson (Program Director)

New York Term is offered every other Spring Term in odd-numbered years.  There is an extra fee for New York Term. All Coe financial aid applies, and students are eligible to apply for additional financial aid based on the additional costs of the term.

**NYT-250 Fine Arts in New York City**   
Consists of five components: art, film, music, theatre, and dance. Students attend approximately 35 concerts, plays, and dance performances and make frequent visits to museums, galleries, and artists’ studios. Each of these events is accompanied by discussion and seminar sessions with members of the resident New York Term faculty. (Total of 2.0 course credits upon completion of the five components.) 

**NYT-444 Independent Study**   
A plan of study designed by the student in consultation with the student’s faculty advisor, and supervised by the on-campus faculty advisor. Subject must be particularly appropriate for study in New York City. Prerequisite: consent of instructor. (Corequisite: NYT-394 for 1.0 credit.)

**NYT-494 Internship in New York City**
Investigates a student's career interests through work or volunteer experience. The internship is supervised by a faculty member of the relevant department, in consultation with Coe's Center for Creativity and Careers. Normally earns 2.0 credits, but may be taken for 1.0 credits when combined with NYT-444. 

### Occasional Courses

Additional courses, not found in the Catalog, may be offered occasionally and serve one or more of the following purposes: 

1. to provide the opportunity for research, creative, or other scholarly activity for an instructor jointly with interested students; 
2. to explore and develop intellectual pursuits which are attractive to members of the faculty; 
3. to respond to student requests for courses which are distinctive, unusual, or meet specific needs; 
4. to bridge between two or more disciplines or curricular categories; 
5. to serve as one means of developing and testing a possible permanent course. 

The approved occasional courses include, but are not limited to, the courses listed under their respective departments and described as occasional. Additional approved occasional courses exist that are not listed in this catalog.
Students should note that occasional courses do not necessarily count toward a given major or minor.

### Skills Development

**SKD-115 Summer Bridge**
Engages students in a one-week course that takes place prior to Fall Orientation. Students participate in two mini-classes taught by college faculty. Each mini-class is followed by small group discussions regarding course content, learning strategies, college expectations, etc. Additional workshop sessions are held throughout Summer Bridge on topics such as: financial literacy, campus resources, goal setting and academic planning. Summer Bridge also offers opportunities to make social connections through a variety of informal and planned activities. P/NP basis only. Prerequisite: admission to TRIO Student Support Services. (0.3 course credit)

**SKD-120 Concepts of Individualized Learning**
Provides a weekly engagement with an academic coach to identify interests and explore strengths, applying this knowledge to the development of a personal academic plan. Topics include: learning strategies, self-regulation, personal and professional growth, goal setting, campus engagement and self-reflection. P/NP basis only. (0.0 course credit)

**SKD-125 Learning Lab**
Focuses on developing constructive learning habits and techniques to achieve academic pursuits and foster lifelong learning. Units highlight a variety of study strategies, which students experiment with and apply to other courses in which they are concurrently enrolled. Results are presented through written, oral, or graphic reports that encourage collaboration and participation in educational communities. Designed for all levels of learners but may be particularly beneficial for first-year students and sophomores.  P/NP basis only. (0.5 course credit)

**SKD-130 Personal Finance for College Students**
A study of managing finances and making financial decisions that college students encounter. Areas of study for this project-oriented course include student loans, credit cards, savings and investments, cars, living on campus versus apartment living, savings needed for life immediately following graduation, and travel. Prerequisites: Admission to TRIO Student Support Services and consent of instructor. (0.5 course credit)

**SKD-135 Library Research Methods**
Examines how students currently find, evaluate and use information, critically reflecting on how that information is shaped by political, cultural, and social forces. The course covers the following (1) selecting a manageable, research topic; (2) finding relevant background information on chosen topic using legitimate reference sources; (3) using databases: choosing an appropriate database; identifying keywords; effective search strategies; standardized (controlled) vocabulary; (4) evaluating print and electronic sources for impact, credibility, and point of view or bias; (5) understanding peer review and its role in scholarly communication; (6) Google and the free web; (7) YouTube and podcasts; (8) intellectual property and copyright; (9) visual literacy (10) academic integrity and plagiarism.  Appropriate for all students who are interested in improving their research skills. (0.20 credits) (Offered an on occasional basis)

**SKD-145 Strategies for Academic Success**
Connects students to college resources geared to individual academic goals. Through individualized assignments, students investigate and practice academic habits and skills that lead to academic success: time management, identifying and using resources, understanding academic expectations, applying effective study skills, and mastering college technology. Required for students on academic probation. Offered each term. Prerequisite: academic probation or provisional admission. (0.5 course credit)

**SKD-150 Transfer Advisory**
Introduces transfer students to resources across Coe College, including digital tools, C3, Academic Tutoring and Coaching, the Writing Center, the Center for Health and Society, and Health and mental health resources. P/NP basis only. Prerequisite: first-term transfer student status. (0.2 course credit)

**INT-100 Professionalism and Self Presentation**
Introduces students to the fundamentals of job-seeking strategies and professional expectations. Students are guided through development of professional materials, networking techniques, and interviewing skills.  This course does not satisfy Coe’s practicum requirement.

### Washington Term
McNabb (Program Director)

**WSH-284 Topics in Washington, D.C.**
Experiential learning, study, writing, and discussion dealing with various subjects related to the nation’s capital.  Examples of recent and proposed topics include Art and Architecture, Campaigns and Elections, Congressional Relations, and Politics and Communications.

**WSH-286 Topics in Washington, D.C.: Non-Western Perspectives**
Same as Topics in Washington, D.C. (WSH-284) except the course focuses on topics related to non-Western cultures.  Examples of recent and proposed topics include Globalization and the U.S.; and People, Politics and Cultures of the Middle East.  

**WSH-464 Washington Term Internship Seminar**
Group discussion of internship experiences.  Students are exposed to various research methodologies, readings and guest speakers for understanding Washington politics. The goal of the course is to expose students to generalizations about politics and how their internships are either confirming or challenging those generalizations. 

**WSH-494 The Washington Experience**
Internship with an organization related to national or international politics in Washington, D.C., supervised by one of the resident staff of the Washington Term. Students establish learning goals and prepare a portfolio that documents their learning and places it in the larger context of the literature on American or international politics. P/NP basis only. One course credit may be counted toward a major in political science with consent of department, if credit has not already been received for Internship in Political Science (POL-494). (2.0 course credits) 
