project:
  type: book
  output-dir: docs

execute:
  warning: false
  message: false
  output: asis
  freeze: true

book:
  title: "Course Catalog 2026-2027"
  date: "7/13/2026"
  cover-image: 2023 Catalog cover.png
  page-footer: "*Coe College Catalog (2026-2027)*"
  sidebar:
    search: true
    collapse-level: 1
    style: "docked"
    background: rgb(211 144 47)
    border: true
  chapters:
    - index.qmd
    - part: "INTRODUCTORY RESOURCES"
      chapters:
      - catalog_sections/01_mission_rendered.qmd
      - catalog_sections/02_fast_facts_rendered.qmd
    - part: "ACADEMIC RESOURCES"
      chapters:
      - catalog_sections/03_academic_calendar_rendered.qmd
      - catalog_sections/04_education_program_rendered.qmd
    - part: "CAMPUS RESOURCES"    
      chapters:
      - catalog_sections/05_campus_resources_rendered.qmd
      - catalog_sections/06_student_life_rendered.qmd
      - catalog_sections/07_student_services_rendered.qmd
    - part: "COLLEGE REGULATIONS AND POLICIES"  
      chapters:
      - catalog_sections/08_college_regulations_and_policies_rendered.qmd
    - part: "COURSES OF INSTRUCTION"
      chapters:
      - catalog_sections/09_individualized_study.qmd
      - catalog_sections/10_academic_programs.qmd
      - catalog_sections/27_departmental_programs_rendered.qmd
      - catalog_sections/28_reserve_officer_training_corps_rendered.qmd
    - part: "ADMISSIONS"
      chapters:
      - catalog_sections/admission_rendered.qmd
    - part: "FINANCIAL RESOURCES"
      chapters:
      - catalog_sections/29_financial_information_rendered.qmd
      - catalog_sections/30_financial_aid_and_scholarship_rendered.qmd
    - part: "ADDITIONAL RESOURCES"
      chapters:
      - catalog_sections/31_directories_rendered.qmd
      - catalog_sections/32_campus_map.qmd
    #- catalog_sections/references_rendered.qmd

#bibliography: references.bib
#suppress-bibliography: true

toc: true
toc-depth: 2

format:
  html:
    theme: cosmo
    mainfont: "Garamond"
  docx:
    mainfont: "Garamond"
    keep-md: true
    toc: true
  pdf:
    documentclass: scrbook
    keep-tex: true
    template: custom.latex
    include-in-header:
      text: |
              \RedeclareSectionCommand[beforeskip=-2.5ex plus -1ex minus -.2ex,afterskip=0.3ex plus -.2ex]{section}
              \RedeclareSectionCommand[tocnumwidth=3em]{section}
              \usepackage[top=0.5in, left=0.5in, right=0.5in, bottom=1in]{geometry}
              \bibliographystyle{catalog}
              \usepackage{makeidx}
              \makeindex
              \renewcommand\toprule[2]\relax
              \renewcommand\bottomrule[2]\relax
              \usepackage{fancyhdr}
              \lfoot{\textit{Coe College (2022-2023)}}
              \renewcommand{\part}[1]{\addcontentsline{toc}{part}{#1}}
              \newcommand{\pandocbounded}[1]{#1}
              \newcounter{none}
    
    include-after-body: 
      text: |
          \printindex
          
          
