## Art and Visual Studies
Escobedo, Kunau, Morrow, Rogers (Chair)

A major in art or a minor in art, art history, or museum studies provides a foundation in theory and practice. Students focus on making, meaning, and gaining an understanding of visual and contextual history and analysis.  In studying the formal, technical and conceptual aspects of art, students learn to communicate effectively with broad and diverse audiences. 

*An Art major may also complete an Art History minor or a Museum Studies minor, but only two courses may count toward both the major and the minors.*

### Art Major 
A grade of "C" (2.0) or higher must be earned in all courses counted toward a major in art.

1. {{< var c.arh128.long >}}
2. **Two** 100-level ART- courses
3. {{< var c.art206.long >}}
4. **Two** of the following 300-level ART courses:
    - {{< var c.art340.long >}}
    - {{< var c.art345.long >}}
    - {{< var c.art350.long >}}
    - {{< var c.art355.long >}}
    - {{< var c.art360.long >}}
    - {{< var c.art365.long >}}
5. **One** additionl 200-level Art History course
6. {{< var c.arh307.long >}}
7. {{< var c.art464.long >}}
8. {{< var c.art474.long >}}
**NOTE:**  *Scheduling may be planned to allow at least one term of study off-campus at one of the approved foreign or domestic programs. With departmental approval, courses from these programs may count as 100- or 300-level courses.*

Students completing a major in Art may elect also to complete a Multimedia Graphic Design concentration. Courses taken to fulfill requirements in the Multimedia Graphic Design concentration.

To complete the Multimedia Graphic Design concentration, a student must meet the following requirements: 
1.	Completion of a major in Art.
2.	Completion of five additional Multimedia Graphic Design courses.
3.	A cumulative 2.0 GPA must be earned. 
4.	At least three of the five courses must be completed at Coe. 

#### Multimedia Graphic Design Concentration in Art
*Recommended courses in the art major: ART-104 Digital Photography, ART-145 Digital Studio*, ART-350 Advanced Digital Research I and ART-355 Advanced Digital Research II, ARH-270 History of Design*

1.	{{< var c.art363.long >}}
2.	{{< var c.art371.long >}}
3.	{{< var c.art305.long >}}
4.  {{< var c.art306.long >}}
5.	{{< var c.art307.long >}}

### Art Minor 
A grade of "C" (2.0) or higher must be earned in all courses counted toward a minor in art.

1. {{< var c.arh128.long >}}
2. **Two** 100-level ART- courses
3. **Two** of the following 300-level ART- courses
   - {{< var c.art340.long >}}
   - {{< var c.art345.long >}}
   - {{< var c.art350.long >}}
   - {{< var c.art355.long >}}
   - {{< var c.art360.long >}}
   - {{< var c.art365.long >}}
4. **One** 200-level ARH- course 

Further information for all these requirements and programs is available from the Art and Art History Department.


### Courses in Art 

**100-level courses** (*except ART-130, see below*) are open to any student and may offer the opportunity to explore two or more areas of art making in a studio environment.  ART-130 Art in the Elementary Classroom does not satisfy any of the requirements for a major or minor in Art or Art History.  It also does not count as a 100-level art course needed for some courses as a prerequisite.

 **{{< var c.art102.long >}}**  
{{< var c.art102.desc >}}  
 **{{< var c.art103.long >}}**  
{{< var c.art103.desc >}}  
 **{{< var c.art104.long >}}**  
{{< var c.art104.desc >}}  
 **{{< var c.art110.long >}}**  
{{< var c.art110.desc >}}
 **{{< var c.art112.long >}}**  
{{< var c.art112.desc >}}
 **{{< var c.art115.long >}}**  
{{< var c.art115.desc >}}  
 **{{< var c.art125.long >}}**  
{{< var c.art125.desc >}}  
 **{{< var c.art135.long >}}**  
{{< var c.art135.desc >}}  
 **{{< var c.art145.long >}}**  
{{< var c.art145.desc >}}  
 **{{< var c.art150.long >}}**  
{{< var c.art150.desc >}}  
 **{{< var c.art175.long >}}**  
{{< var c.art175.desc >}}  
 **{{< var c.art191.long >}}**  
{{< var c.art191.desc >}}  
 **{{< var c.art206.long >}}**  
{{< var c.art206.desc >}}

**300-level courses** offer students the opportunity to expand their technical and conceptual skills at a more advanced level.

 **{{< var c.art305.long >}}**  
{{< var c.art305.desc >}}
 **{{< var c.art306.long >}}**  
{{< var c.art306.desc >}}
 **{{< var c.art307.long >}}**  
{{< var c.art307.desc >}}
 **{{< var c.art330.long >}}**  
{{< var c.art330.desc >}}
 **{{< var c.art340.long >}}**  
{{< var c.art340.desc >}}
 **{{< var c.art345.long >}}**  
{{< var c.art345.desc >}}
 **{{< var c.art350.long >}}**  
{{< var c.art350.desc >}}
 **{{< var c.art355.long >}}**  
{{< var c.art355.desc >}}
 **{{< var c.art360.long >}}**  
{{< var c.art360.desc >}}
 **{{< var c.art363.long >}}**  
{{< var c.art363.desc >}}
 **{{< var c.art365.long >}}**  
{{< var c.art365.desc >}}
 **{{< var c.art371.long >}}**  
{{< var c.art371.desc >}}
 **{{< var c.art391.long >}}**  
{{< var c.art391.desc >}}
 **{{< var c.art394.long >}}**  
{{< var c.art394.desc >}}
 **{{< var c.art444.long >}}**  
{{< var c.art444.desc >}}
 **{{< var c.art464.long >}}**  
{{< var c.art464.desc >}}
 **{{< var c.art474.long >}}**  
{{< var c.art474.desc >}}
 **{{< var c.art494.long >}}**  
{{< var c.art494.desc >}}

### Art History Minor

A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in art history. An Art History minor may also complete an Art major, Art minor, or Museum studies minor, but only two courses may count toward both the major and the minors.

1.	{{< var c.arh128.long >}}
2.	**Three** additional Art History courses. One must be ARH-200 or above. One may be a course from the following list:
	- {{< var c.ant125.long >}}
	- {{< var c.his318.long >}}
	- {{< var c.com161.long >}}
	- {{< var c.com257.long >}}
	- {{< var c.ms105.long >}}
3.	{{< var c.arh307.long >}}
4.	**One** 100- or 300-level ART- course

### Courses in Art History

 **{{< var c.arh106.long >}}**  
{{< var c.arh106.desc >}}
 **{{< var c.arh107.long >}}**  
{{< var c.arh107.desc >}}
 **{{< var c.arh128.long >}}**  
{{< var c.arh128.desc >}}
 **{{< var c.arh191.long >}}**  
{{< var c.arh191.desc >}}
 **{{< var c.arh201.long >}}**  
{{< var c.arh201.desc >}}
 **{{< var c.arh218.long >}}**  
{{< var c.arh218.desc >}}
 **{{< var c.arh231.long >}}**  
{{< var c.arh231.desc >}}
 **{{< var c.arh248.long >}}**  
{{< var c.arh248.desc >}}
 **{{< var c.arh268.long >}}**  
{{< var c.arh268.desc >}}
 **{{< var c.arh270.long >}}**  
{{< var c.arh270.desc >}}
 **{{< var c.arh296.long >}}**  
{{< var c.arh296.desc >}}
 **{{< var c.arh297.long >}}**  
{{< var c.arh297.desc >}}
 **{{< var c.arh307.long >}}**  
{{< var c.arh307.desc >}}
 **{{< var c.arh391.long >}}**  
{{< var c.arh391.desc >}}
 **{{< var c.arh394.long >}}**  
{{< var c.arh394.desc >}}
 **{{< var c.arh444.long >}}**  
{{< var c.arh444.desc >}}
 **{{< var c.arh494.long >}}**  
{{< var c.arh494.desc >}}
