## Biology

R. Christensen, Cozine, Ellis, Heintzman, Keyes, Leonardo (Administrative Coordinator, Molecular Biology), Leveille, Mitchell, Storer (Chair)

In addition to a major or minor in biology, the department also offers a collateral major in **Neuroscience (see p. 169) along with Concentrations in Environmental and Ecological Science, Molecular Biology, and Pre-Health Sciences**. The biology program provides students with an early introduction to experimental design and use of instrumentation to investigate properties of cells and organisms.  Opportunities to work one-on-one with faculty, in honors and independent study work or in research participation, is also available to students.

### Biology Major

A major in biology requires a minimum cumulative 2.0 GPA over courses counted toward the major.

1. BIO 145/145L Cellular and Molecular Biology and Laboratory (WE)  
2. BIO 155/155L Organismal and Ecological Biology and Laboratory (WE)  
3. BIO 202 Topics in Evolution  
4. BIO 235/235L Genetics and Laboratory  
5. **Four** biology electives with the associated laboratories  
6. CHM 121/121L General Chemistry I and Laboratory  
7. CHM 122/122L General Chemistry II and Laboratory  
8. **One** of the following:  
    - MTH 135 Calculus I (strongly recommended for students considering attending graduate school)  
    - STA 100 Statistical Reasoning I-Foundations **and** STA 110 Stats IIA: Inferential Reasoning  
    - STA 100 Statistical Reasoning I-Foundations **and** STA 130 Stats IIB: Experimental Design  
9. Attendance at research seminars in junior and senior years  

*Strongly recommended:*

>**One** of the following sequences:  

- PHY 165/165L Basic Physics I & Laboratory and PHY 175/175L Basic Physics II & Laboratory
- PHY 185/185L General Physics I & Laboratory and PHY 195/195L General Physics II & Laboratory

With consent of the department chair, other chemistry or mathematics courses may be substituted.

### Concentrations in Biology

Students completing a major in Biology may elect to also complete a concentration of courses within a specific discipline in the major. Courses taken to fulfill requirements in the biology major may be used to also fulfill requirements in an area of concentration. Students may declare only one concentration. 

Concentrations are offered in environmental and ecological science, molecular biology, and pre-health science. To complete a concentration, a student must meet the following requirements: 
1.	Completion of a major in Biology 
2.	Completion of, at most, six additional courses in which a cumulative 2.0 GPA must be earned.  At least three of the additional courses must be completed at Coe.

**Environmental and Ecological Science Concentration**  
1.	CHM 211/211L Analytical Chemistry and Laboratory (WE)  
2.	MTH 135 Calculus I  
3.	**Three** of the following (with two being at the 300 level or higher):  
- BIO 104 Biodiversity  
- +++MISSING INFO: c.bio111_111l.long +++  
- BIO 115 Marine Biology  
- BIO 203 Northwoods Ecology  
- BIO 205/205L General Botany and Laboratory (WE)  
- +++MISSING INFO: c.bio275_275l.long +++  
- BIO 285/285L Animal Behavior and Laboratory  
- BIO 295/295L Spatial Ecology and Laboratory (WE)  
- +++MISSING INFO: c.bio303_303l.long +++  
- +++MISSING INFO: c.bio335_335l.long +++  
- BIO 355/355L Animal Physiology and Laboratory  
- +++MISSING INFO: c.bio365_365l.long +++  
- BIO 385/385L Behavior and Ecology of Vertebrates  
- BIO 425/425L Ecology and Laboratory (WE)  
- BIO 455/455L Molecular Neurobiology and Laboratory  
- BIO 454 Research Participation  

**Molecular Biology Concentration** *  
1.	BIO 345/345L Techniques in Molecular Biology and Laboratory  
2.	CHM 221 Organic Chemistry I  
3.	**Three** of the following:   
- BIO 325/325L Microbiology (WE) and Laboratory  
- BIO 405 Current Topics in Molecular Biology  
- BIO 415/415L Developmental Biology and Laboratory  
- BIO 435/435L Cell Physiology and Laboratory  
- BIO 455/455L Molecular Neurobiology and Laboratory  
- +++MISSING INFO: c.bio465_465l.long +++  
- BIO 454 Research Participation  
- CHM 321 Organic Chemistry II*  
- CHM 431/431L Biochemistry and Laboratory*  
- CHM 432/432L Protein Biochemistry and Laboratory*  

**Pre-Health Sciences Concentration** *  
1.	BIO 375/375L Integrated Human Physiology and Laboratory  
2.	+++MISSING INFO: c.bio315_315l.long +++  
3.	HSS 300 Learn Strategies  Health Profess  
4.	**Three** of the following:   
- BIO 325/325L Microbiology (WE) and Laboratory  
- BIO 415/415L Developmental Biology and Laboratory  
- BIO 435/435L Cell Physiology and Laboratory  
- BIO 455/455L Molecular Neurobiology and Laboratory  
- +++MISSING INFO: c.bio465_465l.long +++  
- CHM 221 Organic Chemistry I*  
- CHM 321 Organic Chemistry II*  
- CHM 431/431L Biochemistry and Laboratory*  
- CHM 432/432L Protein Biochemistry and Laboratory*  
- HSS 494 Health Professions Externship*  

* *Students interested in either the Molecular Biology or the Pre-Health Sciences Concentration are strongly encouraged to meet with a member of the Biology Department faculty for informal advising as soon as they have chosen this concentration. Additional coursework may be needed for those students pursuing admission to a graduate program in Molecular Biology or professional program in the Health Sciences. Check the required courses for admission for each school to which you are interested in applying.*


### Laboratory Study in Biology

Laboratory and field experiences are essential to scientific understanding. They offer an introduction to the processes of science, emphasizing student participation in hypothesis formulation, experimental design, data collection, data analysis, and the composition of papers in a format conventional to science. Biology majors must complete the requisite laboratory courses for the major. Students not majoring in biology should enroll in a laboratory section of any course they plan to apply to the laboratory science requirement in general education. 

### Biology Minor

A minor in biology requires a minimum cumulative GPA of 2.0 over courses counted toward the minor.

1.	BIO 145/145L Cellular and Molecular Biology and Laboratory (WE)  
2.	BIO 155/155L Organismal and Ecological Biology and Laboratory (WE)  
3.	**One** of the following series:  
- **Two** additional biology electives with the associated laboratories (one must be at least a 200-level)  
- **One** additional biology elective with the associated lab **and** BIO 202 Topics in Evolution  
4.	CHM 121/121L General Chemistry I and Laboratory  
5.	CHM 122/122L General Chemistry II and Laboratory  

### Courses in Biology

Studies Homo sapiens applying the same tools biologists use to study other organisms. Topics may include an overview of human evolution, reproduction, genetics, population genetics, adaptations of selected organs and organ systems, humans’ relationship to and impact on their environment, and other contemporary issues in human biology. This course does not satisfy any of the requirements for a major in biology.  
 **BIO 100L Human Biology Lab**  
Three hours per week. Corequisite registration in BIO-100. This course does not satisfy any of the requirements for a major in biology. Nursing majors are not required to take BIO-100L. (0.2 course credit)  
 **BIO 103 Anatomy & Physiology**  
Introduces the student to the structure, function, and organization of the human body. Designed for non-majors as well as students with health-related career interests. Corequisite registration in BIO-103L. This course does not satisfy any of the requirements for a major in biology or nursing.  
 **BIO 103L Anatomy and Physiology Lab**  
Three hours per week. Corequisite registration in BIO-103. This course does not satisfy any of the requirements for a major in biology or nursing. (0.2 course credit)  
 **BIO105 Introductory Biology**  
nan  
 **BIO 111 Urban Ecology**  
Introduces the ecology of urban systems, investigating how humans and their built environments interact with and form ecosystems. Two main points of view will be represented: the city as an ecological system, and the responses and adaptations of organisms to this ecosystem. We will also investigate how humans respond to and interact with this biotic and abiotic environment. Labs will visit relevant areas of Cedar Rapids. One three hour workshop and one four-hour lab per week. (Offered alternate years.)  
 **BIO 111L Urban Ecology Lab**  
Three hours per week. Labs will visit relevant areas of Cedar Rapids. Corequisite with Urban Ecology (BIO 111). (0.2 course credit).  
 **BIO 115 Marine Biology**  
Surveys marine organisms and communities with emphasis on tropical systems. In class components focus on an introduction to marine biology, oceanography, and taxonomy, while the primary field analyses focus on the dynamics of coral reefs, mangroves, and turtle grass meadows. An off-campus course taught at an appropriate site and involving extensive field work. Includes lecture and laboratory. Prerequisite: consent of instructor. (Offered May Experiential Term only)  
 **BIO 120 Biology, Health, & Society**  
Introduces the basic principles, terms, and technologies needed to understand the role of biology in our lives. This course centers around answering questions in healthcare and in contemporary society, using the application of biological knowledge. Study skills for mastering college biology are also taught. Three lectures and one co-curricular skills workshop per week. Counts as a non-lab science course. This course does not satisfy any of the requirements for a major in biology.  
 **BIO 145 Cellular & Molecular Biology**  
Studies biology at the cellular and molecular level, including structure and function of cell components, metabolism and energy, and Mendelian genetics. Three lectures per week.  
 **BIO 145L Cellular and Molecular Biology Lab**  
Introduces students to common biological techniques including enzyme assays and DNA studies. Students are also introduced to experimental design, collection of data, and statistical analysis of data. Instruction in writing of scientific papers is also provided. Three hours per week. Concurrent or previous registration in Cellular and Molecular Biology (BIO-145). Nursing majors are not required to take BIO-145L. (0.2 course credit)  
 **BIO 155 Organismal & Ecological Biology**  
Studies tissues, organ systems, and reproduction in animals with an emphasis on human biology. Principles of ecology, environmental science and animal behavior are also studied. Three lectures per week.  
 **BIO 155L Organismal & Ecological Biology Lab**  
Introduces dissection, field biology, and selected statistical analysis of data. Instruction in writing of scientific papers is also provided. Three hours per week. Concurrent or previous registration in Organismal and Ecological Biology (BIO-155). (0.2 course credit)  
 **BIO 165 Introduction to Ornithology**  
Introduces the behavior, ecology and biology of birds, emphasizing identification of local species and such species’ adaptations to their biotic and abiotic environments. Binoculars furnished. This course satisfies the lab science course requirement. Credit is given for Introduction to Ornithology (BIO-165) or Advanced Topics in Ornithology (BIO-303), not both. Offered Spring Term on campus and Summer at the Wilderness Field Station. (This course does not satisfy the requirements for a major in biology.)  
 **BIO 165L Introduction to Ornithology LAB**  
Four hours per week. Corequisite with Introduction to Ornithology (BIO-165). (0.3 course credit)  
 **BIO 175 Field Botany**  
Investigates tree and wildflower species encountered in Iowa’s forests, fields and prairies. Emphasizes hands-on description of structural characteristics, identification of species using a dichotomous key and characteristics of flowering plant families. A basic understanding of the distribution of plants within communities is also developed. A collection of local plants is required. (Offered in May Experiential Term)  
 **BIO 185 Entomology**  
Introduces the biology of insects and related arthropods, focusing on how homeostatic problems common to all organisms have been solved. Topics include physiology, morphology, systematics, and the relationship among insects, plants, and humans.  
 **BIO 185L Entomology Lab**   
Three hours per week. Consists of both in-class study as well as field trips emphasizing the ecology and behavior of local forms. A representative insect collection is made. Corequisite registration in BIO-185. (0.2 course credit)  
 **BIO 195 Introduction to Microbiology**  
Studies elementary level principles of microbiology. Special attention is given to the medical aspect of the subject. Three lectures per week. Designed for students with allied health career interests. This course does not satisfy any of the requirements for a major in biology. Prerequisite: Human Biology (BIO-100) or Cellular and Molecular Biology (BIO-145).  
 **BIO 195L Introduction to Microbiology Lab**  
Three hours per week. Corequisite registration in BIO-195. (0.2 course credit)  
 **BIO 202 Topics in Evolution**  
Investigates selective and non-selective evolutionary mechanisms operating on populations, especially as they affect adaptation, speciation, and extinction. Selected aspects of the fossil record and current theories of hominid evolution may also be part of the course. Instruction in presentation of scientific papers is also provided. Counts as a non-lab science course. Prerequisites: Cellular and Molecular Biology (BIO-145).  
 **BIO 205 General Botany**  
Explores the biology of plants at the cellular, tissue and whole plant levels. The influence of environment on metabolism, growth, development and reproduction are themes. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), and Organismal and Ecological Biology (BIO-155)  
 **BIO 205L General Botany Laboratory**  
Provides the opportunity for hands-on observations of plant cells, tissues and whole plants, flowers and fruits and to perform experiments related to basic principles of plant biology introduced in lecture. Instruction in library database searches and writing annotated scientific reports is provided. Three hours per week. Concurrent or previous registration in General Botany (BIO-205). (0.2 course credit)  
 **BIO 215 Human Anatomy**  
Surveys microscopic and gross human anatomy, providing necessary background for students in physiology and body mechanics. Three lectures per week. Prerequisites: Human Biology (BIO-100) or Cellular and Molecular Biology (BIO-145) or Organismal and Ecological Biology (BIO-155). This course does not satisfy any of the requirements for a major in biology. Credit is given for Human Anatomy (BIO-215) or Integrated Human Anatomy (BIO-315), not both. Concurrent registration in Human Anatomy Laboratory (BIO-215L).  
 **BIO 215L Human Anatomy Laboratory**  
Unites the physical structures with written material to help students conceptualize the intricacies of the human body. Three hours per week. Concurrent registration in Human Anatomy (BIO-215). (0.2 course credit)  
 **BIO 225 Human Physiology**  
Studies the various systems of the human body, including the application of physiological principles to the health professions. Three lectures per week. This course does not satisfy any of the requirements for a major in biology. Prerequisites: Human Anatomy (BIO-215) and either Human Biology (BIO-100), Cellular and Molecular Biology (BIO-145), or Organismal and Ecological Biology (BIO-155).  
 **BIO 235 Genetics**  
Explores the three main branches of heredity: transmission (classical), molecular, and population genetics. Transmission genetics examines probabilities and pedigrees of genetic traits passed from generation to generation. Molecular genetics probes the structure, function, and regulation of genes. Population genetics investigates through mathematical models the distribution and behavior of genes in populations. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), and Organismal and Ecological Biology (BIO-155).  
 **BIO 235L Genetics Laboratory**  
Three hours per week. Concurrent with Genetics (BIO-235). (0.2 course credit)  
 **BIO 275 Aquatic Ecology**  
Study of the biota of lakes and streams in northern Minnesota and adjacent Ontario, and their abiotic environment. Extensive field sampling enables students to study predation, diel vertical migration, stream drift, induced morphological defenses, and food-web interactions. Regional and North American lake and stream biodiversity and the effects of introduced species and human intervention on aquatic ecosystems are reviewed. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), or Organismal and Ecological Biology Laboratory (BIO155/-155L). (Offered summers at the Wilderness Field Station)  
 **BIO 275L Aquatic Ecology Lab**  
Field work at the Wilderness Field Station. Corequisite with Aquatic Ecology (BIO-275). (0.2 course credit)  
 **BIO 285 Animal Behavior**  
Considers principles and methods in ethology with emphasis on temporal and spatial patterns, adaptive significances, communication, aggression and territoriality, social organization, and the nature of regulatory mechanisms. Prerequisites: One of the following: Cellular and Molecular Biology and Laboratory (BIO-145/-145L); Organismal and Ecological Biology and Laboratory (BIO-155/-155L); or Statistical Methods and Data Analysis (PSY-300). (Offered summers at the Wilderness Field Station)  
 **BIO 285L Animal Behavior Laboratory**  
Field work at the Wilderness Field Station. Three hours per week. Corequisite registration with Animal Behavior (BIO-285). (0.2 course credit)  
 **BIO 295 Spatial Ecology**  
Investigates spatial patterns of organisms in natural, agricultural, and urban landscapes. Emphasis is on how the arrangements of organisms both reflect and feedback on underlying resources and geography. Students learn how to capture spatial characteristics of individuals, populations, species, communities, and landscapes sampled in the field, integrate them with satellite imagery, and analyze them statistically. Use of global positioning system hardware to provide spatial reference for field ecology surveys and use of ArcView as a data management, display, and analysis tool are important features of the course. Three lectures per week. Prerequisites: Organismal and Ecological Biology and Laboratory (BIO-155/-155L).  
 **BIO 295L Spatial Ecology Laboratory**  
Four hours per week. Corequisite registration with Spatial Ecology (BIO-295). (0.3 course credit)  
 **BIO 315 Integrated Human Anatomy**  
Integrates macroscopic human anatomy at the organ and organ system levels with microscopic study of histology and development from a clinical perspective. Three lectures per week. Prerequisites: Organismal and Ecological Biology and Laboratory (BIO-155/155L). Credit is given for Integrated Human Anatomy (BIO-315) or Human Anatomy (BIO-215), not both.  
 **BIO 315L Integrated Human Anatomy Lab**  
Studies human anatomy using dissection, models, histological slides, and cadaveric specimens. Students learn to integrate written, verbal and visual material to master anatomical and histological terminology. Three hours per week. Concurrent or previous registration in Integrated Human Anatomy (BIO-315). (0.2 course credit)  
 **BIO 325 Microbiology**  
Studies major fields of microbiology with emphasis on bacteria and viruses. Topics include bacterial cell structure, genetics, and pathogenesis as well as immunology and epidemiology. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), Organismal and Ecological Biology (BIO-155), Organic Chemistry I (CHM-221) and Organic Laboratory (CHM-322) or Genetics (BIO-235).  
 **BIO 325L Microbiology Lab**  
Four hours per week. Concurrent with Microbiology (BIO-325). (0.2 course credit)  
 **BIO 335 Conservation and Ecology of Mammals**  
Studies mammals of Minnesota and the natural history, form/function relations, behavior, distributions, and interaction with their environment and other organisms. Investigation of how these variables impact conservation. Class activities include direct observations, reading tracks and “sign.” Live-trap mark and recapture studies supplemented by readings, lectures, and discussions. (Offered summers at the Wilderness Field Station)  
 **BIO 335L Conserv & Ecology of Mammals LAB**  
Field work at the Wilderness Field Station. Corequisite registration with Conservation and Ecology of Mammals (BIO 335). (0.2 course credit)  
 **BIO 345 Techniques in Molecular Biology**  
Introduces students to biological molecular techniques. Methods include RNA, DNA and protein expression analysis and cell culture techniques. On completing the course, students should have a working knowledge of most methods used in molecular biology research. Two sessions per week. Prerequisites: Genetics and Laboratory (BIO-235/-235L), and General Chemistry II and Laboratory (CHM-122/-122L).  
 **BIO 345L Techniques in Molecular Biology Lab**  
Six hours per week. Concurrent with Techniques in Molecular Biology (BIO-345). (0.5 course credit)  
 **BIO 355 Animal Physiology**  
Studies how organ systems in animal species solve the fundamental problems of staying alive. This includes how to obtain energy, how to procure the raw materials necessary for constructing their bodies, how to gain oxygen from the environment, how to get rid of unneeded substances and toxic materials. The course addresses how these ends are achieved through the cooperation of cells, tissues, organs, and organ systems in a variety of organisms including mammals, birds, reptiles, amphibians, and fish as well as selected invertebrates. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Biology Laboratory (BIO-145/-145L), and Organismal and Ecological Biology (BIO-155).  
 **BIO 355L Animal Physiology Lab**  
Three hours per week concurrent with Animal Physiology (BIO-355). (0.2 course credit)  
 **BIO 365 Comparative Chordate Anat**  
Surveys the chordates and the development and evolution of form in vertebrates, using primarily the shark, mudpuppy, and cat in laboratory. Two lectures, one discussion recitation per week. Prerequisite: Cellular and Molecular Biology (BIO-145), Organismal and Ecological Biology (BIO-155) and Topics in Evolution (BIO-202.  
 **BIO 365L Comp Chordate Anat Lab**  
Four hours per week. Corequisite registration with Comparative Chordate Anatomy (BIO-365). (0.2 course credit)  
 **BIO 375 Integrated Human Physiology**  
Studies physiologic functions in terms of basic physical and chemical processes; an introduction to the principles of physiology using the human organism as a model. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), and Organismal and Ecological Biology (BIO-155).  
 **BIO 375L Integrated Human Physiology Lab**  
Three hours per week. Concurrent with Integrated Human Physiology (BIO-375). (0.2 course credit)  
 **BIO 385 Behavior/Ecology of Vertebrates**  
Explores the identification, evolutionary history, and behavioral and ecological relationships of local mammals, birds, reptiles, amphibians, and fish. Students learn and apply survey techniques appropriate for particular groups to understand species/habitat relationships, diversity within groups, and the impact of humans on diversity. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145) and Topics in Evolution (BIO-202).  
 **BIO 385L Behavior/Ecology Vertebrates Lab**  
Three hours per week. Concurrent with Behavior and Ecology of Vertebrates (BIO-385). (0.2 course credit)  
 **BIO 405 Current Topics in Molecular Biology**  
Explores primary literature in the field of molecular biology, focusing on recent advances in DNA, RNA and protein manipulation, characterization, and control. Students read research articles, critically evaluate published data, and communicate technical information in several forms. Three lectures per week. Prerequisites: Techniques in Molecular Biology (BIO-345).  
 **BIO 415 Developmental Biology**  
Explores the developmental processes and changes that occur as an organism grows from fertilized egg to adult organism. The actions and interactions of cells and tissues are examined in the living, growing, and rapidly changing environment of the body. Classical embryology is examined through modern genetic techniques, with special emphasis on how differential gene expression makes us who we are. Survey of research methodologies are a prominent topic. Three lectures per week. Prerequisites: Genetics and Laboratory (BIO-235/-235L).  
 **BIO 415L Developmental Biology lab**  
Three hours per week. Concurrent with Developmental Biology (BIO-415). (0.2 course credit)  
 **BIO 425 Ecology**  
Studies the interrelationship among organisms and their environments. The structure and dynamics of populations, communities, and ecosystems are examined through lectures and laboratory or field investigations. Three lectures per week. Prerequisites: General Botany (BIO-205) or consent of instructor.  
 **BIO 425L Ecology Lab**  
Three hours per week. Concurrent with Ecology (BIO-425). (0.2 course credit)  
 **BIO 435 Cell Physiology**  
Studies the content, organization, and function of the cell and its components. Other topics include the relationship of the cell to its environment, the cell membrane, enzymes, conversion of matter and energy, cell growth, and cell division. Three lectures per week. Prerequisites: Genetics and Laboratory (BIO-235/-235L), and General Chemistry II and Laboratory (CHM-122/-122L).  
 **BIO 435L Cell Physiology Lab**  
Three hours per week. Concurrent with Cell Physiology (BIO-435). (0.2 course credit)  
 **BIO 444 Independent Study**  
Offers students the opportunity to do independent work on a selected project under direction of a member of the department. May be taken more than once for a maximum of 2.0 credits. Prerequisites: Courses providing appropriate background for the project selected and consent of department chair.  
 **BIO 445 Environmental Microbiology**  
Examines the role of microbes in the environment. Topics include microbial diversity, nutrient cycling including biogeochemistry, bioremediation, and biodegradation. The use of molecular methods and microscopy to study microbes in situ are special emphases of the course. Three lectures per week. Prerequisites: Cellular and Molecular Biology and Laboratory (BIO-145/-145L), Organismal and Ecological Biology (BIO-155), Organic Chemistry I (CHM-221) with Organic Laboratory (CHM-322) or Genetics (BIO-235).  
 **BIO 445L Env Microbiology Lab**  
Application of theory through developing the technical skills necessary to conduct experiments in modern microbial ecology. Students learn how to select a proper sampling site, collect samples without contamination, and the process of both molecular and culture-based techniques used to study microorganisms from their natural environment. Six hours per week. Corequisite registration with Environmental Microbiology (BIO-445). (0.5 course credit)  
 **BIO 454 Research Participation**  
Engages students in a research program designed and directed by a biology department faculty member, including some or all of the following: library research, research design, and field or laboratory investigations. Scheduled by arrangement with sponsoring professor with a time requirement of 10 hours per week minimum per course credit. P/NP basis only. May be taken for an X status grade with consent of instructor prior to registration. May be taken more than once for credit for a maximum of 2.0 credits. Research participation credit does not satisfy any of the requirements for a major in biology. (0.2–1.0 course credit)  
 **BIO 455 Molecular Neurobiology**  
Studies the organization and function of the nervous system, focusing on both cellular physiology and functional neuroanatomy. Topics include the cellular and molecular properties of brain cells, the neurological basis of behavior, and disorders of the nervous system. Three lectures per week. Prerequisites: Organismal and Ecological Biology and Laboratory (BIO-155/-155L), and Genetics and Laboratory (BIO-235/-235L).  
 **BIO 455L Molecular Neurobiology Lab**  
Develops technical skills needed to conduct experiments in modern neurobiology. Students learn how to perform laboratory techniques that look at gene expression and cellular function and acquire an understanding of the process and rationale behind the methods used in neurobiology research. Three hours per week. Corequisite registration with Molecular Neurobiology (BIO-455). (0.2 course credit)  
 **BIO 462/463 Advanced Biology Laboratory I and II**  
Offers an extensive independent or group investigations of a particular topic in biology. Designed to be a research experience in preparation for teaching, graduate school or direct entry into a technical field after graduation. Advanced Biology Laboratory I (BIO-462) may be repeated as Advanced Biology Laboratory II (BIO-463). P/NP basis only. Prerequisites: Genetics and Laboratory (BIO-235/-235L), and consent of instructor. (Offered May Term only)  
 **BIO 465 Immunology**  
An integrated series of lectures designed to familiarize students with cellular, molecular and biochemical aspects of the development of the immune system and the immune response, including B-and T-cell function, antibody structure and function, complement, and major histocompatibility complex formation, with special emphasis on the integration of these parts during the response to infectious agents. Special topics include immunomodulation, vaccination, autoimmunity, and neuro-immune interactions. The laboratory component utilizes existing instrumentation in the biology department and cell culture to explore different aspects of the immune system. Three lectures and one three hour laboratory period per week. Prerequisites: General Chemistry II (CHM 122/122L), Genetics (BIO-235), and Integrated Human Physiology (BIO-375) (or concurrent enrollment in BIO-375).  
 **BIO 465L Immunology Laboratory**  
Three hours per week. Corequisite registration with Immunology (BIO-465). (0.2 course credit)  
 **BIO 494 Internship in Biology**  
Investigates an area of interest through voluntary field placement supervised by a faculty member of the department. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major in biology. Prerequisites: declared major in biology, junior standing, and consent of department chair.  

 **OCC 365 Oak Ridge Science Semester**  
See @sec-ACM-and-international-programs

 **HSS 494 Health Professions Externship**  
Offers an intense exploration in the fields of human or animal healthcare, allied health, or auxiliary fields within the healthcare system. Students are placed at local sites and/or in nearby communities with one or more professionals in fields related to the student’s interests. A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisites: junior or senior standing, submission of application in Fall term, and consent of instructor. (Offered May Experiential Term only)

