## Biology

R. Christensen, Cozine, Ellis, Heintzman, Keyes, Leonardo (Administrative Coordinator, Molecular Biology), Leveille, Mitchell, Storer (Chair)

In addition to a major or minor in biology, the department also offers a collateral major in **Neuroscience (see p. 169) along with Concentrations in Environmental and Ecological Science, Molecular Biology, and Pre-Health Sciences**. The biology program provides students with an early introduction to experimental design and use of instrumentation to investigate properties of cells and organisms.  Opportunities to work one-on-one with faculty, in honors and independent study work or in research participation, is also available to students.

### Biology Major

A major in biology requires a minimum cumulative 2.0 GPA over courses counted toward the major.

1. {{< var c.bio145_145l.long >}}  
2. {{< var c.bio155_155l.long >}}  
3. {{< var c.bio202.long >}}  
4. {{< var c.bio235_235l.long >}}  
5. **Four** biology electives with the associated laboratories  
6. {{< var c.chm121_121l.long >}}  
7. {{< var c.chm122_122l.long >}}  
8. **One** of the following:  
    - {{< var c.mth135.long >}} (strongly recommended for students considering attending graduate school)  
    - {{< var c.sta100.long >}} **and** {{< var c.sta110.long >}}  
    - {{< var c.sta100.long >}} **and** {{< var c.sta130.long >}}  
9. Attendance at research seminars in junior and senior years  

*Strongly recommended:*

>**One** of the following sequences:  

- {{< var c.phy165_165l.long >}} and {{< var c.phy175_175l.long >}}
- {{< var c.phy185_185l.long >}} and {{< var c.phy195_195l.long >}}

With consent of the department chair, other chemistry or mathematics courses may be substituted.

### Concentrations in Biology

Students completing a major in Biology may elect to also complete a concentration of courses within a specific discipline in the major. Courses taken to fulfill requirements in the biology major may be used to also fulfill requirements in an area of concentration. Students may declare only one concentration. 

Concentrations are offered in environmental and ecological science, molecular biology, and pre-health science. To complete a concentration, a student must meet the following requirements: 
1.	Completion of a major in Biology 
2.	Completion of, at most, six additional courses in which a cumulative 2.0 GPA must be earned.  At least three of the additional courses must be completed at Coe.

**Environmental and Ecological Science Concentration**  
1.	{{< var c.chm211_211l.long >}}  
2.	{{< var c.mth135.long >}}  
3.	**Three** of the following (with two being at the 300 level or higher):  
- {{< var c.bio104.long >}}  
- {{< var c.bio111_111l.long >}}  
- {{< var c.bio115.long >}}  
- {{< var c.bio203.long >}}  
- {{< var c.bio205_205l.long >}}  
- {{< var c.bio275_275l.long >}}  
- {{< var c.bio285_285l.long >}}  
- {{< var c.bio295_295l.long >}}  
- {{< var c.bio303_303l.long >}}  
- {{< var c.bio335_335l.long >}}  
- {{< var c.bio355_355l.long >}}  
- {{< var c.bio365_365l.long >}}  
- {{< var c.bio385_385l.long >}}  
- {{< var c.bio425_425l.long >}}  
- {{< var c.bio455_455l.long >}}  
- {{< var c.bio454.long >}}  

**Molecular Biology Concentration** *  
1.	{{< var c.bio345_345l.long >}}  
2.	{{< var c.chm221.long >}}  
3.	**Three** of the following:   
- {{< var c.bio325_325l.long >}}  
- {{< var c.bio405.long >}}  
- {{< var c.bio415_415l.long >}}  
- {{< var c.bio435_435l.long >}}  
- {{< var c.bio455_455l.long >}}  
- {{< var c.bio465_465l.long >}}  
- {{< var c.bio454.long >}}  
- {{< var c.chm321.long >}}*  
- {{< var c.chm431_431l.long >}}*  
- {{< var c.chm432_432l.long >}}*  

**Pre-Health Sciences Concentration** *  
1.	{{< var c.bio375_375l.long >}}  
2.	{{< var c.bio315_315l.long >}}  
3.	{{< var c.hss300.long >}}  
4.	**Three** of the following:   
- {{< var c.bio325_325l.long >}}  
- {{< var c.bio415_415l.long >}}  
- {{< var c.bio435_435l.long >}}  
- {{< var c.bio455_455l.long >}}  
- {{< var c.bio465_465l.long >}}  
- {{< var c.chm221.long >}}*  
- {{< var c.chm321.long >}}*  
- {{< var c.chm431_431l.long >}}*  
- {{< var c.chm432_432l.long >}}*  
- {{< var c.hss494.long >}}*  

* *Students interested in either the Molecular Biology or the Pre-Health Sciences Concentration are strongly encouraged to meet with a member of the Biology Department faculty for informal advising as soon as they have chosen this concentration. Additional coursework may be needed for those students pursuing admission to a graduate program in Molecular Biology or professional program in the Health Sciences. Check the required courses for admission for each school to which you are interested in applying.*


### Laboratory Study in Biology

Laboratory and field experiences are essential to scientific understanding. They offer an introduction to the processes of science, emphasizing student participation in hypothesis formulation, experimental design, data collection, data analysis, and the composition of papers in a format conventional to science. Biology majors must complete the requisite laboratory courses for the major. Students not majoring in biology should enroll in a laboratory section of any course they plan to apply to the laboratory science requirement in general education. 

### Biology Minor

A minor in biology requires a minimum cumulative GPA of 2.0 over courses counted toward the minor.

1.	{{< var c.bio145_145l.long >}}  
2.	{{< var c.bio155_155l.long >}}  
3.	**One** of the following series:  
- **Two** additional biology electives with the associated laboratories (one must be at least a 200-level)  
- **One** additional biology elective with the associated lab **and** {{< var c.bio202.long >}}  
4.	{{< var c.chm121_121l.long >}}  
5.	{{< var c.chm122_122l.long >}}  

### Courses in Biology

 **{{< var c.bio100.long >}}**  
{{< var c.bio100.desc >}}  
 **{{< var c.bio100l.long >}}**  
{{< var c.bio100l.desc >}}  
 **{{< var c.bio103.long >}}**  
{{< var c.bio103.desc >}}  
 **{{< var c.bio103l.long >}}**  
{{< var c.bio103l.desc >}}  
 **{{< var c.bio104.long >}}**  
{{< var c.bio104.desc >}}  
 **{{< var c.bio105.long >}}**  
{{< var c.bio105.desc >}}  
 **{{< var c.bio111.long >}}**  
{{< var c.bio111.desc >}}  
 **{{< var c.bio111l.long >}}**  
{{< var c.bio111l.desc >}}  
 **{{< var c.bio115.long >}}**  
{{< var c.bio115.desc >}}  
 **{{< var c.bio120.long >}}**  
{{< var c.bio120.desc >}}  
 **{{< var c.bio145.long >}}**  
{{< var c.bio145.desc >}}  
 **{{< var c.bio145l.long >}}**  
{{< var c.bio145l.desc >}}  
 **{{< var c.bio155.long >}}**  
{{< var c.bio155.desc >}}  
 **{{< var c.bio155l.long >}}**  
{{< var c.bio155l.desc >}}  
 **{{< var c.bio165.long >}}**  
{{< var c.bio165.desc >}}  
 **{{< var c.bio165l.long >}}**  
{{< var c.bio165l.desc >}}  
 **{{< var c.bio175.long >}}**  
{{< var c.bio175.desc >}}  
 **{{< var c.bio185.long >}}**  
{{< var c.bio185.desc >}}  
 **{{< var c.bio185l.long >}}**   
{{< var c.bio185l.desc >}}  
 **{{< var c.bio195.long >}}**  
{{< var c.bio195.desc >}}  
 **{{< var c.bio195l.long >}}**  
{{< var c.bio195l.desc >}}  
 **{{< var c.bio202.long >}}**  
{{< var c.bio202.desc >}}  
 **{{< var c.bio203.long >}}**  
{{< var c.bio203.desc >}}  
 **{{< var c.bio205.long >}}**  
{{< var c.bio205.desc >}}  
 **{{< var c.bio205l.long >}}**  
{{< var c.bio205l.desc >}}  
 **{{< var c.bio215.long >}}**  
{{< var c.bio215.desc >}}  
 **{{< var c.bio215l.long >}}**  
{{< var c.bio215l.desc >}}  
 **{{< var c.bio225.long >}}**  
{{< var c.bio225.desc >}}  
 **{{< var c.bio235.long >}}**  
{{< var c.bio235.desc >}}  
 **{{< var c.bio235l.long >}}**  
{{< var c.bio235l.desc >}}  
 **{{< var c.bio275.long >}}**  
{{< var c.bio275.desc >}}  
 **{{< var c.bio275l.long >}}**  
{{< var c.bio275l.desc >}}  
 **{{< var c.bio285.long >}}**  
{{< var c.bio285.desc >}}  
 **{{< var c.bio285l.long >}}**  
{{< var c.bio285l.desc >}}  
 **{{< var c.bio295.long >}}**  
{{< var c.bio295.desc >}}  
 **{{< var c.bio295l.long >}}**  
{{< var c.bio295l.desc >}}  
 **{{< var c.bio303.long >}}**  
{{< var c.bio303.desc >}}  
 **{{< var c.bio303l.long >}}**  
{{< var c.bio303l.desc >}}  
 **{{< var c.bio315.long >}}**  
{{< var c.bio315.desc >}}  
 **{{< var c.bio315l.long >}}**  
{{< var c.bio315l.desc >}}  
 **{{< var c.bio325.long >}}**  
{{< var c.bio325.desc >}}  
 **{{< var c.bio325l.long >}}**  
{{< var c.bio325l.desc >}}  
 **{{< var c.bio335.long >}}**  
{{< var c.bio335.desc >}}  
 **{{< var c.bio335l.long >}}**  
{{< var c.bio335l.desc >}}  
 **{{< var c.bio345.long >}}**  
{{< var c.bio345.desc >}}  
 **{{< var c.bio345l.long >}}**  
{{< var c.bio345l.desc >}}  
 **{{< var c.bio355.long >}}**  
{{< var c.bio355.desc >}}  
 **{{< var c.bio355l.long >}}**  
{{< var c.bio355l.desc >}}  
 **{{< var c.bio365.long >}}**  
{{< var c.bio365.desc >}}  
 **{{< var c.bio365l.long >}}**  
{{< var c.bio365l.desc >}}  
 **{{< var c.bio375.long >}}**  
{{< var c.bio375.desc >}}  
 **{{< var c.bio375l.long >}}**  
{{< var c.bio375l.desc >}}  
 **{{< var c.bio385.long >}}**  
{{< var c.bio385.desc >}}  
 **{{< var c.bio385l.long >}}**  
{{< var c.bio385l.desc >}}  
 **{{< var c.bio405.long >}}**  
{{< var c.bio405.desc >}}  
 **{{< var c.bio415.long >}}**  
{{< var c.bio415.desc >}}  
 **{{< var c.bio415l.long >}}**  
{{< var c.bio415l.desc >}}  
 **{{< var c.bio425.long >}}**  
{{< var c.bio425.desc >}}  
 **{{< var c.bio425l.long >}}**  
{{< var c.bio425l.desc >}}  
 **{{< var c.bio435.long >}}**  
{{< var c.bio435.desc >}}  
 **{{< var c.bio435l.long >}}**  
{{< var c.bio435l.desc >}}  
 **{{< var c.bio444.long >}}**  
{{< var c.bio444.desc >}}  
 **{{< var c.bio445.long >}}**  
{{< var c.bio445.desc >}}  
 **{{< var c.bio445l.long >}}**  
{{< var c.bio445l.desc >}}  
 **{{< var c.bio454.long >}}**  
{{< var c.bio454.desc >}}  
 **{{< var c.bio455.long >}}**  
{{< var c.bio455.desc >}}  
 **{{< var c.bio455l.long >}}**  
{{< var c.bio455l.desc >}}  
 **{{< var c.bio462_463.long >}}**  
{{< var c.bio462_463.desc >}}  
 **{{< var c.bio465.long >}}**  
{{< var c.bio465.desc >}}  
 **{{< var c.bio465l.long >}}**  
{{< var c.bio465l.desc >}}  
 **{{< var c.bio494.long >}}**  
{{< var c.bio494.desc >}}  
