## Business Administration and Economics
Baranowski, Calman, Carstens (Administrative Coordinator, Aviation Studies & Flight Operations), Chen, J. Christensen, Eichhorn (Co-Chair), Hayes, Kuennen (Co-Chair), Lensing, Lutz, Melcher, Nguyen, Perry, Westberg

The Stead Department of Business Administration and Economics offers majors in **ACCOUNTING, BUSINESS ADMINISTRATION, ECONOMICS, and INTERNATIONAL ECONOMICS,** and minors in economics and international economics. Students pursuing one or more of these are strongly encouraged to consult with departmental faculty to develop specific plans of study. 

### Business Administration
The study of business administration is designed to develop in its students a high degree of competence in the application of business theories and sound judgment to the solution of business operating problems. Graduates are able to contribute effectively to the activities of their organizations by applying business skills required to plan, analyze, and control company activities. Beyond enhancing the value of a firm, the graduate should have a firm knowledge from which to achieve professional growth in the workplace and/or graduate school. The business major is designed to prepare students in the core areas of business administration, with specific focus on management, finance, and marketing. Students are also provided the opportunity to specialize in a particular area through selection of elective courses. 

### Business Administration Major  

A major in business administration requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. ACC 171 Principles of Accounting I
2. ECO 175 Principles of Macroeconomics
3. BUS 190 Statistical Analysis
4. ACC 215 Principles of Accounting II
5. ECO 215 Prin Microeconomics
6. BUS 315 Business Law I
7. **One** of the following Management courses:    
   BUS 250 Principles of Management  
   BUS 300 Human Resource Management  
   BUS 387 Adv Top:Human Res Mgt  
   BUS 470 Strategic Management    
8. **One** of the following Marketing courses:   
   BUS 330 Principles of Marketing  
   BUS 460 Advertising  
   BUS 465 Advanced Topics in Marketing  
   BUS 467 Consumer Behavior  
9. **One** of the following Finance courses
   ECO 225 Money & Banking  
   BUS 350 Principles of Finance  
   BUS 352 Corporate Finance  
   BUS 495 Investment Analysis   
10. **Two** additional business courses numbered 200 or above

Students planning to attend graduate school in business are strongly encouraged to take calculus, additional statistics courses, intermediate level macro/microeconomics, quantitative management courses, and strategic management. Students should also discuss their graduate school plans with a member of the department to determine other courses that may be expected for admission to specific graduate programs. 

### Concentrations in Business

Students completing a major in Business Administration may elect to also complete a concentration of courses within a specific discipline in the major. Courses taken to fulfill requirements in the business major may be used to also fulfill requirements in an area of concentration. Students may declare only one concentration.  

Concentrations are offered in aviation studies; flight operations; finance; international business; management; marketing; risk management/insurance; healthcare administration; supply chain management; and sports management. To complete a concentration, a student must meet the following requirements:
1.	Completion of a major in Business Administration
2.	Completion of **five** additional courses in which a cumulative 2.0 GPA must be earned.  At least three of the five courses must be completed at Coe.

#### Aviation Studies Concentration in Business  
**(This concentration is intended for Coe students who do not plan to complete the flight operations courses.)**

1.	AVS 101 Introduction to Aviation
2.	AVS 201/201L Principles of Meteorology and Laboratory
3.	AVS 301 Applied Aerodynamics
4.	AVS 302 Human Factors
5. AVS 401 Aviation Seminar

#### Flight Operations Concentration in Business  
**(This concentration is intended for only those Coe students who have been admitted into Coe’s aviation program and who plan to take the flight operations courses.)**

1.	AVS 101 Introduction to Aviation
2.	AVS 201/201L Principles of Meteorology and Laboratory
3.	AVS 301 Applied Aerodynamics
4.	AVS 302 Human Factors
5.	AVS 315 Aviation Law
6.	AVS 402 Aircraft Systems
7.	AVS 403 Aviation Safety
8.	**All** courses listed under Required Flight Operations courses (See course descriptions starting on p. 68.) 

#### Finance Concentration in Business
1.	BUS 350 Principles of Finance
2.	BUS 472 Advanced Topics in Finance
3.	BUS 495 Investment Analysis
4.	**Two** of the following:
   ECO 225 Money & Banking
   ACC 301 Intermediate Accounting I
   ECO 375 Econometrics
   ECO 435 Time Series Analysis
   BUS 454 Research in Business
   ECO 457 US Econ History
   BUS 472 Advanced Topics in Finance (if the topic is substantially different from when taken to fulfill requirement #2)

#### Healthcare Administration Concentration in Business
1.	ECO 247 Health Economics **or** HSS 200 Comparative Health Systems
2.	BUS 300 Human Resource Management
3.	**One** of the following:
   DS 100 Introduction to Data Science
   PHL 200 Bio-Medical Ethics
   COM 332 Health Communication (WE)
   POL 350 US Social Policy Process
4.	**Two** of the following through an online partnership with Rize Education: 
   BUS 312 Healthcare Justice, Law, and Ethics
   BUS 342 Data-Driven Healthcare
   BUS 353 Healthcare Finance
   BUS 390 Strategic Healthcare Operations  

Students planning to attend graduate school in Healthcare Administration are strongly encouraged to take more than the five required courses to complete the concentration. Students should discuss their graduate school plans with the program director. 

The Healthcare Administration concentration is offered online through a consortium of accredited colleges and universities. All courses within the program are delivered by faculty employed by partner institutions in the consortium, with technology and administrative support provided by Rize Education. Oversight of courses offered through the consortium are reviewed and approved by Coe College. Students register through Coe College and receive academic credit from Coe College.

#### International Business Concentration in Business
1.	BUS 446 International Business Management 
2.	**Two** of the following:
   BUS 456 Advanced Topics in Global Business 
   ECO 336 Divergent Economic Growth 
   ECO 436 Econ Development
   ECO 446 International Econ
3.	**One** of the following:
   One course in a world language numbered 115 or above
   COM 236 Intercultural Communication
   IS 116 Intro to International Studies
   POL 258 World Politics
   One course with an international focus outside of the department, with approval of the department chair
4.	**One** of the following:
   A semester abroad
   A May Experiential Term abroad
   A capstone project in international business, supervised by a business faculty member
   An internship in international business, supervised by a business faculty member

#### Management Concentration in Business 
1. BUS 250 Principles of Management
2. **Four** of the following:   
   BUS 300 Human Resource Management      
   BUS 375 Business Ethics      
   BUS 387 Adv Top:Human Res Mgt      
   BUS 395 Organizational Behavior      
   BUS 446 International Business Management        
   BUS 454 Research in Business
   BUS 464 Seminar in Management
   BUS 470 Strategic Management      

#### Marketing Concentration in Business
1. BUS 330 Principles of Marketing  
2. **Four** of the following: 
   BUS 280 Business Websites **and** BUS 281 Social Media in Business  
   BUS 420 Sports Marketing and Communications  
   BUS 460 Advertising  
   BUS 461 Marketing Decision Making/Analysis  
   BUS 465 Advanced Topics in Marketing  
   BUS 470 Strategic Management  
   BUS 454 Research in Business (when topic is appropriate to marketing concentration) 
   PR 205 Public Relations  

#### Risk Management/Insurance Concentration in Business
1.	BUS 350 Principles of Finance 
2.	DS 100 Introduction to Data Science 
3.	BUS 310 Insurance Company Operations 
4.	BUS 311 Personal and Business Risk Manageme 
5.	**One** of the following:
   ECO 247 Health Economics 
   BUS 341 Introductory Business Analytics 
   BUS 411 Adv Topics:Risk Management/Insuranc 
   BUS 454 Research in Business (when topic is appropriate to Risk Management/Insurance concentration)
   BUS 494 Internship in Business (when internship is appropriate to Risk Management/Insurance concentration)
   BUS 495 Investment Analysis

#### Sports Management Concentration in Business {#sec-sports-management-concentration}
1. SMT 100 Introduction to Sports Management  
2. **Four** of the following:   
   DS 120 Sports Analytics 
   BUS 400 Legal Issues in Sports   
   BUS 420 Sports Marketing and Communications  
   BUS 454 Research in Business (when topic is appropriate to sports management concentration)  
   SMT 300 Sport/Recreation Event Management  
   SMT 450 Seminar in Sports Management  
   SMT 494 Internship in Sports Management  
 
#### Supply Chain Management Concentration in Business 
1.	**One** of the following data analysis courses:
   BUS 340 Applied Regression Analysis 
   BUS 341 Introductory Business Analytics 
   ECO 375 Econometrics 
   DS 260 Data Analysis and Visualization 
2.	**One** of the following global strategy courses:
   BUS 446 International Business Management 
   ECO 446 International Econ 
3.	**Two** required courses through an online partnership with Rize Education:
   BUS 346 Forecasting & Logistics 
   BUS 381 Sourcing & Operations 
4.	**One** of the following through an online partnership with Rize Education:
   BUS 442 Supply Chain Mgmt Technologies 
   BUS 459 Supply Chain in Action 
   BUS 463 Capstone in Supply Chain Management 

The Supply Chain Management concentration is offered online through a consortium of accredited colleges and universities. All courses within the program are delivered by faculty employed by partner institutions in the consortium, with technology and administrative support provided by Rize Education. Oversight of courses offered through the consortium are reviewed and approved by Coe College. Students register through Coe College and receive academic credit from Coe College.
