## Communications Studies
Carr, Harmsen, Opayemi (Chair)

The aim of the major in communication studies is to provide a background of theory and practice in oral and mediated communication.  In their study of formal and informal oral, print and digital environments, students will learn to communicate ethically, responsibly and effectively for diverse audiences in multiple contexts.

### Communication Studies Major
A major in communication studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.com101.long >}}  
2. {{< var c.com125.long >}}  
3. **One** methods course:  
    {{< var c.com281.long >}}  
    {{< var c.com381.long >}}  
4. **One** course in Human Communication:  
    {{< var c.com137.long >}}  
    {{< var c.com231.long >}}  
    {{< var c.com225_227.long >}}  
    {{< var c.com322.long >}}  
    {{< var c.com327.long >}}  
    {{< var c.com236.long >}}  
    {{< var c.com323.long >}}  
    {{< var c.com332.long >}}  
    {{< var c.com435_437.long >}}  
5. **One** course in Mass Media:  
    {{< var c.com141.long >}}  
    {{< var c.com151.long >}}  
    {{< var c.com157.long >}}  
    {{< var c.com241.long >}}  
    {{< var c.com245_247.long >}}  
    {{< var c.com257.long >}}  
    {{< var c.com341.long >}}  
    {{< var c.com445_447.long >}}  
6. **One** course in Cultural and Critical Communications:
    {{< var c.com160.long >}}  
    {{< var c.com161.long >}}  
    {{< var c.com267.long >}}  
    {{< var c.com275_277.long >}}  
    {{< var c.com377.long >}}  
    {{< var c.com465_467.long >}}
7. A Communication Studies (COM) course numbered 400 or above (if not used to satisfy requirement 4, 5, or 6)
8. **Three** additional courses with a COM prefix; students may count up to 1.0 credits with ECC prefix toward this requirement, including ECC-494 Internship in English, Creative Writing, and Communication Studies

### Communication Studies Minor
A minor in communication studies requires a minimum cumulative 2.0 GPA in all courses counted toward the minor. 

1. {{< var c.com101.long >}}  
2. {{< var c.com125.long >}}  
3. **Three** additional courses with a COM prefix; students may count up to 1.0 credits with ECC prefix toward this requirement, including ECC-494 Internship in English, Creative Writing, and Communication Studies  

### COURSES IN COMMUNICATION STUDIES

 **{{< var c.com101.long >}}**  
  {{< var c.com101.desc >}}  
 **{{< var c.com125.long >}}**  
  {{< var c.com125.desc >}}  
 **{{< var c.com137.long >}}**  
  {{< var c.com137.desc >}}  
 **{{< var c.com141.long >}}**  
  {{< var c.com141.desc >}}  
 **{{< var c.com151.long >}}**  
  {{< var c.com151.desc >}}  
 **{{< var c.com157.long >}}**  
  {{< var c.com157.desc >}}  
 **{{< var c.com160.long >}}**  
  {{< var c.com160.desc >}}  
 **{{< var c.com161.long >}}**  
  {{< var c.com161.desc >}}  
 **{{< var c.com212.long >}}**  
  {{< var c.com212.desc >}}  
 **{{< var c.com225_227_245_247_275_277.long >}}**  
  {{< var c.com225_227_245_247_275_277.desc >}}  
 **{{< var c.com231.long >}}**  
  {{< var c.com231.desc >}}  
 **{{< var c.com236.long >}}**  
  {{< var c.com236.desc >}}  
 **{{< var c.com241.long >}}**  
  {{< var c.com241.desc >}}  
 **{{< var c.com257.long >}}**  
  {{< var c.com257.desc >}}  
 **{{< var c.com267.long >}}**  
  {{< var c.com267.desc >}}  
 **{{< var c.com281.long >}}**  
  {{< var c.com281.desc >}}  
 **{{< var c.com322.long >}}**  
  {{< var c.com322.desc >}}  
 **{{< var c.com323.long >}}**  
  {{< var c.com323.desc >}}  
 **{{< var c.com327.long >}}**  
  {{< var c.com327.desc >}}  
 **{{< var c.com332.long >}}**  
  {{< var c.com332.desc >}}  
 **{{< var c.com341.long >}}**  
  {{< var c.com341.desc >}}  
 **{{< var c.com347.long >}}**  
  {{< var c.com347.desc >}}  
 **{{< var c.com377.long >}}**  
  {{< var c.com377.desc >}}  
 **{{< var c.com381.long >}}**  
  {{< var c.com381.desc >}}  
 **{{< var c.com394.long >}}**  
  {{< var c.com394.desc >}}  
 **{{< var c.com435_437.long >}}**  
  {{< var c.com435_437.desc >}}  
 **{{< var c.com444.long >}}**  
  {{< var c.com444.desc >}}  
 **{{< var c.com455_457.long >}}**  
  {{< var c.com455_457.desc >}}  
 **{{< var c.com465_467.long >}}**  
  {{< var c.com465_467.desc >}}  
