## Computer Science
Hughes, Saha, Stobb

Computer Science is the study of abstractions and algorithmic processes and how they can be applied to fulfill human information needs. The department of mathematical sciences offers a complete range of courses, with majors and minors available in **COMPUTER SCIENCE, DATA SCIENCE,** and **MATHEMATICS**, as well as courses in statistics for additional breadth. The department adheres to its belief that the mathematical sciences and the habits of mind that they engender are components of a fine liberal arts education.

### Computer Science Major

A major in computer science requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.cs110.long >}}, **or** commensurate programming experience  
2. {{< var c.cs115.long >}}  
3. {{< var c.cs210.long >}}  
4. {{< var c.cs215.long >}}  
5. {{< var c.cs220.long >}}  
6. **One** Introductory Mathematics course:
   {{< var c.mth135.long >}}  
   {{< var c.mth165.long >}}  
7. {{< var c.mth215.long >}}  
8. **One** of the following:   
   {{< var c.cs230.long >}}  
   {{< var c.ds230.long >}}  
9. **Three** Computer Science Application courses: 
   {{< var c.cs320.long >}}  
   {{< var c.cs330.long >}}  
   {{< var c.cs340.long >}}  
   {{< var c.cs350.long >}}  
   {{< var c.cs384.long >}}  
   {{< var c.ds315.long >}}  
   {{< var c.ds370.long >}}  
10. **One** Advanced Software Development course:
   {{< var c.cs410.long >}}  
   {{< var c.cs430.long >}}  
   {{< var c.cs440.long >}}  
11. {{< var c.cs480.long >}}  

### Computer Science Minor 

1. {{< var c.cs110.long >}}   
2. {{< var c.cs115.long >}}  
3. {{< var c.cs210.long >}}  
4. **Two** additional Computer Science courses numbered 200 or higher
5. **One** additional Computer Science course numbered 300 or higher

The following courses do not satisfy any of the requirements for a major or minor in Computer Science:
{{< var c.cs105.long >}}   
{{< var c.cs205.long >}}   

### Courses in Computer Science 

 **{{< var c.cs105.long >}}**   
  {{< var c.cs105.desc >}}   
 **{{< var c.cs110.long >}}**   
  {{< var c.cs110.desc >}}   
 **{{< var c.cs115.long >}}**   
  {{< var c.cs115.desc >}}   
 **{{< var c.cs205.long >}}**   
  {{< var c.cs205.desc >}}   
 **{{< var c.cs210.long >}}**   
  {{< var c.cs210.desc >}}   
 **{{< var c.cs215.long >}}**   
  {{< var c.cs215.desc >}}   
 **{{< var c.cs220.long >}}**  
  {{< var c.cs220.desc >}}  
 **{{< var c.cs230.long >}}**   
  {{< var c.cs230.desc >}}   
 **{{< var c.cs280.long >}}**  
  {{< var c.cs280.desc >}}  
 **{{< var c.cs320.long >}}**  
  {{< var c.cs320.desc >}}  
 **{{< var c.cs330.long >}}**  
  {{< var c.cs330.desc >}}  
 **{{< var c.cs340.long >}}**  
  {{< var c.cs340.desc >}}  
 **{{< var c.cs350.long >}}**  
  {{< var c.cs350.desc >}}  
 **{{< var c.cs384.long >}}**  
  {{< var c.cs384.desc >}}  
 **{{< var c.cs410.long >}}**  
  {{< var c.cs410.desc >}}  
 **{{< var c.cs430.long >}}**  
  {{< var c.cs430.desc >}}  
 **{{< var c.cs440.long >}}**  
  {{< var c.cs440.desc >}}  
 **{{< var c.cs444.long >}}**  
  {{< var c.cs444.desc >}}  
 **{{< var c.cs480.long >}}**  
  {{< var c.cs480.desc >}}  
 **{{< var c.cs484.long >}}**  
  {{< var c.cs484.desc >}}  
