## English, Creative Writing, and Communication Studies  
Carr, Ferguson, Harmsen, Hausknecht, LeMay, Opayemi (Chair), Shaw, Sodeman  

### Courses in English, Creative Writing, and Communication Studies  

 **ECC 100 Inspirations and Aspirations** 
ECC-100 English, Creative Writing, and Communication Studies: Inspirations and Aspirations
Allows students to identify and share the values, priorities, and motivations that draw them to a major in English, Creative Writing, or Communication Studies; and demonstrates how knowledge and skills honed within the classroom can be the foundation of different rewarding careers. This course is appropriate for both declared and exploratory majors. It includes values and strengths articulation, informational interviews, guest speakers, and a final collaborative presentation project. It welcomes any student interested in learning how studies in ENG, CRW, and COM can inspire and support a wide range of future paths. The 0.5 course credit does not count toward the ENG, CRW, or COM majors or minors. No prerequisites. (0.5 course credit)  
 **ECC 112 Intro to Wri Center Thry & PR (WE)** 
ECC-112 Introduction to Writing Center Theory & Practice (WE) Introduces foundations of writing center theory and pedagogy. Designed for Writing Center consultants who are concurrently beginning work at the writing center. Instruction takes place in weekly group meetings and individual conferences. Offered fall semesters only. (0.3 course credit)  
 **ECC 230 Grammar & Style Workshop** 
Examines various grammatical principles that provide structure to language and explores the stylistic choices available to writers. Focuses on the rhetorical use of grammar and style to affect meaning, express power relations, and persuade readers. Analysis of published writers and extensive practice in writing helps students develop stylistic versatility and effectiveness.  
 **ECC 312 Writing Center Theory & Pract (WE)** 
ECC-312 Wring Center Theory & Practice (WE) Explores current topics in writing center research. Students plan and complete a project informed by research and share with writing center peers. Offered fall and spring terms. May be taken more than once for credit for a maximum of 0.9 credits. Prerequisite: Introduction to Writing Center Theory & Practice (WE) (ECC-112) (0.3 course credit)  
 **ECC 325 CBP:Applied & Public Humanities** 
ECC-325 Community-Based Projects: Applied and Public Humanities 
Engages students in supervised work on service projects sponsored by external constituencies such as non-profit institutions and community agencies. Students learn how their knowledge and skills gained in ENG, CRW, COM, and other arts and humanities coursework can sustain prolonged engagement in a community setting, providing service and benefits to community and project sponsors and creating connections for future creative and professional growth. A commitment of 70 hours over a single term. P/NP only. (0.5 course credit)  
 **ECC 345 Writing Process** 
ECC-345 Writing Process (WE)
Focuses on established and emergent theories about writing and writers' processes from the discipline of writing studies. Students apply select theory and/or research in a self-study of their writing while undertaking a modest independent writing project of their own design, to be included with the self-study and other documents in a portfolio of polished work.  
 **ECC 494 Internship in Eng, Crw, & Comm** 
ECC-494 Internship in English, Creative Writing, and Communication Studies 
Explores a career area related to English, Creative Writing, or Communication Studies. Application and supervision through the Internship Specialist. A minimum of 140 hours on-site experience is required. P/NP basis only. A maximum of one credit may count toward a major or minor in English, Creative Writing, or Communication Studies. Prerequisites: junior standing and consent of department chair.  
