## Environmental Studies (Collateral Major)  
Ellis (Administrative Coordinator)

The Environmental Studies Major is a collateral, interdisciplinary program which requires students to study environmental issues using the techniques and perspectives from a variety of academic disciplines.

In the sophomore or junior year, a student intending to complete an environmental studies collateral submits a proposal to the Environmental Studies administrative coordinator, outlining the plan of study for the major and describing plans for independent research, internship, or off-campus study. Students seeking this collateral major should submit this document prior to enrollment in EVS-484 Topics in Environmental Studies. 

In addition to the requirements listed below, before undertaking a practicum experience, each student is strongly encouraged to consult with the Environmental Studies administrative coordinator to identify a practicum experience that supports his or her study of environmental issues.

Students choosing a collateral major in environmental studies may not select the concentration in environmental science. 

### Collateral Major in Environmental Studies  
A major in environmental studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.  

Concurrent completion of any of the majors for a B.A. degree listed on p. 21 of the Catalog is required.  

1. BIO 105 Introduction to Environmental Studies  
2. BIO 111/111L Urban Ecology **or** BIO 155/155L Organismal and Ecological Biology and Laboratory (WE)  
3. **One** of the following:  
	Any Data Science course  
	BUS 190 Statistical Analysis  
	BUS 340 Applied Regression Analysis  
	PSY 300 Stat Methods and Data Analysis  
	POL 244 Research Methods in Political Scien  
	SOC 235 Methods of Sociological Research  
	STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 110 Stats IIA: Inferential Reasoning (7 weeks)  
	STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 130 Stats IIB: Experimental Design (7 weeks)  
	STA 315 Mathematical Probability  
4. **Three** of the following:  
	BIO 111/111L Urban Ecology, if not used to satisfy #2  
	COM 267 Environmental Rhetoric  
	ECO 195 Prin of Environmental Economics  
	POL 107 Environmental Justice (NOTE: Taught at the Wilderness Field Station)  
	PHL 205 Environmental Ethics  
	PHY 161 Energy: Science and Technology  
5.	EVS 484 Topics in Environmental Studies  
6. **One** of the following Natural Science courses, if not used to satisfy #2 or #4  
	BIO 111/111L Urban Ecology   
	BIO 115 Marine Biology (Note: Offered May Term)  
	BIO 165/165L Introduction to Ornithology and Lab  
	BIO 175 Field Botany  
	BIO 185/185L Entomology and Lab (Note: Taught at the Wilderness Field Station)  
	+++MISSING INFO: c.bio285_185l.long +++ (Note: Taught at the Wilderness Field Station)  
	BIO 203 Northwoods Ecology (Note: Taught at the Wilderness Field Station)  
	BIO 275 Aquatic Ecology (Note: Taught at the Wilderness Field Station)  
	BIO 295/295L Spatial Ecology and Laboratory (WE)  
	CHM 103/103L Selected Concepts in Chemistry and Laboratory **or** CHM 121/121L General Chemistry I and Laboratory   
	PHY 161 Energy: Science and Technology  
	PHY 311 Renewable Energy (WE)  
7. **Two** of the following Social Science or Humanities courses if not used to satisfy #4  
	COM 267 Environmental Rhetoric  
	CRW 345 Writing Wilderness (Note: Taught at the Wilderness Field Station)  
	ECO 175 Principles of Macroeconomics  
	ECO 215 Prin Microeconomics  
	HIS 205 The Historians Craft  
	PHL 128 Morality & Moral Controversies  
	PHL 205 Environmental Ethics  
	POL 107 Environmental Justice (Note: Taught at the Wilderness Field Station)  
	POL 115 American National Gov & Pol   
	POL 258 World Politics  
	POL 210 Environmental Politics  
	PSY 215 Multicultural Psychology  
	PSY 255 Social Psychology  

### Minor in Environmental Studies  
1. BIO 105 Introduction to Environmental Studies  
2. **One** of the following:  
	Any Data Science course  
	BUS 190 Statistical Analysis  
	BUS 340 Applied Regression Analysis  
	PSY 300 Stat Methods and Data Analysis  
	POL 244 Research Methods in Political Scien  
	SOC 235 Methods of Sociological Research  
	STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 110 Stats IIA: Inferential Reasoning (7 weeks)  
	STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 130 Stats IIB: Experimental Design (7 weeks)  
	STA 315 Mathematical Probability  
3. **Two** of the following:  
	BIO 111/111L Urban Ecology, if not used to satisfy #2  
	COM 267 Environmental Rhetoric  
	ECO 195 Prin of Environmental Economics  
	POL 107 Environmental Justice (NOTE: Taught at the Wilderness Field Station)  
	PHL 205 Environmental Ethics  
	PHY 161 Energy: Science and Technology  
4. **One** of the following Natural Science courses, if not used to satisfy #2 or #3  
	BIO 111/111L Urban Ecology   
	BIO 115 Marine Biology (Note: Offered May Term)  
	BIO 165/165L Introduction to Ornithology and Lab  
	BIO 175 Field Botany  
	BIO 185/185L Entomology and Lab (Note: Taught at the Wilderness Field Station)  
	+++MISSING INFO: c.bio285_185l.long +++ (Note: Taught at the Wilderness Field Station)  
	BIO 203 Northwoods Ecology (Note: Taught at the Wilderness Field Station)  
	BIO 275 Aquatic Ecology (Note: Taught at the Wilderness Field Station)  
	BIO 295/295L Spatial Ecology and Laboratory (WE)  
	CHM 103/103L Selected Concepts in Chemistry and Laboratory **or** CHM 121/121L General Chemistry I and Laboratory   
	PHY 161 Energy: Science and Technology  
	PHY 311 Renewable Energy (WE)  
5. **One** of the following Social Science or Humanities courses, if not used to satisfy #3  
	COM 267 Environmental Rhetoric  
	CRW 345 Writing Wilderness (Note: Taught at the Wilderness Field Station)  
	ECO 175 Principles of Macroeconomics  
	ECO 215 Prin Microeconomics  
	HIS 205 The Historians Craft  
	PHL 128 Morality & Moral Controversies  
	PHL 205 Environmental Ethics  
	POL 107 Environmental Justice (Note: Taught at the Wilderness Field Station)  
	POL 115 American National Gov & Pol   
	POL 258 World Politics  
	POL 210 Environmental Politics  
	PSY 215 Multicultural Psychology  
	PSY 255 Social Psychology  

### Courses in Environmental Studies (Collateral Major)  

 **ECO 195 Prin of Environmental Economics**  
  An introduction to the economics of the environment and natural resource allocation. This course is focused on optimal resource allocation and the problems associated with externalities and public goods in the context of a market economy. Environmental issues and policy are analyzed using standard economic models. This course may be used to satisfy the requirements for a major in Environmental Studies but does not satisfy any of the requirements for a major or minor in economics. Prerequisite: Principles of Macroeconomics (ECO-175).   
 **EVS 484 Topics in Environmental Studies**  
  An intensive examination of selected works and subjects dealing with environmental issues. Specific topics vary from year to year. Prerequisite: junior standing or permission of instructor. May be taken more than once for credit with permission of instructor.   













