## Environmental Studies (Collateral Major)  
Ellis (Administrative Coordinator)

The Environmental Studies Major is a collateral, interdisciplinary program which requires students to study environmental issues using the techniques and perspectives from a variety of academic disciplines.

In the sophomore or junior year, a student intending to complete an environmental studies collateral submits a proposal to the Environmental Studies administrative coordinator, outlining the plan of study for the major and describing plans for independent research, internship, or off-campus study. Students seeking this collateral major should submit this document prior to enrollment in EVS-484 Topics in Environmental Studies. 

In addition to the requirements listed below, before undertaking a practicum experience, each student is strongly encouraged to consult with the Environmental Studies administrative coordinator to identify a practicum experience that supports his or her study of environmental issues.

Students choosing a collateral major in environmental studies may not select the concentration in environmental science. 

### Collateral Major in Environmental Studies  
A major in environmental studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.  

Concurrent completion of any of the majors for a B.A. degree listed on p. 21 of the Catalog is required.  

1. {{< var c.bio105.long >}}  
2. {{< var c.bio111_111l.long >}} **or** {{< var c.bio155_155l.long >}}  
3. **One** of the following:  
	Any Data Science course  
	{{< var c.bus190.long >}}  
	{{< var c.bus340.long >}}  
	{{< var c.psy300.long >}}  
	{{< var c.pol244.long >}}  
	{{< var c.soc235.long >}}  
	{{< var c.sta100.long >}} (7 weeks) **and** {{< var c.sta110.long >}} (7 weeks)  
	{{< var c.sta100.long >}} (7 weeks) **and** {{< var c.sta130.long >}} (7 weeks)  
	{{< var c.sta315.long >}}  
4. **Three** of the following:  
	{{< var c.bio111_111l.long >}}, if not used to satisfy #2  
	{{< var c.com267.long >}}  
	{{< var c.eco195.long >}}  
	{{< var c.pol107.long >}} (NOTE: Taught at the Wilderness Field Station)  
	{{< var c.phl205.long >}}  
	{{< var c.phy161.long >}}  
5.	{{< var c.evs484.long >}}  
6. **One** of the following Natural Science courses, if not used to satisfy #2 or #4  
	{{< var c.bio111_111l.long >}}   
	{{< var c.bio115.long >}} (Note: Offered May Term)  
	{{< var c.bio165_165l.long >}}  
	{{< var c.bio175.long >}}  
	{{< var c.bio185_185l.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio285_285l.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio203.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio275.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio295_295l.long >}}  
	{{< var c.chm103_103l.long >}} **or** {{< var c.chm121_121l.long >}}   
	{{< var c.phy161.long >}}  
	{{< var c.phy311.long >}}  
7. **Two** of the following Social Science or Humanities courses if not used to satisfy #4  
	{{< var c.com267.long >}}  
	{{< var c.crw345.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.eco175.long >}}  
	{{< var c.eco215.long >}}  
	{{< var c.his205.long >}}  
	{{< var c.phl128.long >}}  
	{{< var c.phl205.long >}}  
	{{< var c.pol107.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.pol115.long >}}   
	{{< var c.pol258.long >}}  
	{{< var c.pol210.long >}}  
	{{< var c.psy215.long >}}  
	{{< var c.psy255.long >}}  

### Minor in Environmental Studies  
1. {{< var c.bio105.long >}}  
2. **One** of the following:  
	Any Data Science course  
	{{< var c.bus190.long >}}  
	{{< var c.bus340.long >}}  
	{{< var c.psy300.long >}}  
	{{< var c.pol244.long >}}  
	{{< var c.soc235.long >}}  
	{{< var c.sta100.long >}} (7 weeks) **and** {{< var c.sta110.long >}} (7 weeks)  
	{{< var c.sta100.long >}} (7 weeks) **and** {{< var c.sta130.long >}} (7 weeks)  
	{{< var c.sta315.long >}}  
3. **Two** of the following:  
	{{< var c.bio111_111l.long >}}, if not used to satisfy #2  
	{{< var c.com267.long >}}  
	{{< var c.eco195.long >}}  
	{{< var c.pol107.long >}} (NOTE: Taught at the Wilderness Field Station)  
	{{< var c.phl205.long >}}  
	{{< var c.phy161.long >}}  
4. **One** of the following Natural Science courses, if not used to satisfy #2 or #3  
	{{< var c.bio111_111l.long >}}   
	{{< var c.bio115.long >}} (Note: Offered May Term)  
	{{< var c.bio165_165l.long >}}  
	{{< var c.bio175.long >}}  
	{{< var c.bio185_185l.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio285_285l.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio203.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio275.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.bio295_295l.long >}}  
	{{< var c.chm103_103l.long >}} **or** {{< var c.chm121_121l.long >}}   
	{{< var c.phy161.long >}}  
	{{< var c.phy311.long >}}  
5. **One** of the following Social Science or Humanities courses, if not used to satisfy #3  
	{{< var c.com267.long >}}  
	{{< var c.crw345.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.eco175.long >}}  
	{{< var c.eco215.long >}}  
	{{< var c.his205.long >}}  
	{{< var c.phl128.long >}}  
	{{< var c.phl205.long >}}  
	{{< var c.pol107.long >}} (Note: Taught at the Wilderness Field Station)  
	{{< var c.pol115.long >}}   
	{{< var c.pol258.long >}}  
	{{< var c.pol210.long >}}  
	{{< var c.psy215.long >}}  
	{{< var c.psy255.long >}}  

### Courses in Environmental Studies (Collateral Major)  

 **{{< var c.eco195.long >}}**  
  {{< var c.eco195.desc >}}   
 **{{< var c.evs484.long >}}**  
  {{< var c.evs484.desc >}}   













