## Museum Studies (Minor Only)  
Rogers (Administrative Coordinator)  

The Museum Studies minor is designed to educate and train students in the basic tenets of museum-related work that is applicable to traditional museums of all kinds (art, cultural, thematic, science, etc.), archaeological sites, auction and appraisal houses, historic homes, historical societies, and commercial galleries.

If pursuing another major or minor in a related discipline (Art, Art History, Business, History, Public Relations), you can only double count two courses. 

A Museum Studies minor may also complete an Art major or minor or Art History minor, but only two courses may count toward both the major and the minors.

### Museum Studies Minor (MS)  
1.	MS 101 Intro to Museum Studies  
2.	MS 105 History of Museums  
3.	MS 283 Arts Administration  
4.	**One credit** from the following:  
  	MS 201 Curating a College Collection (0.5 credit)  
  	MS 203 Collection Mgmt & Registration (0.5 credit)  
  	MS 205 Exhibition Planning & Museum Audien (0.5 credit)  
  	MS 215 Exhibition Installation & Lighting (0.5 credit)  
  	+++MISSING INFO: c.art_ms235.long +++ (0.5 credit)  
  	MS 220 Marketing the Museum (0.5 credit)  
  	MS 225 Archives Care, Mgmt, & Best Practic (0.5 credit)  
  	MS 395 Topics in Museum Studies (0.5 or 1 credit)  
5.	**One** of the following:  
  	AAM 107 Intro to African American Studies   
  	ANT 116 Cultural Anthropology  
  	ANT 125 Art & Archaeology Classical World  
  	Any 100-level ART course  
  	ARH 106 World Art  
  	ARH 128 Introduction to Art History  
  	ARH 307 Modern and Contemporary Art  
  	BUS 125 Computers in Business  
  	BUS 250 Principles of Management  
  	BUS 285 Computer Appl:Adv Top  
  	BUS 330 Principles of Marketing  
  	BUS 460 Advertising  
  	BUS 461 Marketing Decision Making/Analysis  
  	COM 151 Introduction to New Media Studies  
  	COM 161 Visual Rhetoric  
  	COM 231 Communication in Teams (WE)  
  	COM 322 Prof Communication & Writing (WE)  
  	COM 327 Organizational Communication (WE)  
  	COM 377 Language, Power, and Social Change  
  	DS 100 Introduction to Data Science  
  	DS 230 Data-Centric Computing  
  	Any HIS course  
  	IS 116 Intro to International Studies  
  	PR 205 Public Relations  
6.	MS 494 Museum Studies Internship or ANT 208 Archaeological Field School   

### Courses in Museum Studies
100-level courses are open to any student and may offer the opportunity to explore two or more areas of art making in a studio environment.

 **MS 101 Intro to Museum Studies**  
Highlights the multi-faceted world of museum studies, as well as the numerous careers in museums (of various types), commercial galleries, historic homes and sites, auction houses, archives, and more. Features a series of guest lecturers who work with different entities in the Eastern Iowa area. These experts offer valuable insight to the numerous occupational choices–and their historical contexts–under the category of Museum Studies.  
 **MS 105 History of Museums**  
Reviews the history of museums. Evidence shows that humans have been collecting objects for millennia, and there are many reasons why, ranging from functional to aesthetic to displaying power, wealth, knowledge, and prestige. The evolution of museums from private collections to public institutions is investigated in depth.  
 **MS 201 Curating a College Collection**  
Implements the full experience of curatorial work. Students will research Coe’s Permanent Art Collection in order to craft an exhibition. They will write exhibition proposals, didactic panels, wall labels, extended wall labels, and more. Prerequisite: MS-101 Introduction to Museum Studies, MS-105 History of Museum Studies, or consent of instructor.MS-201 Curating a College Collection  
 **MS 203 Collection Mgmt & Registration**  
Introduces the organizational practices of art/museum collections. This includes work with databases as well as the best practices for handling artworks and artifacts, for storage and maintenance, and for preservation of materials. Prerequisite: MS-101 Introduction to Museum Studies, MS-105 History of Museum Studies, or consent of instructor.  
 **MS 205 Exhibition Planning & Museum Audien**  
Encourages students to design innovative and engaging exhibitions that enhance audience experiences. Using previously-curated exhibition plans, students map gallery installations using a variety of methods, such as traditional two-dimensional layouts, three dimensional models, and digital software. An additional attention is given to audience reception and the research surrounding memory and museum experiences. Prerequisites: two ART- courses (each 1.0 course credit), or MS-101 Introduction to Museum Studies, or MS-105 History of Museum Studies, or consent of instructor. (0.5 course credit)  
 **MS 215 Exhibition Installation & Lighting**  
Challenges students to actually install an art exhibition. This includes in-depth instruction on mapping, measuring, and physically installing objects in a gallery setting. In addition to lighting design, students also learn various installation techniques for two- and three-dimensional artwork, video and time-based media, and full gallery installations. This is an essential course for anyone pursuing work as a museum preparator. Prerequisites: two ART- courses (each 1.0 course credit), or MS-101 Introduction to Museum Studies, or MS-105 History of Museum Studies, or consent of instructor. (0.5 course credit)  
 **MS 220 Marketing the Museum**  
Directs students to analyze and implement best practices for museum advertising and public relations. Additionally, students must think about building donor and community relationships. This is an essential course for anyone pursuing work in museum marketing. Prerequisite: MS-101 Introduction to Museum Studies, MS-105 History of Museum Studies, or consent of instructor.  
 **MS 225 Archives Care, Mgmt, & Best Practic**  
Features in-depth, hands-on training with archival material, in addition to a brief academic history of libraries and archives. Projects involve work with Coe’s own George T. Henry College Archives or a local museum or historical institution. Prerequisite: MS-101 Introduction to Museum Studies, MS-105 History of Museum Studies, or consent of instructor.  
 **MS 235 Arts Advocacy**  
See also Art (ART-235)
Introduces students to arts advocacy, providing tools to cultivate, promote, sustain, and support the arts. Students will develop and implement arts advocacy programming. This course meets weekly for the full term. Prerequisites: two ART- courses (each 1.0 course credit), or MS-101 Introduction to Museum Studies, or MS-105 History of Museum Studies, or consent of instructor. (0.5 course credit)  
 **MS 283 Arts Administration**  
Implements the skills and guiding principles of managing arts-related organizations, in particular non-profits. Through collaborative efforts, students learn about project development and implementation, focusing on goal-setting initiatives, financial planning, marketing and advertising, viewership and participation, and audience awareness. Current issues and challenges facing nonprofit arts organizations will be addressed as well. Cross listed with MU-283 and THE-283.  
 **MS 395 Topics in Museum Studies**  
Examines a topic or theme pertaining to the field of museum studies, such the economics of museums and public institutions, deaccessioning and repatriation, technology in the museum, and controversies facing museums today. Depending on the course material and intended assignments, the course can be taken for 0.5 credits or 1 credit. Prerequisite: MS-101 Introduction to Museum Studies, MS-105 History of Museum Studies, or consent of instructor.  
 **MS 494 Museum Studies Internship**  
Focuses on an area of interest related to the Museum Studies minor. Requires placement within a museum or museum-related area that is approved by a faculty member associated with the minor. A minimum of 140 hours of on-site experience is required. P/NP basis only. Prerequisites: declared Museum Studies minor, junior standing, and consent of program director.  
