## Music {#sec-music}
Carson (Chair, Spring), Lovegood, Shanley (Chair, Fall)

Teaching Artists: Altfillisch, Bishop, Brumwell, Capistran, Farley, Fleer, Hall, Harris, Haselhuhn, Marrs, Morton, Nagel, Nothnagle, Phelps, Reznicow, Rothrock, Terrell, Wissenberg, B. Wolgast, M. Wolgast

All Coe students are encouraged to participate in music as part of their liberal arts education. Choral and instrumental ensembles, private lessons in applied music, and academic courses are open to non-music majors. 

*The Coe College Music Department Faculty/Student Handbook* supplements the descriptions of courses and requirements for music majors and outlines departmental policies and procedures. Copies of the *Handbook* are available in the Music Office, Marquis Hall 103 or online at www.coe.edu/academics/majors-areas-study/music.

### Music Major  
Candidates for a major in music must successfully complete:  

1. {{< var c.mu101.long >}}  
2. {{< var c.mu107.long >}}  
3. {{< var c.mu166.long >}}  
4. {{< var c.mu201.long >}}  
5. {{< var c.mu384.long >}}  
6. 4.5 credits of MUA- lessons or ensembles  
7. **One** additional credit in MU- coursework, numbered 300-level or above  
8. Students seeking music education licensure must also complete the Secondary Education Minor as listed on p. 119 (MU- courses may be used to satisfy #7)  
9. The Senior Assessment Examination in the final term prior to graduation  

#### Jazz Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Jazz.  Concurrent completion of a major in music is required.  A minimum of 6.3 course credits must be taken that do not count toward a major in music.  

1. {{< var c.mu157.long >}} **or** {{< var c.mu157.long >}}  
2. {{< var c.mu301.long >}}  
3. **Seven** terms of {{< var c.mua101.long >}}  
4. **Two** terms of {{< var c.mua102k.long >}}  
5. **Two** terms of {{< var c.mua103k.long >}}  
6. {{< var c.aam107.long >}}  

#### Music Industry Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Music Industry.  Concurrent completion of a major in music is required.  A minimum of 6.5 course credits must be taken in addition to those that count toward a major in music.  

1. A minimum of **One credit** earned in:  
	- {{< var c.mua111c.long >}}  
	**or**  
	- {{< var c.mua222c.long >}}  
2. {{< var c.mu283.long >}}  
3. **One** of the following:
	- {{< var c.com231.long >}}  
	- {{< var c.com322.long >}}  
	- {{< var c.com327.long >}}  
	- {{< var c.pr205.long >}}  
4. **One** of the following:  
	- {{< var c.bus250.long >}}  
	- {{< var c.bus330.long >}}  
5. A music industry-related internship or independent study

#### Pre-Music Therapy Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Pre-Music Therapy.  Concurrent completion of a major in music is required.  

The Pre-Music Therapy Emphasis is designed to prepare students to apply to a Music Therapy certification program. It is not a free-standing major, and it does not include music therapy courses. Rather, the courses listed below are intended to better prepare music students for future study in Music Therapy at an academic program approved by the American Music Therapy Association. Students must complete all requirements for a Bachelor of Arts in Music, in addition to the courses listed below. These include 5 non-music course credits and 2 additional music course credits for a minimum total of 7 course credits that must be taken in addition to those that count toward a major in music.  

Courses taken to satisfy requirements in the Bachelor of Arts in Music may NOT also be used to satisfy the requirements of the Pre-Music Therapy Emphasis below, but all courses MAY be used towards General Education requirements.  

1. {{< var c.psy100.long >}}  
2. {{< var c.bio103.long >}}  
3. {{< var c.bio100.long >}}  
4. **One** of the following:  
	- {{< var c.edu117.long >}}  
	- {{< var c.edu187.long >}}  
	- {{< var c.psy235.long >}}  
	- {{< var c.psy270.long >}}  
5. **One** of the following:  
	- {{< var c.the100.long >}}  
	- {{< var c.the150.long >}}  
	- {{< var c.the160.long >}}  
	- {{< var c.the170.long >}}  
	- {{< var c.the270.long >}}  
6. **Two** credits (or more) from the following:  
	- {{< var c.mu301.long >}}  
	- Additional terms of ensemble participation, beyond those required for the Bachelor of Arts in Music:  
		* Concert Band (0.3 each), Jazz Band (0.3 each), Concert Choir (0.3 each), Coe Sho Cho (0.3 each), or Crimson Singers (0.3 each)  
	- Additional terms of lessons, beyond those required for the music major  

Strongly recommended:  

- {{< var c.mu108.long >}}  
- {{< var c.mu385.long >}}  
- Additional music performance courses (ensembles and lessons)  
- Additional theatre, art, biology, business, education, psychology, sociology, and statistics courses  
- Fulfill the academic practicum requirement with a music therapy-related internship  

### Music Minor  
The minor in music consists of six course credits in music. At least two of these credits must be MU courses.  

### Departmental Notes  
- Private music lessons are available for credit only. Coe students are charged by term according to the total registered lesson credit. Students who have not attended three lessons by the end of the third week of classes are dropped from music lessons and may be reinstated only by petition. After the third week of lessons, students will be charged for the full term, even if they choose to drop.  
- Students who register for 0.3 cc (100-level) lessons will receive 12 half-hour private lessons. Students who register for 0.6 cc (200-level) will receive 12 one-hour private lessons.  

### APPLIED MUSIC CLASSES {#sec-MUA-classes}  
Artist teachers in violin, viola, cello, string and electric bass, piano, piano accompanying*, harpsichord*, organ*, flute, oboe, clarinet, saxophone, bassoon, trumpet, horn, trombone, low brass, percussion, guitar, harp, composition*, music production and engineering, and voice are available to all students who wish to study applied music.  

*Prerequisite: proficiency in piano and consent of instructor.  

Credit for applied music study is granted after the student has satisfactorily passed an examination by a faculty committee (jury exam) at the close of each term.  

#### APPLIED BRASSES--LESSONS
- {{< var c.mua101b.long >}}  
- {{< var c.mua202b.long >}}  
- {{< var c.mua111b.long >}}  
- {{< var c.mua212b.long >}}  
- {{< var c.mua121b.long >}}  
- {{< var c.mua222b.long >}}  
- {{< var c.mua131b.long >}}  
- {{< var c.mua232b.long >}}  

#### APPLIED COMPOSITION--LESSONS  
- {{< var c.mua101c.long >}}  
- {{< var c.mua111c.long >}}  
- {{< var c.mua202c.long >}}  
- {{< var c.mua222c.long >}}  

#### APPLIED KEYBOARD--LESSONS  
- {{< var c.mua101k.long >}}  
- {{< var c.mua102k.long >}}  
- {{< var c.mua103k.long >}}  
- {{< var c.mua202k.long >}}  
- {{< var c.mua304k.long >}}  
- {{< var c.mua111k.long >}}  
- {{< var c.mua212k.long >}}  
- {{< var c.mua121k.long >}}  
- {{< var c.mua222k.long >}}  

#### APPLIED PERCUSSION--LESSONS  
- {{< var c.mua101p.long >}}  
- {{< var c.mua202p.long >}}  

#### APPLIED STRINGS--LESSONS  
- {{< var c.mua101s.long >}}  
- {{< var c.mua202s.long >}}  
- {{< var c.mua111s.long >}}  
- {{< var c.mua212s.long >}}  
- {{< var c.mua121s.long >}}  
- {{< var c.mua222s.long >}}  
- {{< var c.mua131s.long >}}  
- {{< var c.mua232s.long >}}  
- {{< var c.mua141s.long >}}  
- {{< var c.mua242s.long >}}  
- {{< var c.mua151s.long >}}  
- {{< var c.mua252s.long >}}  

#### APPLIED VOICE--LESSONS  
- {{< var c.mua101v.long >}}  
- {{< var c.mua202v.long >}}  
- {{< var c.mua300a.long >}}  

#### APPLIED WOODWINDS--LESSONS  
- {{< var c.mua101w.long >}}  
- {{< var c.mua202w.long >}}  
- {{< var c.mua111w.long >}}  
- {{< var c.mua212w.long >}}  
- {{< var c.mua121w.long >}}  
- {{< var c.mua222w.long >}}  
- {{< var c.mua131w.long >}}  
- {{< var c.mua232w.long >}}  
- {{< var c.mua141w.long >}}  
- {{< var c.mua242w.long >}}  

### COURSES IN MUSIC BY CATEGORY  
#### ENSEMBLES  
Ensembles are open, by audition, to all Coe students, as well as being required of all students pursuing a degree in music. Students are encouraged to participate in these ensembles as often as possible.  

- {{< var c.mua100.long >}}  
- {{< var c.mua101.long >}}  
- {{< var c.mua104.long >}}  
- {{< var c.mua105.long >}}  
- {{< var c.mua110.long >}}  
- {{< var c.mua284.long >}}  
Coe College musicians seeking an orchestral experience are encouraged to participate in the Cedar Rapids Community Orchestra at Kirkwood Community College. Please contact the music office (319-399-8520) for more information about how to earn credit for your participation.  

#### GENERAL SURVEY COURSES  
- {{< var c.mu101.long >}}  
- {{< var c.mu107.long >}}  
- {{< var c.mu108.long >}}  
- {{< var c.mu117.long >}}  
- {{< var c.mu140.long >}}  
- {{< var c.mu157.long >}}  
- {{< var c.mu166.long >}}  
- {{< var c.mu201.long >}}  
- {{< var c.mu283.long >}}  
- {{< var c.mu284.long >}}  

#### THEORY COURSES  
- {{< var c.mu101.long >}}  
- {{< var c.mu201.long >}}  
- {{< var c.mu301.long >}}  

#### CONDUCTING COURSES  
- {{< var c.mu384.long >}}  
- {{< var c.mu385.long >}}  

#### HISTORY COURSES  
- {{< var c.mu107.long >}}  
- {{< var c.mu108.long >}}  
- {{< var c.mu117.long >}}  
- {{< var c.mu140.long >}}  
- {{< var c.mu157.long >}}  
- {{< var c.mu166.long >}}  

#### MUSIC EDUCATION COURSES  
- {{< var c.mu360.long >}}  
- {{< var c.mu361.long >}}  
- {{< var c.mu363.long >}}  

#### ADVANCED STUDY IN MUSIC  
- {{< var c.mua490.long >}}  
- {{< var c.mu444.long >}}  

### Courses in Music {#sec-courses-in-music}  
**MU Prefix**  

 **{{< var c.mu101.long >}}**  
  {{< var c.mu101.desc >}}  
 **{{< var c.mu107.long >}}**  
  {{< var c.mu107.desc >}}  
 **{{< var c.mu108.long >}}**  
  {{< var c.mu108.desc >}}  
 **{{< var c.mu117.long >}}**  
  {{< var c.mu117.desc >}}  
 **{{< var c.mu140.long >}}**  
  {{< var c.mu140.desc >}}  
 **{{< var c.mu157.long >}}**  
  {{< var c.mu157.desc >}}  
 **{{< var c.mu166.long >}}**  
  {{< var c.mu166.desc >}}  
 **{{< var c.mu201.long >}}**  
  {{< var c.mu201.desc >}}  
 **{{< var c.mu283.long >}}**  
  {{< var c.mu283.desc >}}  
 **{{< var c.mu284.long >}}**  
  {{< var c.mu284.desc >}}  
 **{{< var c.mu301.long >}}**  
  {{< var c.mu301.desc >}}  
 **{{< var c.mu360.long >}}**  
  {{< var c.mu360.desc >}}  
 **{{< var c.mu361.long >}}**  
  {{< var c.mu361.desc >}}  
 **{{< var c.mu363.long >}}**  
  {{< var c.mu363.desc >}}  
 **{{< var c.mu384.long >}}**  
  {{< var c.mu384.desc >}}  
 **{{< var c.mu385.long >}}**  
  {{< var c.mu385.desc >}}  
 **{{< var c.mu444.long >}}**  
  {{< var c.mu444.desc >}}  

**MUA Prefix**  

 **{{< var c.mua100.long >}}**  
  {{< var c.mua100.desc >}}  
 **{{< var c.mua101.long >}}**  
  {{< var c.mua101.desc >}}  
 **{{< var c.mua104.long >}}**  
  {{< var c.mua104.desc >}}  
 **{{< var c.mua105.long >}}**  
  {{< var c.mua105.desc >}}  
 **{{< var c.mua110.long >}}**  
  {{< var c.mua110.desc >}}  
 **{{< var c.mua130v.long >}}**  
  {{< var c.mua130v.desc >}}  
 **{{< var c.mua284.long >}}**  
  {{< var c.mua284.desc >}}  
 **{{< var c.mua490.long >}}**  
  {{< var c.mua490.desc >}}  
