## Music {#sec-music}
Carson (Chair, Spring), Lovegood, Shanley (Chair, Fall)

Teaching Artists: Altfillisch, Bishop, Brumwell, Capistran, Farley, Fleer, Hall, Harris, Haselhuhn, Marrs, Morton, Nagel, Nothnagle, Phelps, Reznicow, Rothrock, Terrell, Wissenberg, B. Wolgast, M. Wolgast

All Coe students are encouraged to participate in music as part of their liberal arts education. Choral and instrumental ensembles, private lessons in applied music, and academic courses are open to non-music majors. 

*The Coe College Music Department Faculty/Student Handbook* supplements the descriptions of courses and requirements for music majors and outlines departmental policies and procedures. Copies of the *Handbook* are available in the Music Office, Marquis Hall 103 or online at www.coe.edu/academics/majors-areas-study/music.

### Music Major  
Candidates for a major in music must successfully complete:  

1. MU 101 Music Fundamentals I  
2. MU 107 American Music  
3. MU 166 Music of the World  
4. MU 201 Music Fundamentals II  
5. MU 384 Conducting I  
6. 4.5 credits of MUA- lessons or ensembles  
7. **One** additional credit in MU- coursework, numbered 300-level or above  
8. Students seeking music education licensure must also complete the Secondary Education Minor as listed on p. 119 (MU- courses may be used to satisfy #7)  
9. The Senior Assessment Examination in the final term prior to graduation  

#### Jazz Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Jazz.  Concurrent completion of a major in music is required.  A minimum of 6.3 course credits must be taken that do not count toward a major in music.  

1. MU 157 Introduction to Jazz History **or** MU 157 Introduction to Jazz History  
2. MU 301 Music Fundamentals III  
3. **Seven** terms of MUA 101 Jazz Band  
4. **Two** terms of MUA 102K Piano Arranging Lessons  
5. **Two** terms of MUA 103K Piano: Jazz  
6. AAM 107 Intro to African American Studies  

#### Music Industry Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Music Industry.  Concurrent completion of a major in music is required.  A minimum of 6.5 course credits must be taken in addition to those that count toward a major in music.  

1. A minimum of **One credit** earned in:  
	- MUA 111C Music Production and Engineering  
	**or**  
	- MUA 222C Music Production and Engineering  
2. MU 283 Arts Administration  
3. **One** of the following:
	- COM 231 Communication in Teams (WE)  
	- COM 322 Prof Communication & Writing (WE)  
	- COM 327 Organizational Communication (WE)  
	- PR 205 Public Relations  
4. **One** of the following:  
	- BUS 250 Principles of Management  
	- BUS 330 Principles of Marketing  
5. A music industry-related internship or independent study

#### Pre-Music Therapy Emphasis  
Students completing a music degree may choose to supplement their music major with an Emphasis in Pre-Music Therapy.  Concurrent completion of a major in music is required.  

The Pre-Music Therapy Emphasis is designed to prepare students to apply to a Music Therapy certification program. It is not a free-standing major, and it does not include music therapy courses. Rather, the courses listed below are intended to better prepare music students for future study in Music Therapy at an academic program approved by the American Music Therapy Association. Students must complete all requirements for a Bachelor of Arts in Music, in addition to the courses listed below. These include 5 non-music course credits and 2 additional music course credits for a minimum total of 7 course credits that must be taken in addition to those that count toward a major in music.  

Courses taken to satisfy requirements in the Bachelor of Arts in Music may NOT also be used to satisfy the requirements of the Pre-Music Therapy Emphasis below, but all courses MAY be used towards General Education requirements.  

1. PSY 100 Introductory Psychology  
2. BIO 103 Anatomy & Physiology  
3. BIO 100 Human Biology  
4. **One** of the following:  
	- EDU 117 Exceptional Learners  
	- EDU 187 Human Relations  
	- PSY 235 Abnormal Psychology  
	- PSY 270 Learning and Behavior  
5. **One** of the following:  
	- THE 100 Introduction to Theatre  
	- THE 150 Acting I  
	- THE 160 Movement for the Stage  
	- THE 170 Voice & Diction  
	- THE 270 Musical Theatre Acting  
6. **Two** credits (or more) from the following:  
	- MU 301 Music Fundamentals III  
	- Additional terms of ensemble participation, beyond those required for the Bachelor of Arts in Music:  
		* Concert Band (0.3 each), Jazz Band (0.3 each), Concert Choir (0.3 each), Coe Sho Cho (0.3 each), or Crimson Singers (0.3 each)  
	- Additional terms of lessons, beyond those required for the music major  

Strongly recommended:  

- MU 108 Queerness in Music  
- MU 385 Conducting II  
- Additional music performance courses (ensembles and lessons)  
- Additional theatre, art, biology, business, education, psychology, sociology, and statistics courses  
- Fulfill the academic practicum requirement with a music therapy-related internship  

### Music Minor  
The minor in music consists of six course credits in music. At least two of these credits must be MU courses.  

### Departmental Notes  
- Private music lessons are available for credit only. Coe students are charged by term according to the total registered lesson credit. Students who have not attended three lessons by the end of the third week of classes are dropped from music lessons and may be reinstated only by petition. After the third week of lessons, students will be charged for the full term, even if they choose to drop.  
- Students who register for 0.3 cc (100-level) lessons will receive 12 half-hour private lessons. Students who register for 0.6 cc (200-level) will receive 12 one-hour private lessons.  

### APPLIED MUSIC CLASSES {#sec-MUA-classes}  
Artist teachers in violin, viola, cello, string and electric bass, piano, piano accompanying*, harpsichord*, organ*, flute, oboe, clarinet, saxophone, bassoon, trumpet, horn, trombone, low brass, percussion, guitar, harp, composition*, music production and engineering, and voice are available to all students who wish to study applied music.  

*Prerequisite: proficiency in piano and consent of instructor.  

Credit for applied music study is granted after the student has satisfactorily passed an examination by a faculty committee (jury exam) at the close of each term.  

#### APPLIED BRASSES--LESSONS
- MUA 101B Trumpet  
- MUA 202B Trumpet  
- MUA 111B French Horn  
- MUA 212B French Horn  
- MUA 121B Trombone  
- MUA 222B Trombone  
- MUA 131B Low Brass  
- MUA 232B Low Brass  

#### APPLIED COMPOSITION--LESSONS  
- MUA 101C Composition  
- MUA 111C Music Production and Engineering  
- MUA 202C Composition  
- MUA 222C Music Production and Engineering  

#### APPLIED KEYBOARD--LESSONS  
- MUA 101K Piano Lessons  
- MUA 102K Piano Arranging Lessons  
- MUA 103K Piano: Jazz  
- MUA 202K Piano Lessons  
- MUA 304K Piano Accompanying  
- MUA 111K Organ  
- MUA 212K Organ  
- MUA 121K Harpsichord Lessons  
- MUA 222K Harpsichord Lessons  

#### APPLIED PERCUSSION--LESSONS  
- MUA 101P Percussion  
- MUA 202P Percussion  

#### APPLIED STRINGS--LESSONS  
- MUA 101S Violin  
- MUA 202S Violin  
- MUA 111S Viola  
- MUA 212S Viola  
- MUA 121S Cello  
- MUA 222S Cello  
- MUA 131S String Bass  
- MUA 232S String Bass  
- MUA 141S Harp  
- MUA 242S Harp  
- MUA 151S Guitar  
- MUA 252S Guitar  

#### APPLIED VOICE--LESSONS  
- MUA 101V Voice  
- MUA 202V Voice  
- MUA 300A Alexander Technique  

#### APPLIED WOODWINDS--LESSONS  
- MUA 101W Flute  
- MUA 202W Flute  
- MUA 111W Oboe  
- MUA 212W Oboe  
- MUA 121W Clarinet  
- MUA 222W Clarinet  
- MUA 131W Saxophone  
- MUA 232W Saxophone  
- MUA 141W Bassoon  
- MUA 242W Bassoon  

### COURSES IN MUSIC BY CATEGORY  
#### ENSEMBLES  
Ensembles are open, by audition, to all Coe students, as well as being required of all students pursuing a degree in music. Students are encouraged to participate in these ensembles as often as possible.  

- MUA 100 Concert Band  
- MUA 101 Jazz Band  
- MUA 104 Concert Choir  
- MUA 105 Crimson Singers  
- MUA 110 Coe Sho Cho  
- MUA 284 Applied Music: Special Topics  
Coe College musicians seeking an orchestral experience are encouraged to participate in the Cedar Rapids Community Orchestra at Kirkwood Community College. Please contact the music office (319-399-8520) for more information about how to earn credit for your participation.  

#### GENERAL SURVEY COURSES  
- MU 101 Music Fundamentals I  
- MU 107 American Music  
- MU 108 Queerness in Music  
- MU 117 Jazz: The Early Years  
- MU 140 Film Music  
- MU 157 Introduction to Jazz History  
- MU 166 Music of the World  
- MU 201 Music Fundamentals II  
- MU 283 Arts Administration  
- MU 284 Topics in Music  

#### THEORY COURSES  
- MU 101 Music Fundamentals I  
- MU 201 Music Fundamentals II  
- MU 301 Music Fundamentals III  

#### CONDUCTING COURSES  
- MU 384 Conducting I  
- MU 385 Conducting II  

#### HISTORY COURSES  
- MU 107 American Music  
- MU 108 Queerness in Music  
- MU 117 Jazz: The Early Years  
- MU 140 Film Music  
- MU 157 Introduction to Jazz History  
- MU 166 Music of the World  

#### MUSIC EDUCATION COURSES  
- MU 360 Elementary & General Music Methods  
- MU 361 Choral Music Methods  
- MU 363 Instrumental Music Methods  

#### ADVANCED STUDY IN MUSIC  
- MUA 490 Senior Recital  
- MU 444 Independent Study  

### Courses in Music {#sec-courses-in-music}  
**MU Prefix**  

 **MU 101 Music Fundamentals I**  
  Introduces the materials of music and an understanding of the musical system: melody, harmony, notation, songwriting, arranging, aural skills, and technology.  
 **MU 107 American Music**  
  Examines the diversity of American music ranging from Rock ‘n’ Roll and Hip Hop to Classical, Jazz, Avant-Garde, and Musical Theatre. Societal influences on American music, including issues of race, gender, and religious prejudice, will be explored within a historical framework.  
 **MU 108 Queerness in Music**  
  MU-108 Queerness in Music: A History
Examines queer musical artists throughout history; both those who lived authentic and queer lifestyles, and those who struggled with identity, challenged by society, and closeted at various times of their lives. The course will explore music ranging from classical to vaudeville, from early blues and Jazz Age to present day. Recordings, videos, and discussions will illuminate the historical context of modern-day drag, the stories behind songs, and the influence these songs had over time. Issues related to masculinity, femininity, gender fluidity, cross-dressing, homosexuality, love, race, religion will be addressed.  
 **MU 117 Jazz: The Early Years**  
  Combines an on-campus experience with visits to Memphis, New Orleans, and Nashville. The visit to New Orleans, the birthplace of jazz, introduces students to the early history of one of America's greatest contributions to the world of music. Seeing New Orleans in person helps students understand the geographical, political, and societal influences that shaped the early history of Jazz. Students also visit Beale Street in Memphis and the National Museum of African American Music in Nashville to develop an understanding of the music that preceded and followed New Orleans jazz. Listening to live music is emphasized. Offered May Experiential Term only.  
 **MU 140 Film Music**  
  An introduction to the history, principles, and techniques of music in film. In addition to lecture, film viewing and analysis, critical reading and response, student presentation, and short film-music projects elucidate the genre.  
 **MU 157 Introduction to Jazz History**  
  Surveys many styles of jazz by studying them in a historical perspective. Listening, discussion, and lecture components are emphasized. (Offered May Term only)  
 **MU 166 Music of the World**  
  MU-166 Music of the World
Surveys the music of the world, ranging from Classical and Art Music to Traditional and Popular musics of other nationalities and cultures. Emphasis is on examining these musics in their social, cultural, and historical contexts.  
 **MU 201 Music Fundamentals II**  
  MU-201 Music Fundamentals II
Studies materials of music and the musical system, building on the concepts developed in Music Fundamentals I: melody, harmony, rhythm, notation, songwriting, arranging, aural skills, and technology. Prerequisite: Music Fundamentals I or consent of instructor. Prerequisite: Music Fundamentals I or consent of instructor.  
 **MU 283 Arts Administration**  
  Implements the skills and guiding principles of managing arts-related organizations, in particular non-profits. Through collaborative efforts, students learn about project development and implementation, focusing on goal-setting initiatives, financial planning, marketing and advertising, viewership and participation, and audience awareness. Current issues and challenges facing nonprofit arts organizations will be addressed as well. Cross listed with MS-283 and THE-283.  
 **MU 284 Topics in Music**  
  Centers on a particular musical issue, problem, theory, or methodology. Topics vary, and they include, but are not limited to, Advanced Form and Analysis, Rock and Roll History, Music of the 1960s, and Modern Musical Theatre. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: consent of instructor. (Offered on an occasional basis)  
 **MU 301 Music Fundamentals III**  
  MU-301 Music Fundamentals III
Continues the advanced study of the materials of music and the musical system: melody, harmony, rhythm, notation, songwriting, arranging, aural skills, and technology. Prerequisite: Music Fundamentals II or consent of instructor.  
 **MU 360 Elementary & General Music Methods**  
  Objectives, problems, and methods of teaching elementary music and general music in the schools. Course surveys elementary and general music curricula and develops a functional knowledge of: organization and management; fretted and classroom instruments; methods of teaching singing, rhythmic, and listening activities expected. Directed observation in elementary schools required. Pre-or co-requisite: Practicum in Education (EDU-215) or consent of Music Department Chair.  
 **MU 361 Choral Music Methods**  
  Objectives, problems, and methods of teaching choral music in the schools. General survey of elementary and secondary choral music curricula and develops a functional knowledge of: organization and management; the changing voice; beginning, intermediate, and advanced choral techniques. Directed observation in elementary and secondary schools required. Prerequisite: Practicum in Education (EDU-215)  
 **MU 363 Instrumental Music Methods**  
  Objectives, problems, and methods of teaching instrumental music in the schools. General survey of elementary and secondary instrumental music curricula and develops a functional knowledge of: organization and management; concert band and orchestral techniques; jazz band techniques; marching band techniques; beginning, intermediate, and advanced band and orchestral techniques. Directed observation in elementary and secondary schools required. Prerequisite: Practicum in Education (EDU-215).  
 **MU 384 Conducting I**  
  Basic conducting techniques: reading, analysis, and interpretation of choral, band, and orchestral literature. Laboratory experience with college ensembles.  
 **MU 385 Conducting II**  
  Continuation of Conducting I. Prerequisite: Conducting I (MU-384).  
 **MU 444 Independent Study**  
  Independent work on a selected project in music under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration.  Prerequisites: background courses and consent of department chair.  

**MUA Prefix**  

 **MUA 100 Concert Band**  
  Open to all woodwind, brass, and percussion players. The ensemble offers students the opportunity to perform some of the great band repertoire of the 20th and 21st centuries, as well as carefully selected transcriptions of orchestral repertoire. A select Wind Ensemble within the Concert Band occasionally performs additional selections from the contemporary repertoire. The Concert Band tours on a regular basis. (0.3 course credit)  
 **MUA 101 Jazz Band**  
  MUA-101 Jazz Band

Membership determined by an audition of interested saxophone, trombone, trumpet, piano, bass, guitar, drum set, and auxiliary percussion players. The ensemble offers students the opportunity to perform varied selections from the jazz repertoire of the 20th and 21st centuries, as well as the opportunity to improvise in the jazz idiom. The Jazz Band tours on a regular basis and performs with three to five guest artists each year. (0.3 course credit)  
 **MUA 104 Concert Choir**  
  Performs a wide variety of repertoire covering many styles from the Renaissance through the 21st centuries, in a large, auditioned, mixed ensemble. The Concert Choir also performs on and off campus, in both formal and informal concert settings and tours on a regular basis. (0.3 course credit)  
 **MUA 105 Crimson Singers**  
  Performs a wide variety of repertoire from the Renaissance through the 21st centuries in a small auditioned, mixed singing ensemble. Crimson Singers performs on and off campus, in both formal and informal concert settings and tours on a regular basis. (0.3 course credit)  
 **MUA 110 Coe Sho Cho**  
  Provides an opportunity, through rehearsal and performance, to experience the combination of popular, musical theater, contemporary a cappella and jazz choral literature, as well as choreography, in a medium-sized mixed ensemble. Membership is determined by audition. While previous show choir experience is preferable, it is not required. Students in Coe Sho Cho are also encouraged to enroll in the Concert Choir. Coe Sho Cho performs on and off campus, in both formal and informal concert settings and tours on a regular basis. (0.3 course credit)  
 **MUA 130V MusicalTheatreProductionExperience**  
  Practical involvement in a mainstage production of a musical as a vocal or instrumental performer, accompanist,
or vocal coach stage manager, assistant director, dramaturge, or in another capacity as approved by the faculty.
May be taken more than once. Prerequisite: an audition. (0.5 course credit)  
 **MUA 284 Applied Music: Special Topics**  
  Private study in Applied Music topics not offered in MUA course listings for music majors or other interested and qualified students. The course provides extended, yet tangible, instruction and/or research pertaining to the student's specific applied music specialty or related music interest area. Prerequisites: consent of instructor and department chair. (0.3 and 0.6 course credit)  
 **MUA 490 Senior Recital**  
  A full-length senior recital in composition or performance area. P/NP basis only. Prerequisite: consent of instructor.  
