## Philosophy 
Lemos (Chair)

The Philosophy and Religion Department offers courses designed for students to engage with human thought and practice through the study of important texts and historical evidence as well as recent and contemporary writings. Philosophy and Religion courses help students encounter the diversity of human ideas and religious practice in ways that are thoughtful, respectful, and accurate. Students will grow in their abilities to read texts, construct arguments from evidence, think critically, and communicate accurately and with nuance. Any student seeking a liberal education, whatever the major discipline, will profit from the departmental offerings.

### Philosophy Major 
A major in philosophy requires a minimum cumulative GPA of 2.0 in all courses counted towards the major.  

1. PHL 105 Introduction to Philosophy:  
2. PHL 115 Logic  
3. PHL 220 Ancient Greek Philosophy  
4. PHL 300 Early Modern Philosophy  
5-9. Five additional courses, two of which must be Philosophy courses at the 300-level or higher. With the approval of the Philosophy program faculty, two of these four may be courses taken outside of the Philosophy program.  
10. PHL 490 Philosophy Colloquium  

**NOTE:** *The recommended beginning course in philosophy for those contemplating a major in philosophy is Introduction to Philosophy (PHL-105). However, any of the other 100-level courses are also suitable first courses. Some courses numbered between 200 and 299 may be suitable first courses for students with sophomore standing.* 

### Philosophy Minor  

Five courses in Philosophy, two of which must be at the 200-level or higher and one of which must be at the 300-level or higher.  

### Courses in Philosophy  

#### Introductory courses  

The introductory courses listed here are especially well suited for first-year students, as they presuppose no familiarity with college-level writing and reading expectations and there are no prerequisites for these courses.  

The various courses numbered PHL-105 are different versions of the same course. They share some overlapping content and focus on the development of the same skills. Students can receive credit for only one PHL-105 Introduction to Philosophy course.  
 
**PHL 105 Introduction to Philosophy: Minds, Knowledge, and Value (WE)**  
  Examines what philosophers think about some of the most basic questions in life. What is real? What does it mean to have a mind? Could minds have an existence independent from our bodies? Is there anything we can know with absolute certainty? Are there objective moral values, and if so, could we know what they are? May not be taken more than once for credit.  
 **PHL 105 Introduction to Philosophy: God, Self, and Free Will (WE)**  
  Focuses on questions about the nature and existence of God, human nature, personhood, and free will. Is there evidence for the existence of God and is the presence of suffering in the world consistent with God’s existence? Are human beings merely material beings or might we have non-physical minds or souls? What are persons and what constitutes personal identity over time? What does it mean to have free will? Do we possess free will? May not be taken more than once for credit.  
 **PHL 105 Introduction to Philosophy: Masterworks (WE)**  
  Central philosophical debates encountered through the examination of important classical and modern texts from the history philosophy. Readings in the course focus on several major works from philosophers such as Plato, Descartes, Hume, Marx, and Sartre who discuss the meaning of life, belief in God, the mind-body problem, relativism of truth, and other important philosophical concerns. May not be taken more than once for credit.  
 **PHL 105 Introduction to Philosophy: Science Fiction and Philosophy (WE)**  
  Uses science fiction as a springboard for thinking about classic issues and problems in philosophy. Sci-fi classics such as The Matrix, Bladerunner, and Surrogates, raise fundamental philosophical questions such as: What is the difference between appearance and reality and how can we distinguish between them? What is it to be a person? Should we think that all and only human beings can be persons? What is a good human life? Is a pleasant life sufficient for living a good life? In this course, such questions are examined through the lens of both philosophy and science fiction. May not be taken more than once for credit.   
 **PHL 115 Logic**  
  Introduces the discipline of logic on an elementary level. This course teaches skills that are essential to good critical reasoning—how to detect forms of arguments, how to test for validity, and how to construct valid arguments. This course focuses on both formal and informal logic.  
 **PHL 128 Morality & Moral Controversies**  
  Examines important moral issues facing contemporary society. The course uses a variety of common ethical theories. Possible topics include environmental ethics, euthanasia, animal rights, humanitarian aid, abortion, and capital punishment.  
 **PHL 200 Bio-Medical Ethics**  
  Addresses a variety of issues in medical ethics and introduces various moral frameworks for thinking about these issues. Students are introduced to ethical theories, such as utilitarianism and Kantianism, and how they can be applied in the context of medical ethics. Topics addressed in the course are likely to include: abortion, euthanasia, paternalism, and patient autonomy, organ transplants and scarce medical resources, and genetic screening, among others.  
 **PHL 205 Environmental Ethics**  
  Serves as a general introduction to environmental ethics. Students receive instruction in ethical theory and how it can be applied to issues in environmental ethics. Some topics likely to be addressed in the course are: defining our obligations to future generations, the definition of wilderness, sustainable agriculture, animal rights, anthropocentrism, the nature of the value of wilderness, environmental holism, and ecofeminism.  
 **PHL 210 Topics in Philosophy**  
  Examines a selected topic in philosophy. Topics vary depending on the instructor. May be taken more than once for credit, provided the topics are substantially different.  
 **PHL 220 Ancient Greek Philosophy**  
  Surveys of the central ideas and figures in the philosophy of the ancient Greek world. Figures studied include the pre-Socratic philosophers, Socrates, Plato, and Aristotle.  
 **PHL 265 Political Philosophy**  
  Examines the central issues in social and political philosophy concerning the individual’s relation to society and to the state in particular. Questions may include: on what basis can states legitimately exercise authority over individuals? What are the proper ends and limits of state authority? What principles should our society pursue in allocating goods such as property, education, health, and welfare?  
 **PHL 285 Law, Morality & Punishment**  
  Addresses key issues in the philosophy of law. Topics may include issues of both distributive justice and retributive justice, the proper limits of state authority in restricting individual liberty, and civil disobedience. Questions addressed in the course may include: On what principled basis should wealth be distributed in society? On what basis is the punishment of persons justified and what forms should punishment take? Should we abolish institutions of punishment? On what principled basis should the state be allowed to infringe upon individual liberty? What constitutes civil disobedience to the laws and under what conditions is civil disobedience justified, if ever?  
 **PHL 300 Early Modern Philosophy**  
  Examines the metaphysical and epistemological theories of major European philosophers of the 17th and 18th centuries. Readings are drawn from the works of Descartes, Spinoza, Leibniz, Locke, Berkeley, Hume, and Kant. Prerequisite: one course in philosophy or consent of instructor.  
 **PHL 315 Advanced Topics in Philosophy**  
  Examines a selected topic in philosophy. Topics vary depending on the instructor. May be taken more than once for credit, provided the topics are substantially different. Prerequisites: two courses in philosophy or consent of instructor.  
 **PHL 320 Seminar in Ethics**  
  Examines central topics in normative ethics and/or metaethics. Topics addressed may include: utilitarianism, Kantianism, Aristotelian virtue theory, moral realism, ethical relativism, etc. In this course emphasis is placed on the development of student research projects on central topics in ethical theory. Prerequisite: two courses in philosophy or consent of instructor.  
 **PHL 355 Seminar Metaphysics & Epistemology**  
  Examines central topics in metaphysics and epistemology. Metaphysical topics addressed may include: the nature and existence of God, the nature of the self and personal identity, free will, etc. Epistemological topics addressed may include the analysis of knowledge, theories of justified belief, the philosophy of perception, etc. In this course emphasis is placed on the development of student research projects on central topics in metaphysics or epistemology. Prerequisite: two courses in philosophy or consent of instructor.  
 **PHL 394 Directed Learning in Philosophy**  
  Provides the opportunity for a student to design a course of study fitting the individual student’s particular interests and educational needs. Readings may focus on either a philosophical problem or one or more philosophers. Prerequisite: consent of instructor.  
 **PHL 444 Ind Study-Philos**  
  Allows for the independent study of some philosophical problem or the thought of some major philosopher, under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of instructor.  
 **PHL 490 Philosophy Colloquium**  
  Requires students majoring in philosophy to submit 10–15 pages of finished philosophical prose, and present their work orally to students and faculty. Although the Colloquium is usually taken during Spring Term of the senior year, it is open to all juniors and seniors with appropriate background in philosophy. Satisfactory completion of the Colloquium is required for graduation with a major in philosophy. P/NP basis only. (0.0 credits)  
 **PHL 494 Internship in Philosophy**  
  Involves the exploration of a career area related to the student’s interest in philosophy supervised by a faculty member of the department in cooperation with the Internship Specialist. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major in philosophy. Prerequisites: declared major in philosophy, junior standing, and consent of department chair.  
