## Philosophy 
Lemos (Chair)

The Philosophy and Religion Department offers courses designed for students to engage with human thought and practice through the study of important texts and historical evidence as well as recent and contemporary writings. Philosophy and Religion courses help students encounter the diversity of human ideas and religious practice in ways that are thoughtful, respectful, and accurate. Students will grow in their abilities to read texts, construct arguments from evidence, think critically, and communicate accurately and with nuance. Any student seeking a liberal education, whatever the major discipline, will profit from the departmental offerings.

### Philosophy Major 
A major in philosophy requires a minimum cumulative GPA of 2.0 in all courses counted towards the major.  

1. {{< var c.phl105.long >}}  
2. {{< var c.phl115.long >}}  
3. {{< var c.phl220.long >}}  
4. {{< var c.phl300.long >}}  
5-9. Five additional courses, two of which must be Philosophy courses at the 300-level or higher. With the approval of the Philosophy program faculty, two of these four may be courses taken outside of the Philosophy program.  
10. {{< var c.phl490.long >}}  

**NOTE:** *The recommended beginning course in philosophy for those contemplating a major in philosophy is Introduction to Philosophy (PHL-105). However, any of the other 100-level courses are also suitable first courses. Some courses numbered between 200 and 299 may be suitable first courses for students with sophomore standing.* 

### Philosophy Minor  

Five courses in Philosophy, two of which must be at the 200-level or higher and one of which must be at the 300-level or higher.  

### Courses in Philosophy  

#### Introductory courses  

The introductory courses listed here are especially well suited for first-year students, as they presuppose no familiarity with college-level writing and reading expectations and there are no prerequisites for these courses.  

The various courses numbered PHL-105 are different versions of the same course. They share some overlapping content and focus on the development of the same skills. Students can receive credit for only one PHL-105 Introduction to Philosophy course.  
 
**{{< var c.phl105a.long >}}**  
  {{< var c.phl105a.desc >}}  
 **{{< var c.phl105b.long >}}**  
  {{< var c.phl105b.desc >}}  
 **{{< var c.phl105c.long >}}**  
  {{< var c.phl105c.desc >}}  
 **{{< var c.phl105d.long >}}**  
  {{< var c.phl105d.desc >}}  
 **{{< var c.phl115.long >}}**  
  {{< var c.phl115.desc >}}  
 **{{< var c.phl128.long >}}**  
  {{< var c.phl128.desc >}}  
 **{{< var c.phl200.long >}}**  
  {{< var c.phl200.desc >}}  
 **{{< var c.phl205.long >}}**  
  {{< var c.phl205.desc >}}  
 **{{< var c.phl210.long >}}**  
  {{< var c.phl210.desc >}}  
 **{{< var c.phl220.long >}}**  
  {{< var c.phl220.desc >}}  
 **{{< var c.phl265.long >}}**  
  {{< var c.phl265.desc >}}  
 **{{< var c.phl285.long >}}**  
  {{< var c.phl285.desc >}}  
 **{{< var c.phl300.long >}}**  
  {{< var c.phl300.desc >}}  
 **{{< var c.phl315.long >}}**  
  {{< var c.phl315.desc >}}  
 **{{< var c.phl320.long >}}**  
  {{< var c.phl320.desc >}}  
 **{{< var c.phl355.long >}}**  
  {{< var c.phl355.desc >}}  
 **{{< var c.phl394.long >}}**  
  {{< var c.phl394.desc >}}  
 **{{< var c.phl444.long >}}**  
  {{< var c.phl444.desc >}}  
 **{{< var c.phl490.long >}}**  
  {{< var c.phl490.desc >}}  
 **{{< var c.phl494.long >}}**  
  {{< var c.phl494.desc >}}  
