## Physics  
Affatigato, Akgun (Administrative Coordinator, Engineering Physics), Baehr, Duru (Chair), Li, Wetzel, Wheaton  

The physics department serves a variety of students with a balanced program, giving equal emphasis to the needs of the technically and the non-technically oriented.  

### BACHELOR OF ARTS: Physics Major  
A major in physics requires a minimum cumulative 2.0 GPA in all courses counted toward the major.  

1. {{< var c.phy185_185l.long >}}   
2. {{< var c.phy195_195l.long >}}  
3. {{< var c.phy231.long >}}  
4. {{< var c.phy235.long >}} **and** {{< var c.phy236.long >}}  
5. {{< var c.phy265.long >}}  
6. **Two** of the following courses:  
	- {{< var c.phy275.long >}}  
	- {{< var c.phy315.long >}}  
	- {{< var c.phy335.long >}}  
	- {{< var c.phy425.long >}}  
7. **Four** additional physics or engineering physics full-credit courses, all of which must be numbered 150 or above.  
8.	Comprehensive evaluation  
	- Satisfactory completion of written and oral examinations  

***Recommended:***  
	- {{< var c.cs110.long >}}  
	- {{< var c.chm121_121l.long >}}  

### Physics Minor
A minor in Physics requires a cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.phy185_185l.long >}} **or** {{< var c.phy165_165l.long >}}  
2. {{< var c.phy195_195l.long >}} **or** {{< var c.phy175_175l.long >}}  
3. {{< var c.phy235.long >}} **or** {{< var c.phy236.long >}}  
4. {{< var c.phy265.long >}}  
5. **Two** additional physics courses approved by the department, both of which must be numbered 150 and above.  

### Bachelor of Science in Engineering Program  
The B.S.E. degree in Engineering Physics requires a minimum cumulative 2.0 GPA in all courses counted towards the major.  

Students completing the B.S.E. in Engineering Physics cannot minor in Physics and cannot earn a B.A. degree with a major in physics.  

Candidates for the BACHELOR OF SCIENCE IN ENGINEERING degree with an area of study in engineering physics must successfully complete  

1.	{{< var c.enr101.long >}}  
2.	{{< var c.enr101l.long >}}  
3.	{{< var c.enr145.long >}}  
4.	{{< var c.phy185_185l.long >}}  
5.	{{< var c.phy195_195l.long >}}  
6.	{{< var c.mth155.long >}} **or** {{< var c.mth135.long >}} **and** {{< var c.mth145.long >}}  
7.	{{< var c.chm121_121l.long >}}  
8.	{{< var c.phy231.long >}}  
9.	{{< var c.phy235.long >}}  
10.	{{< var c.phy245_245l.long >}}  
11.	{{< var c.phy246.long >}}  
12.	{{< var c.phy265.long >}}  
13.	{{< var c.enr325_325l.long >}}  
14.	{{< var c.enr405.long >}}  
15.	{{< var c.enr415.long >}}  
16.	**Four** of the following:  
	- {{< var c.enr221.long >}}  
	- {{< var c.enr321.long >}}  
	- {{< var c.enr355.long >}}  
	- {{< var c.phy275.long >}}  
	- {{< var c.phy311.long >}}  
	- {{< var c.phy315.long >}}  
17.	**One** of the following:  
	- {{< var c.chm122_122l.long >}}  
	- One full-credit Physics or Engineering Physics course which must be numbered 150 and above. 

### Courses in Physics  
 **{{< var c.phy104.long >}}**  
  {{< var c.phy104.desc >}}  
 **{{< var c.phy105.long >}}**  
  {{< var c.phy105.desc >}}  
 **{{< var c.phy114_114l.long >}}**  
  {{< var c.phy114_114l.desc >}}  
 **{{< var c.phy121.long >}}**  
  {{< var c.phy121.desc >}}  
 **{{< var c.phy161.long >}}**  
  {{< var c.phy161.desc >}}  
 **{{< var c.phy165_165l.long >}}**  
  {{< var c.phy165_165l.desc >}}  
 **{{< var c.phy175_175l.long >}}**  
  {{< var c.phy175_175l.desc >}}  
 **{{< var c.phy185_185l.long >}}**  
  {{< var c.phy185_185l.desc >}}  
 **{{< var c.phy195_195l.long >}}**  
  {{< var c.phy195_195l.desc >}}  
 **{{< var c.phy211.long >}}**  
  {{< var c.phy211.desc >}}  
 **{{< var c.phy231.long >}}**  
  {{< var c.phy231.desc >}}  
 **{{< var c.phy235.long >}}**  
  {{< var c.phy235.desc >}}  
 **{{< var c.phy236.long >}}**  
  {{< var c.phy236.desc >}}  
 **{{< var c.phy241.long >}}**  
  {{< var c.phy241.desc >}}  
 **{{< var c.phy245_245l.long >}}**  
  {{< var c.phy245_245l.desc >}}  
 **{{< var c.phy246.long >}}**  
  {{< var c.phy246.desc >}}  
 **{{< var c.phy251.long >}}**  
  {{< var c.phy251.desc >}}  
 **{{< var c.phy255_355.long >}}**  
  {{< var c.phy255_355.desc >}}  
 **{{< var c.phy265.long >}}**  
  {{< var c.phy265.desc >}}  
 **{{< var c.phy275.long >}}**  
  {{< var c.phy275.desc >}}  
 **{{< var c.phy301.long >}}**  
  {{< var c.phy301.desc >}}  
 **{{< var c.phy311.long >}}**  
  {{< var c.phy311.desc >}}  
 **{{< var c.phy315.long >}}**  
  {{< var c.phy315.desc >}}  
 **{{< var c.phy321.long >}}**  
  {{< var c.phy321.desc >}}  
 **{{< var c.phy335.long >}}**  
  {{< var c.phy335.desc >}}  
 **{{< var c.phy341.long >}}**  
  {{< var c.phy341.desc >}}  
 **{{< var c.phy425.long >}}**  
  {{< var c.phy425.desc >}}  
 **{{< var c.phy441.long >}}**  
  {{< var c.phy441.desc >}}  
 **{{< var c.phy444.long >}}**  
  {{< var c.phy444.desc >}}  
 **{{< var c.phy451.long >}}**  
  {{< var c.phy451.desc >}}  
 **{{< var c.phy454.long >}}**  
  {{< var c.phy454.desc >}}  
 **{{< var c.phy464_474.long >}}**  
  {{< var c.phy464_474.desc >}}  
 **{{< var c.phy484.long >}}**  
  {{< var c.phy484.desc >}}  
 **{{< var c.phy494.long >}}**  
  {{< var c.phy494.desc >}}  

### Courses in Engineering Physics  

 **{{< var c.enr101.long >}}**  
  {{< var c.enr101.desc >}}  
 **{{< var c.enr101l.long >}}**  
  {{< var c.enr101l.desc >}}  
 **{{< var c.enr145.long >}}**  
  {{< var c.enr145.desc >}}  
 **{{< var c.enr221.long >}}**  
  {{< var c.enr221.desc >}}  
 **{{< var c.enr321.long >}}**  
  {{< var c.enr321.desc >}}  
 **{{< var c.enr325_325l.long >}}**  
  {{< var c.enr325_325l.desc >}}  
 **{{< var c.enr355.long >}}**  
  {{< var c.enr355.desc >}}  
 **{{< var c.enr405.long >}}**  
  {{< var c.enr405.desc >}}  
 **{{< var c.enr415.long >}}**  
  {{< var c.enr415.desc >}}  

