## Physics  
Affatigato, Akgun (Administrative Coordinator, Engineering Physics), Baehr, Duru (Chair), Li, Wetzel, Wheaton  

The physics department serves a variety of students with a balanced program, giving equal emphasis to the needs of the technically and the non-technically oriented.  

### BACHELOR OF ARTS: Physics Major  
A major in physics requires a minimum cumulative 2.0 GPA in all courses counted toward the major.  

1. PHY 185/185L General Physics I & Laboratory   
2. PHY 195/195L General Physics II & Laboratory  
3. PHY 231 Math Mthds Physicists & Engineers  
4. PHY 235 Modern Physics **and** PHY 236 Advanced Laboratory 1  
5. PHY 265 Electromagnetism  
6. **Two** of the following courses:  
	- PHY 275 Classical Mechanics  
	- PHY 315 Thermodynamics & Stat Mech  
	- PHY 335 Quantum Mechanics  
	- PHY 425 Solid State Physics  
7. **Four** additional physics or engineering physics full-credit courses, all of which must be numbered 150 or above.  
8.	Comprehensive evaluation  
	- Satisfactory completion of written and oral examinations  

***Recommended:***  
	- CS 110 Introduction to Programming  
	- CHM 121/121L General Chemistry I and Laboratory  

### Physics Minor
A minor in Physics requires a cumulative 2.0 GPA in all courses counted toward the major.

1. PHY 185/185L General Physics I & Laboratory **or** PHY 165/165L Basic Physics I & Laboratory  
2. PHY 195/195L General Physics II & Laboratory **or** PHY 175/175L Basic Physics II & Laboratory  
3. PHY 235 Modern Physics **or** PHY 236 Advanced Laboratory 1  
4. PHY 265 Electromagnetism  
5. **Two** additional physics courses approved by the department, both of which must be numbered 150 and above.  

### Bachelor of Science in Engineering Program  
The B.S.E. degree in Engineering Physics requires a minimum cumulative 2.0 GPA in all courses counted towards the major.  

Students completing the B.S.E. in Engineering Physics cannot minor in Physics and cannot earn a B.A. degree with a major in physics.  

Candidates for the BACHELOR OF SCIENCE IN ENGINEERING degree with an area of study in engineering physics must successfully complete  

1.	ENR 101 Introduction to Engineering Design  
2.	ENR 101L Engineering Design Laboratory  
3.	ENR 145 Comput Mthds for Physicist & Engin  
4.	PHY 185/185L General Physics I & Laboratory  
5.	PHY 195/195L General Physics II & Laboratory  
6.	MTH 155 Calculus for Engineers **or** MTH 135 Calculus I **and** MTH 145 Calculus II  
7.	CHM 121/121L General Chemistry I and Laboratory  
8.	PHY 231 Math Mthds Physicists & Engineers  
9.	PHY 235 Modern Physics  
10.	+++MISSING INFO: c.phy245_245l.long +++  
11.	PHY 246 Advanced Laboratory 2 (WE)  
12.	PHY 265 Electromagnetism  
13.	+++MISSING INFO: c.enr325_325l.long +++  
14.	ENR 405 Senior Design 1  
15.	ENR 415 Senior Design 2  
16.	**Four** of the following:  
	- ENR 221 Materials Science Engineering 1  
	- ENR 321 Materials Science Engineering 2  
	- ENR 355 Robotics and Sensors  
	- PHY 275 Classical Mechanics  
	- PHY 311 Renewable Energy (WE)  
	- PHY 315 Thermodynamics & Stat Mech  
17.	**One** of the following:  
	- CHM 122/122L General Chemistry II and Laboratory  
	- One full-credit Physics or Engineering Physics course which must be numbered 150 and above. 

### Courses in Physics  
 **PHY 104 From the Big Bang to First Humans**  
  Studies the history of the evolving Universe starting with the Big Bang all the way to the first humans on the Earth. The conditions in the first moments of the Universe, formation of matter and forces, formation of galaxies, stars and planets, emergence of life on Earth, the evolution of life from the first organisms to the humans, along with very basic science to understand all these phenomena, are covered.  
 **PHY 105 Physics: An Historical Approach**  
  Introduces important developments in physics from the time of Aristotle to the 20th century. Special attention is given to significant conceptual developments and major technological advances. Readings are selected from writings of some of the major figures in the history of physics, as well as modern commentators. The class experience includes reenactments of some historically significant experiments. This course satisfies the non-lab science course requirement.  
 **PHY 114/114L Modern Astronomy & Laboratory**  
  Introduces the objects and phenomena found in the universe, including the solar system, planets, moons, comets, meteors, the sun, stars, birth and death of stars, neutron stars, pulsars, black holes, galaxies, quasars, and cosmological evolution. Laboratory activities required. Lab is P/NP basis only. This course satisfies the general education laboratory science requirement. Prerequisite: competence in algebra.  
 **PHY 121 Everyday Physics**  
  Covers the principle of physics we use in our daily life. Examples from everyday experience are used to explain the fundamental principles of linear and rotational motion, momentum, forces, energy, as well as electricity, magnetism, and medical applications.  
 **PHY 161 Energy: Science and Technology**  
  Covers physics and technology of energy generation, consumption, and conservation. Covers a wide range of energy sources, including fossil fuels, hydropower, solar energy, wind energy, bioenergy, and nuclear energy. Surveys the efficiencies and environmental impacts of energy use in transportation, manufacturing, and buildings.  
 **PHY 165/165L Basic Physics I & Laboratory**  
  An algebra-based survey course in the basic principles of mechanics, dynamics, energy, momentum and rotational motion. One (0.0 course credit) laboratory per week, held jointly with General Physics laboratories, is a required part of this course. Lab is P/NP basis only. This course satisfies the general education laboratory science requirement. Previous experience in algebra recommended.  
 **PHY 175/175L Basic Physics II & Laboratory**  
  An algebra-based survey course in the basic principles of thermodynamics, electrostatics, magnetism, circuits, light, and optics. One (0.0 course credit) laboratory per week, held jointly with General Physics laboratories, is a required part of this course. Lab is P/NP basis only. This course satisfies the general education laboratory science requirement. Prerequisite: Basic Physics I & Laboratory (PHY-165/-165L), or consent of instructor.  
 **PHY 185/185L General Physics I & Laboratory**  
  A calculus-based introduction to mechanics to serve as a basis for advanced courses in physics. Kinematics, dynamics, energy, momentum, rotational motion and fluid mechanics are covered. One (0.0 course credit) laboratory per week, held jointly with Basic Physics laboratories, is a required part of this course. Lab is P/NP basis only. Previous experience in calculus recommended.   
 **PHY 195/195L General Physics II & Laboratory**  
  A calculus-based introduction to thermodynamics, electrostatics, magnetism, circuits, light, and optics. One (0.0 course credit) laboratory per week, held jointly with Basic Physics laboratories, is a required part of this course. Lab is P/NP basis only. Prerequisites: General Physics I & Laboratory (PHY-185/-185L) or consent of instructor.   
 **PHY 211 Glass Science**  
  Introduces the physics and chemistry behind the formation and study of glassy materials. The course covers glass making, glass structure and surfaces, property characterization, a wide array of industrial and scientific applications, as well as modern experimental techniques. It is especially suitable in preparation for glass research, and for students interested in a possible career in materials research and/or condensed matter physics. Prerequisite: General Physics II & Laboratory (PHY-195/-195L), or consent of instructor.  
 **PHY 231 Math Mthds Physicists & Engineers**  
  Studies areas of mathematics that are of fundamental importance in the physical sciences. Topics include vector calculus, eigenvalue problems, curvilinear coordinates, Fourier analysis, introduction to complex variables and differential equations. Topics include complex variables, Fourier analysis, eigenvalue problems, and vector calculus. Includes one computer laboratory session per week. Previous experience in calculus is recommended. Prerequisite: Calculus II (MTH-145), or Calculus for Engineers and Physicists (ENR 125).  
 **PHY 235 Modern Physics**  
  Introduces quantum phenomena, including the wave-particle duality, atomic models, special theory of relativity, Schrodinger’s equation and its applications to certain potentials. Corequisite: Advanced Laboratory 1 (PHY-236). Prerequisites: General Physics II & Laboratory (PHY-195/-195L) or consent of instructor.  
 **PHY 236 Advanced Laboratory 1**  
  PHY-236 Advanced Laboratory 1 (WE) Introduces laboratory measurement techniques as applied to modern physics experiments. Experiments from optics and atomic physics. A writing intensive course with laboratory and computer design projects based on applications of modern physics and atomic physics. Corequisite: Modern Physics (PHY-235). (0.5 course credit)  
 **PHY 241 Introduction to Astrophysics**  
  Covers the fundamental concepts in astrophysics: The tools of astronomy, celestial mechanics, interaction of light and matter, telescopes, nature of the stars and their classifications. Other topics include the general overview of the solar system, and the binary systems. Prerequisite: General Physics II & Laboratory (PHY-195/-195L) or consent of instructor.  
 **+++MISSING INFO: c.phy245_245l.long +++**  
  +++MISSING INFO: c.phy245_245l.desc +++  
 **PHY 246 Advanced Laboratory 2 (WE)**  
  Continuation of Advanced Laboratory 1. A writing-intensive course that expands the laboratory experiments to nuclear and particle physics, such as Gamma Ray Spectroscopy, Nuclear Magnetic Resonance, Muon Lifetime, and Nuclear radiation. Prerequisite: Modern Physics (PHY-235) and Advanced Laboratory 1 (PHY-236). (0.5 course credits)  
 **PHY 251 Stars & Galaxies**  
  Focuses on the star formation and evolution, as well as the galactic evolution. The formation of the solar system and its implications, the degenerate remnants, and the Milky Way galaxy are covered. Prerequisite: General Physics II & Laboratory (PHY-195/-195L) or consent of instructor.  
 **PHY 255/355 Introduction to Physics Research I–II**  
  Extensive independent or group investigations of a particular topic or set of topics. Designed to be a research experience in preparation for teaching, graduate school, or direct entry into a technical field after graduation. Prerequisite: General Physics II & Laboratory (PHY-195/-195L) or consent of instructor.  
 **PHY 265 Electromagnetism**  
  Studies electromagnetic phenomena at the intermediate level, including circuits, static and quasi-static fields, Maxwell’s equations, radiation, and selected topics in properties of materials. Special topics in vector algebra, scalar and vector point functions, and differential vector calculus are developed and used. Prerequisite: General Physics II & Laboratory (PHY-195/-195L) or consent of instructor.  
 **PHY 275 Classical Mechanics**  
  Studies Newtonian, Lagrangian, and Hamiltonian formulations of the laws of motion. Applications to systems of particles, extended objects, and oscillatory systems. Prerequisite: General Physics II & Laboratory (PHY-195/-195L).  
 **PHY 301 Optics & Waves**  
  Covers the theory of modern optics, wave theory of light, as well as mechanical and electromagnetic oscillations. Introducing a variety of topics, including geometrical and physical optics, mathematics of wave motion, propagation, reflection, refraction, phenomenon of resonance in oscillations, and Fourier formalism. Prerequisite: Electromagnetism (PHY-265) or consent of instructor.  
 **PHY 311 Renewable Energy (WE)**  
  Reviews the scientific fundamentals of renewable energy production. Basic thermodynamic principles of the heat engines, the hydrogen production and storage methods are covered. Renewable energy sources including solar, biomass, wind, and ocean engine designs are discussed in detail. Also includes some hands-on experiments on solar, wind, and fuel cell systems. Prerequisite: General Physics II & Laboratory (PHY-195/-195L), or consent of instructor.  
 **PHY 315 Thermodynamics & Stat Mech**  
  Introduces fundamental concepts such as temperature, phase transitions, the first, second, and the third laws of thermodynamics, and the work/entropy relationship. The Statistical Mechanics half covers a mathematical treatment of partition functions, thermal properties of solids, and critical-point transitions. Problems will involve theoretical situations, as well as real-life scenarios involving engines, pumps, and energy transfer-related problems in which the students will design their own unique solutions. Prerequisite: Modern Physics (PHY-235) and Advanced Laboratory 1 (PHY-236) or consent of instructor.  
 **PHY 321 Health Physics**  
  Studies the use of physics in medicine. The basic principles of the medical physics applications, such as radiation therapy, dosimetry, computed tomography (CT), positron emission tomography (PET), single photon emission spectroscopy (SPECT), Magnetic Resonance Imaging (MRI), Nuclear Magnetic Resonance (NMR), and crystallography are covered. Prerequisite: General Physics II & Laboratory (PHY-195/-195L), or consent of instructor.  
 **PHY 335 Quantum Mechanics**  
  Introduces the formal treatment of quantum mechanics. This course covers the Schrodinger wave equation, the Dirac Braket notation, operator formalism, spin and angular momentum, the wave equation in one and three dimensions, and perturbation theory. Prerequisite: Modern Physics (PHY-235) and Advanced Lab 1 (PHY-236).  
 **PHY 341 Space Plasma Physics**  
  Focuses on the behavior of plasma in space environment. Covers the plasma parameters, waves, the planetary atmospheres, ionospheres, and magnetospheres. Prerequisite: Introduction to Astrophysics (PHY-241) or consent of instructor.  
 **PHY 425 Solid State Physics**  
  Studies the structure and properties of crystalline and amorphous solids. The main topics include crystal structure and quantized vibrations (phonons); electronic band structure and its relation to electrical, thermal, and optical behavior; semiconductors and superconductors. Prerequisite: Modern Physics (PHY-235), Advanced Lab 1 (PHY-236), and Mathematical Methods for Physicists (PHY-231); or consent of instructor.  
 **PHY 441 Relativity and Cosmology**  
  An introduction to Einstein’s general theory of relativity, as well as the intervals, geodesics, black holes, and close binary star systems. The course starts with an introduction to tensor calculus, then covers the Newtonian, relativistic and observational cosmology, and the physics of the early Universe. Prerequisite: Modern Physics (PHY-235), Advanced Lab 1 (PHY-236), and Mathematical Methods for Physicists (PHY-231); or consent of instructor.  
 **PHY 444 Ind Study-Physics**  
  Allows independent study of topics under the guidance of the department: experimental or pedagogical research on a problem predefined by the student in consultation with the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: demonstrated initiative and self-discipline, four courses in physics, and consent of department chair.  
 **PHY 451 Particle Physics**  
  Reviews the Standard Model, particle detection techniques, and the particle physics experiments. The nuclear weak, strong, and the electromagnetic interactions, Feynman diagrams, quark model, relativistic kinematics are also covered. Prerequisite: Modern Physics (PHY-235) and Advanced Lab 1 (PHY-236), or consent of instructor.  
 **PHY 454 Summer Research**  
  May be taken more than once for credit for a maximum of 2.0 credits. Prerequisite: consent of instructor.  
 **PHY 464/474 Junior-Senior Seminar I and II**  
  Presentations and discussions of advanced topics unavailable through the regular catalog offerings, and appropriate to students enrolled. Prerequisite: Modern Physics (PHY-235) or consent of instructor.  
 **PHY 484 Advanced Topics in Physics**  
  Covers several instructional modules. The content corresponds to material usually covered in the second-semester of an advanced, year-long course. Core modules include quantum mechanics (e.g., Bell’s theorem) and electromagnetism (e.g., stress tensor). The four remaining modules are chosen from topics that include optics, fluid dynamics, experimental techniques, nuclear physics, geophysics, advanced classical mechanics, waves, statistical mechanics, and atomic physics. Prerequisite: Quantum Mechanics (PHY-335) and Electromagnetism (PHY-265), or consent of instructor.  
 **PHY 494 Internship in Physics**  
  Investigates an area of interest through field placement supervised by a faculty member of the department. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major in physics. Prerequisites: completion of a physics minor or junior standing and consent of department chair.  

### Courses in Engineering Physics  

 **ENR 101 Introduction to Engineering Design**  
  Provides first-year engineering students with an introduction to how to solve open-ended problems in a hands-on manner using critical thinking and workplace skills. Students are expected to work in multidisciplinary teams to learn through doing, with an emphasis on defining and diagnosing the problem through a holistic lens of technology, people, and culture. Course also covers engineering ethics, and requires successfully completing a team design project. Oral and written presentations are required.  
 **ENR 101L Engineering Design Laboratory**  
  Introduces the concepts of engineering design. Topics include 2-dimensional and 3-dimensional drawings, CAD software, 3D printing, and hands-on sessions on building 3D models with various materials, introduction to power tools, and wood machine shop. Corequisite: Introduction to Engineering Design (ENR-101) or DS-130 Innovation by Design is required. (0.5 course credit)  
 **ENR 145 Comput Mthds for Physicist & Engin**  
  Computational Physics Methods for Physicists & Engineers
Designed to be a survey of the computational methods used by physicists. Students learn basics of Linux systems, Python, Jupyter Notebook, Github, shell scripting, and data analysis tools, such as MATLAB and ROOT. The students will learn and apply simulation tools and electronic interfaces to their design projects. This course is project-based and requires intensive individual participation in prototyping.  
 **ENR 221 Materials Science Engineering 1**  
  ENR-221 Materials Science Engineering 1 Introduces the relationship of atomic arrangement with microscopic and macroscopic material properties using fundamentals of physics and chemistry. Covers the crystalline and amorphous structures, the defects and grain boundaries, phase diagrams and time-dependency of phase transformation. The emphasis is placed on understanding the different aspects of atomic arrangement and how to analyze them. As an essential component of the class, students will learn how to work with different analysis techniques available in our laboratories and develop a project involving the characterization of an unknown material.  
 **ENR 321 Materials Science Engineering 2**  
  ENR-321 Materials Science Engineering 2 
Continuation of Materials Science Engineering 1, this course will follow up by studying the relationship between structure and property, as well as introducing processing methods. Examples of these relationships are mechanical, optical, magnetic, electrical, and thermal properties. As an essential component for the class, students will work in groups to analyze and develop solutions for case studies involving challenges faced by the industry, applying concepts of design thinking. Prerequisite: Materials Science Engineering 1 (ENR-221) or consent of instructor.  
 **+++MISSING INFO: c.enr325_325l.long +++**  
  +++MISSING INFO: c.enr325_325l.desc +++  
 **ENR 355 Robotics and Sensors**  
  Introduces the basics of robotics and automation; mechanical design, principles of motion and kinematics for automated devices. The students will complete projects while learning about the system requirements identification, sensor, and microcontroller integration. The course exposes students to the current research in robotics research such as autonomous vehicles, assistant robots, and field robots for extreme conditions. Prerequisite: Electromagnetism (PHY-265).  
 **ENR 405 Senior Design 1**  
  Introduces final project work. The class is divided into two parts. In the first portion, the students will learn effective team organization, team planning, time management, literature research methods, record keeping, technical writing, professional ethics and development, among other skills required to be an effective engineer in the classroom. In parallel, the students will be developing, under the supervision of a mentor, their project in which they will design a project and execute all steps. Prerequisites: Computational Methods in Physics and Engineering (ENR-145) and senior standing.  
 **ENR 415 Senior Design 2**  
  Continues the work of Senior Design I. At the end of Senior Design 2 students are expected to finalize their project. The course focuses on the development of the scientific project and culmination of a written report and an oral presentation. The course also includes visits to regional research and manufacturing facilities. Prerequisite: Senior Design 1 (ENR-405).  

