## Public Relations (Collateral Major)  

Carstens (Administrative Coordinator)  
 
The Public Relations major   prepares students for a career in public relations and related communication fields. The major integrates course work in business administration, professional writing, graphic arts, and other disciplines relevant to public relations. The curriculum encourages the development of skills and perspectives desirable for learning to manage the successful communication between an organization and its publics.  

Students wishing to complete this major must consult with the Public Relations administrative coordinator no later than the first term of their junior year. Students wishing to register for any of the art courses that count toward this major should consult with the art and art history department prior to course registration.  

### Collateral Major in Public Relations  

A major in Public Relations requires a cumulative 2.0 GPA in all courses counted toward the major.  

Concurrent completion of any of the majors listed on p. 21 of the Catalog for a B.A. (residential) is required.  

1. **One** of the following:  
	* {{< var c.art104.long >}}  
	* {{< var c.art115.long >}}  
	* {{< var c.art145.long >}}  
	* {{< var c.art150.long >}}  
2. {{< var c.pr205.long >}}   
3. {{< var c.bus330.long >}}  
4. {{< var c.bus460.long >}}  
5. **One** of the following:  
	* {{< var c.com141.long >}}  
	* {{< var c.com241.long >}}  
6. **One** of the following (producing a portfolio of writings related to the field of public relations):  
	* {{< var c.bus461.long >}}  
	* {{< var c.ecc345.long >}}  
7. **One** of the following:  
	* {{< var c.bus494.long >}} (with public relations or advertising as a major component)  
	* {{< var c.pr494.long >}}  
	* Summer Internship with public relations as a major component  
8. **Three** of the following. No more than two courses may be selected from within any one department. (Students majoring in Business Administration may select no more than one course with either a BUS or an ACC prefix. Students majoring in Communication Studies may select no more than one course with a COM prefix.)  
	* {{< var c.acc171.long >}}  
	* {{< var c.art104.long >}} (if not used to satisfy #1)  
	* {{< var c.art115.long >}} (if not used to satisfy #1)  
	* {{< var c.art145.long >}} (if not used to satisfy #1)  
	* {{< var c.art150.long >}} (if not used to satisfy #1)  
	* {{< var c.art363.long >}} (if not used to satisfy #1)  
	* {{< var c.bus250.long >}}  
	* {{< var c.bus375.long >}}  
	* {{< var c.bus461.long >}} (if not used to satisfy #6)  
	* {{< var c.bus464.long >}} , subject to topic approval by PR administrative coordinator  
	* {{< var c.bus465.long >}} , subject to topic approval by PR administrative coordinator  
	* {{< var c.com125.long >}}  
	* {{< var c.com157.long >}}  
	* {{< var c.com341.long >}}  
	* {{< var c.com347.long >}}  
	* {{< var c.com141.long >}} (if not used to satisfy #5)  
	* {{< var c.com322.long >}}  
	* {{< var c.ecc345.long >}} (if not used to satisfy #6)  

### Courses in Public Relations  
 **{{< var c.pr205.long >}}**  
  {{< var c.pr205.desc >}}  
 **{{< var c.pr494.long >}}**  
  {{< var c.pr494.desc >}}  

