## Psychology {#sec-psychology}  
Brown, Castillo, Chihak, Farrell, Lee (Chair), Recker  

Psychology is the scientific study of behavior and mental processes—the basis for both a field of scientific knowledge and of professional application. Both required and elective courses in psychology are grounded in the scientific approach. As an important tool for the understanding of both theory and data, the study of basic statistical and methodological concepts is included among courses required of all students majoring in psychology.  

In addition to a major in **PSYCHOLOGY**, the College also offers a collateral major in **NEUROSCIENCE** and a concentration in **ORGANIZATIONAL SCIENCE**.  

### Secondary Education Certification in Psychology  
Students seeking certification to teach psychology at the secondary level are strongly encouraged to speak with an advisor in Education as early as possible in their program of studies.  

### Psychology Major  
A major in Psychology requires a cumulative 2.0 GPA in all courses counted toward the major.  

1. {{< var c.psy100.long >}}  
2. {{< var c.psy200.long >}}   
3. {{< var c.psy295.long >}}  
4. {{< var c.psy300.long >}}  
5. **One**of the following:  
	* {{< var c.psy454.long >}}  
	* {{< var c.psy494.long >}}   
6. **One** of the following:  
	* {{< var c.psy205.long >}}  
	* {{< var c.psy235.long >}}  
7. **One** of the following:  
	* {{< var c.psy215.long >}}  
	* {{< var c.psy245.long >}}  
	* {{< var c.psy255.long >}}  
8. **One** of the following:  
	* {{< var c.psy250.long >}}  
	* {{< var c.psy260.long >}}  
	* {{< var c.psy270.long >}}  
9. **One** of the following:  
	* {{< var c.psy325_325l.long >}}  
	* {{< var c.psy335_335l.long >}}  
	* {{< var c.psy355_355l.long >}}  
10. **Two** additional courses in psychology, one of which must be 300 level or above.

### Organizational Science Concentration in Psychology  
Students completing a major in Psychology may elect to also complete a concentration in Organizational Science. This concentration is designed to acquaint students with human behavior in organizations from both theoretical and applied perspectives. It aims to prepare students to carry out various human resources, organizational development, customer service, and institutional research functions in a variety of organizational settings. It also prepares students for graduate study in the fields of Industrial/Organizational (I/O) Psychology, Human Resources, and other similar fields.  

To complete the Organizational Science concentration, students must meet the following requirements. Courses taken to fulfill the Psychology major may be used to also fulfill requirements in the Organizational Science concentration.  

1.	Completion of a major in Psychology 
2.	Completion of the following **six** courses in which a cumulative 2.0 GPA must be earned. At least three of the six courses must be completed at Coe:
	* {{< var c.psy245.long >}}  
	* {{< var c.psy255.long >}}  
	* {{< var c.psy355_355l.long >}}  
	* {{< var c.psy465.long >}}  
	* {{< var c.bus300.long >}}  
	* {{< var c.bus315.long >}}  

### Courses in Psychology

 **{{< var c.psy100.long >}}**  
  {{< var c.psy100.desc >}}  
 **{{< var c.psy137.long >}}**  
  {{< var c.psy137.desc >}}  
 **{{< var c.psy200.long >}}**  
  {{< var c.psy200.desc >}}  
 **{{< var c.psy205.long >}}**  
  {{< var c.psy205.desc >}}  
 **{{< var c.psy208.long >}}**  
  {{< var c.psy208.desc >}}  
 **{{< var c.psy215.long >}}**  
  {{< var c.psy215.desc >}}  
 **{{< var c.psy235.long >}}**  
  {{< var c.psy235.desc >}}  
 **{{< var c.psy245.long >}}**  
  {{< var c.psy245.desc >}}  
 **{{< var c.psy250.long >}}**  
  {{< var c.psy250.desc >}}  
 **{{< var c.psy255.long >}}**  
  {{< var c.psy255.desc >}}  
 **{{< var c.psy260.long >}}**  
  {{< var c.psy260.desc >}}  
 **{{< var c.psy270.long >}}**  
  {{< var c.psy270.desc >}}  
 **{{< var c.psy295.long >}}**  
  {{< var c.psy295.desc >}}  
 **{{< var c.psy300.long >}}**  
  {{< var c.psy300.desc >}}  
 **{{< var c.psy325_325l.long >}}**  
  {{< var c.psy325.desc >}}  
 **{{< var c.psy335_335l.long >}}**  
  {{< var c.psy335.desc >}}  
 **{{< var c.psy350.long >}}**  
  {{< var c.psy350.desc >}}  
 **{{< var c.psy354.long >}}**  
  {{< var c.psy354.desc >}}  
 **{{< var c.psy355_355l.long >}}**  
  {{< var c.psy355.desc >}}  
 **{{< var c.psy415.long >}}**  
  {{< var c.psy415.desc >}}  
 **{{< var c.psy444.long >}}**  
  {{< var c.psy444.desc >}}  
 **{{< var c.psy450.long >}}**  
  {{< var c.psy450.desc >}}  
 **{{< var c.psy454.long >}}**  
  {{< var c.psy454.desc >}}  
 **{{< var c.psy464.long >}}**  
  {{< var c.psy464.desc >}}  
 **{{< var c.psy465.long >}}**  
  {{< var c.psy465.desc >}}  
 **{{< var c.psy494.long >}}**  
  {{< var c.psy494.desc >}}  
