## Spanish/Spanish Studies

Peach, Muñoz Pérez, Rodríguez Moreno (Program Coordinator).

### Spanish Major 
A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in Spanish. 

Students who major in Spanish complete a minimum of eight courses in Spanish beyond SPA 225 Intermediate Spanish II , though SPA 148 Spanish Literature in Translation may be taken as one of the eight. SPA 115 Elementary Spanish I , SPA 125 Elementary Spanish II , SPA 135 Spanish Review & Preparation , SPA 215 Intermediate Spanish I , and SPA 225 Intermediate Spanish II are regarded as skill-building courses, and do not count toward the major in Spanish. Spanish students are urged to substitute study abroad in a program approved by the College and the department for up to three courses for the major. One Hispanic literature course (SPA-336 or above) must be taken in the senior year. 

SPA 464 Capstone in Spanish is required during the final spring term before graduation. Students selecting Spanish as a second teaching field should complete a minimum of four Spanish courses numbered 315 or above. Any advanced courses taken for the second teaching field should include SPA 315 Spanish Composition & Conversation . 

### Spanish Minor

A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in Spanish. 

The minor in Spanish requires the completion of four courses beyond SPA 225 Intermediate Spanish II , though with the consent of department chair, SPA 148 Spanish Literature in Translation may be taken as one of the four. SPA 115 Elementary Spanish I , SPA 125 Elementary Spanish II , SPA 135 Spanish Review & Preparation , SPA 215 Intermediate Spanish I , and SPA 225 Intermediate Spanish II are regarded as skill-building courses, and do not count toward the minor in Spanish. 

### Spanish Studies Major
 
A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in Spanish Studies. 

The Spanish Studies major requires: 1) successful completion of four courses beyond SPA 225 Intermediate Spanish II , with SPA 336 Hispanic Life & Culture: Latin Amer or SPA 338 Hispanic Life & Culture: Europe recommended as one of the four; and 2) successful completion of a departmentally approved list of five courses proposed by the student which exhibits both internal coherence and relevance to the coursework in Spanish. Typically, application to the department for the approval of the interdisciplinary elected courses is to be made no later than the Spring Term of the junior year. SPA 115 Elementary Spanish I , SPA 125 Elementary Spanish II , SPA 135 Spanish Review & Preparation, SPA 215 Intermediate Spanish I , and SPA 225 Intermediate Spanish II are regarded as skill-building courses, and do not count toward the major in Spanish Studies.

### Courses in Spanish
 **SPA 115/125 Elementary Spanish I and II**  
  Develops basic proficiencies in oral and written communication for students with no previous knowledge of Spanish. The first term emphasizes oral practice in the context of Hispanic Cultures. The second term builds upon acquired skills and includes class discussion, short reading, and writing activities. Prerequisite: appropriate Spanish Placement exam results or consent of instructor.  
 **SPA 129 Intensive Elementary Spanish I-II**  
  Offers students with no prior training a year’s worth of basic communicative skills in Spanish in a single term. Students will be introduced to beginning grammar based on a communicative and task-supported curriculum that helps them to develop skills in reading, listening, speaking, and writing in Spanish to engage in interpretive, interpersonal, and presentational modes of communication. (Offered in the summer)  
 **SPA 135 Spanish Review & Preparation**  
  Prepares students who have had some limited experience in Spanish to enter Intermediate Spanish SPA-215 the following term. It provides a complete review of college level elementary Spanish vocabulary, grammar, and oral and written communication. This course is appropriate for students with one recent year of secondary school Spanish or two years if there are significant gaps in learning or if some time has elapsed since their earlier study of Spanish. Prerequisite: appropriate Spanish Placement exam results or consent of instructor.  
 **SPA 148 Spanish Literature in Translation**  
  Focuses on reading and analysis of selected works by major Hispanic authors, centering on a theme, author, time period, or genre. The content varies from term to term. Students pursuing a major or minor in Spanish must write a paper in Spanish. Taught in English.  
 **SPA 215 Intermediate Spanish I**  
  Follows and builds upon the skills and proficiencies acquired in Continuation of Elementary Spanish, with particular emphasis on oral practice and a review of grammatical structures. Prerequisite: Elementary Spanish II (SPA-125), Spanish Review and Preparation (SPA-135), appropriate Spanish Placement exam results or consent of instructor.  
 **SPA 258 Spanish Lang Learn in Spain**  
  Features immersive leaning of Spanish in the context of a study abroad course supervised by a Coe faculty member. It includes three hours of daily instruction in Spanish with an additional hour studying the culture and traditions of the country. Prerequisite: consent of instructor. (Offered May Experiential Term only)  
 **SPA 315 Spanish Composition & Conversation**  
  Focuses on further development of oral and written communication skills in appropriate cultural contexts, and includes a review of key problematic structures of the Spanish language. Students write frequent compositions using a variety of structures of the Spanish language, and class time concentrates on conversational activities. Prerequisite: Intermediate Spanish II (SPA-225), appropriate Spanish Placement exam results or consent of instructor.  
 **SPA 325 Spanish Language & Literature**  
  Continues Spanish Composition and Conversation, with an emphasis on speaking and writing. A wide range of short literary texts is also studied. Prerequisite: Intermediate Spanish II (SPA-225), appropriate Spanish placement exam, or consent of instructor.  
 **SPA 330 Spanish for Heritage Speakers**  
  Focuses on the specific linguistic and communicative needs of heritage speakers of Spanish in the context of
exploring issues of identity, immigration and community in contemporary Latino communities in the U.S.
Assessments based on an exit interview and a portfolio of formal writing. Prerequisite: Spanish placement test or
approval of the instructor.  
 **SPA 336 Hispanic Life & Culture: Latin Amer**  
  Offers an interdisciplinary overview of the culture and history of Latin America as portrayed in literature, art, architecture, and film. Particular attention is given to the way the past has created and shaped contemporary Hispanic culture in Latin America. Prerequisite: Spanish Composition and Conversation (WE) (SPA-315), Spanish for Heritage Speakers (SPA-304), or Spanish Language and Literature (WE) (SPA-325). (Offered alternate years)  
 **SPA 338 Hispanic Life & Culture: Europe**  
  Offers an interdisciplinary overview of the culture and history of Spanish in Europe as portrayed in literature, art, architecture, and film, with particular emphasis on how Spanish cultural history shapes the present. Particular attention is given to the way the past has created and shaped Hispanic culture in Spain. Prerequisite: Spanish Composition and Conversation (WE) (SPA-315), Spanish for Heritage Speakers (SPA-304), or Spanish Language and Literature (WE) (SPA-325). (Offered alternate years)  
 **SPA 339 Spanish for Health Care**  
  Focuses on providing Spanish language proficiency for students planning careers in the area of healthcare. Emphasis is placed on the healthcare vocabulary and the culture of the Latino population living in the United States. Local outreach is a required component of this course. Students visit local health clinics, where they are able to volunteer, using their knowledge of Spanish and working as translators. Prerequisite: Intermediate Spanish II (SPA-225) or consent of instructor.  
 **SPA 345 Introduction to Hispanic Literature**  
  Introduces Peninsular and Spanish-American literary works, with an emphasis on basic critical concepts, terminology, and methods. A wide range of texts is studied, beginning with poems and short narratives, and ending with longer works. Prerequisite: Spanish Composition and Conversation (WE) (SPA-315) or Spanish Language and Literature (WE) (SPA-325), or Spanish for Heritage Speakers (SPA-304).  
 **SPA 349 Business Spanish**  
  Focuses on providing Spanish language proficiency for students planning careers in business with emphasis on the variety of Spanish-speaking cultures in the business world and requires local outreach and on-site learning. Prerequisite: Intermediate Spanish II (SPA-225) or consent of instructor.  
 **SPA 394 Directed Learning: Spanish**  
  Allows students to investigate a particular aspect of literature in Spanish unavailable through the regular sequence of courses offered. Periodic conferences and papers are required. May be taken more than once for credit. Prerequisite: Spanish Composition and Conversation (WE) (SPA-315) or Spanish Language and Literature (WE) (SPA-325).  
 **SPA 412 Ecologies:Latin America Environ Lit**  
  Examines Latin American writers and artists who have long focused on nature as a means to address pressing political, social, and ethical issues through literature, ethnographic texts, film and the visual arts. Readings in this class will trace connections between environmental thought and the region's long and multi-layered history of colonialism. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 418 Gender & Sexuality in Hispanic Wrld**  
  Examines constructions and representations of gender, sexuality, and power in Latin American and/or Spanish literature and cultures with particular emphasis on intersections with race/ethnic positioning, sexual identity, and social class. The course adopts an interdisciplinary approach to explore the role and contributions of artists, as well as the reception of their work, with regard to issues surrounding cultural representations of race and ethnicity, masculinity and femininity, gender and sexual identities and LGTBQ+ communities, nationalism and citizenship, and social movements. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 421 Nation, History, and Literature**  
  Focuses on the literature and culture of one nation in the Hispanic world, highlighting their relationship to the specific national history of the country. This class will study a variety of genres: short stories, poetry, and theater. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 428 Indigeneity, Blackness, & EthnicLit**  
  Examines voices of ethnic cultures that have creatively responded to their social and political contexts through literary analysis as well as visual, musical, and other symbolic and representational literacies. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 431 Hispanic Graphic Novel:Theory& Prac**  
  Focuses on providing students with the knowledge to understand cartoons and graphic novels produced in Spanish as a particular medium in relation to a historical context. The class will study theory of comics, the tradition of Hispanic comics, and will hold a workshop where the students learn techniques to develop their own story in a comic format. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338)  
 **SPA 432 Representations of Violence**  
  Explores the relationships between a variety of cultural productions (film, literature, poetry, painting, theater,
performance, TV productions, etc.) and specific accounts of personal and collective violence in socio-political
conflicts in the Hispanic world. Concepts such as memory, trauma, mourning, and pain will be a central part of this
course. Prerequisite: Introduction to Hispanic Literature (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA338).  
 **SPA 442 Popular Culture, Media, & Cultural**  
  Focuses on popular culture with an emphasis on the role of visual and material culture in the Hispanic world as contested territory between power structures and resistance movements. A variety of cultural productions may be included: film, literature, music, internet blogs, YouTube videos, publicity, folklore, dance, TV productions, comic strips, etc. This class will focus on a selected time period and/or geographical region of the Spanish-speaking world. May be taken more than once for credit, if focused on a different region or period. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 443 Cinema & Politics of Representation**  
  Provides a historical and thematic overview of cinema in a selected time period and/or geographical region of the Spanish-speaking world to deepen understanding of and engagement with important and complex cultural issues in relation to both aesthetics and politics, and offers both offers tools and guidance for discussing and writing about film. May be taken more than once for credit, if focused on a different region or period. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 444 Ind Study-Spanish**  
  Allows students to design and undertake a selected project in Spanish under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of department chair.  
 **SPA 446 Latin Am. & Spanish Short Stories**  
  Focuses on the rich and varied literary production of the short story in Latin America and/or Spain. Readings may include a wide range of short narratives with an emphasis on those of the 20th and 21st century. Prerequisite: Introduction to Hispanic Literature (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 451 Hispanic Cross-Over Literature**  
  Focuses on literature that is designed for children or for both adults and children. Texts for this class will intersect with notions of memory, education, censorship, and the dialogue between image and written text. The class will emphasize the picture-book (álbum ilustrado), and it will hold a workshop where the students learn techniques to develop their own. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 455 Spanish Drama**  
  Focuses on providing students with the elements to appreciate and analyze Spanish and US Latinx theatre and performance art. This class will introduce students to the various techniques, themes, and images used to express, criticize, or romanticize Hispanic society and life, and may include the staging of a play. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336/ SPA-338).  
 **SPA 457 US LatinX Literature**  
  Focuses on the major trends of LatinX literature that highlight the experiences of LatinX people within the US. Topics will include bilingualism, code-switching, identity, borders, immigration, and exile in LatinX groups such as Chicano/a, Nuyorican, Boricuas, Dominicans, etc. Their cultural productions will be analyzed within their social and political context and texts assigned will be in English, Spanish or mixed. Prerequisite: Introduction to Hispanic Literature (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 458 Travel Writing & Transatlantic Lit**  
  Explores the varying perceptions of life, history, culture, traditions, and customs in Spain and Latin America across time and space through the accounts of travel narratives through interdisciplinary perspectives. Prerequisite: Introduction to Hispanic Literature (SPA-345) or Hispanic Life and Culture (SPA-336 / SPA-338).  
 **SPA 475 Topics in Hispanic Literature**  
  Centers on a particular theme, author, region, time period, or genre of Hispanic literature. Approach and content vary from term to term as determined by the instructor. May be taken more than once, provided the topics are substantially different. Prerequisite: Introduction to Hispanic Literature (WE) (SPA-345) or Hispanic Life and Culture (SPA-336/ SPA-338).  
 **SPA 476 Topics in Hispanic Society &Culture**  
  Topics in Hispanic Society and Culture (WE) 
Centers on a particular theme, author, region, time period, or genre of Hispanic culture and society. May be taken more than once, provided the topics are substantially different. Prerequisite: Consent of instructor  
 **SPA 464 Capstone in Spanish**  
  Serves as the final requirement designed for Spanish majors who are graduating seniors. Students will polish a research paper written for any of the advanced classes in a previous semester. They will demonstrate the skills acquired throughout the major, such as: critical reading and writing, textual analysis, and original thinking regarding a historical and cultural topic related to Latin America and/or Spain. At the end of the course, students should present their research work on a conference-like panel open to the public. (Offered every spring)  
 **SPA 494 Internship in Spanish**  
  Allows students to explore a career area related to Spanish. Application and supervision through the Internship Specialist. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major or minor in Spanish. Prerequisites: junior standing and consent of department chair.  
